REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Night Purge Mode
REM ======================================================================

REM ***** Determine cooling availability *****
IF {device-name}-HTG-LOCKOUT THEN START A
IF {device-name}-CLG-LOCKOUT THEN STOP A

REM ***** Calculate night purge start time *****
{device-name}-NP-FIRST-START = {device-name}-OCC-MODE-FIRST-ON - ( {device-name}-OSH-MAX-PRESTART * 1.6667 + {device-name}-NP-MAX-RT * 1.6667 )
{device-name}-NP-FIRST-START = LIMIT( {device-name}-NP-FIRST-START , 0:00:00 , 23:59:59 )

REM ***** Time window check *****
IF TIME > {device-name}-NP-FIRST-START AND TIME < {device-name}-NP-FIRST-START + {device-name}-NP-MAX-RT * 1.6667 THEN START B ELSE STOP B

REM ***** OA enthalpy vs space enthalpy check *****
C = SWITCH( C , {device-name}-NET-OA-ERH , {device-name}-AVG-RM-ERH , {device-name}-AVG-RM-ERH - 2 )

REM ***** Only purge when unoccupied *****
IF {device-name}-OCC-MODE <> 4 THEN STOP {device-name}-NP-MODE , END

REM ***** Enable night purge when conditions met *****
IF A AND B AND C THEN START {device-name}-NP-MODE ELSE STOP {device-name}-NP-MODE
