REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Freeze Protection Mode
REM ======================================================================

REM ***** Limit freeze protection setpoint *****
{device-name}-FRZ-PRTC-SP = LIMIT( {device-name}-FRZ-PRTC-SP , {device-name}-ERW-DEFROST-SP , 35 )

REM ***** Determine freeze protection mode from OAT *****
A = SWITCH( A , {device-name}-NET-OAT , {device-name}-FRZ-PRTC-SP + 2 , {device-name}-FRZ-PRTC-SP )
IF A THEN START {device-name}-FRZ-PRTC-MODE ELSE STOP {device-name}-FRZ-PRTC-MODE
