REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Configuration Program
REM  Reads network data, calculates enthalpies, processes zone data
REM ======================================================================

REM ***** Set outside air variables from parent controller *****
{device-name}-NET-OAT = {parent}AV1
{device-name}-NET-OAH = {parent}AV2
{device-name}-NET-OA-ERH = ENTHALPY( {device-name}-NET-OAT , {device-name}-NET-OAH , 1 )

REM ***** Set network occupied command *****
{device-name}-NET-OCC-CMD = {parent}BV11

REM ***** Set network snow day *****
{device-name}-SNOW-DAY = {parent}BV9

REM ***** Zone aggregates calculated by ZONE-COORD-PRG (not read from parent) *****

REM ***** Calculate return air enthalpy *****
{device-name}-RA-ERH = ENTHALPY( {device-name}-RAT , {device-name}-RAH , 1 )

REM ***** Calculate room average enthalpy *****
{device-name}-AVG-RM-ERH = ENTHALPY( {device-name}-AVG-RMT , {device-name}-RMH , 1 )

REM ***** Determine active discharge static pressure *****
{device-name}-ACT-DSP = {device-name}-SA-DSP

REM ***** Determine first occupancy for local schedule *****
{device-name}-LOCAL-FIRST-ON = SCHED( 1 , FIRST_ON )

REM ***** Report AHU OK status to parent *****
{parent}BV10 = {device-name}-AHU-OK

REM ***** Publish SAT for VAV network *****
{device-name}-SAT-PUB = {device-name}-SAT

REM ***** Hot Water Supply Temp monitoring *****
REM AV155 = HW supply temp from plant (commissioning-set)
REM HWS-OK = 1 if AV155 > 90°F (plant has water), 0 otherwise
IF {device-name}-HWST > 90 THEN {device-name}-HWS-OK = 1 ELSE {device-name}-HWS-OK = 0
