10 REM ======================================================================
20 REM  Generated by SBS Composition Engine v2
30 REM  {device-name} — Optimum Start Heat / Cool Mode
40 REM ======================================================================
50 Z = MAX( {device-name}-OSH-MODE , {device-name}-OSC-MODE )
60 IF- Z THEN START {device-name}-STNDBY-MODE
70 REM ***** Calculate pre-start times based on OAT *****
80 A = SLIDE( {device-name}-NET-OAT , 50 , 20 , 0 , {device-name}-OSH-MAX-PRESTART * 1.66667 )
90 B = SLIDE( {device-name}-NET-OAT , 50 , 80 , 0 , {device-name}-OSC-MAX-PRESTART * 1.66667 )
100 REM ***** Determine first-on time *****
110 IF {device-name}-USE-LOC-SCHD THEN {device-name}-OCC-MODE-FIRST-ON = {device-name}-LOCAL-FIRST-ON ELSE {device-name}-OCC-MODE-FIRST-ON = {device-name}-MSTR-FIRST-ON
120 REM ***** Disable on snow days *****
130 IF {device-name}-SNOW-DAY THEN STOP {device-name}-OSH-MODE , STOP {device-name}-OSC-MODE , END
140 REM ***** Disable at occupancy *****
150 IF {device-name}-OCC-CMD THEN STOP {device-name}-OSH-MODE , STOP {device-name}-OSC-MODE , END
160 REM ***** Lock-in OSH once enabled — stop when RAT satisfied *****
170 IF TIME-ON( {device-name}-OSH-MODE ) > {device-name}-OSH-MIN-RUNTIME * 1.66667 AND {device-name}-RAT > {device-name}-OSH-RAT-SP THEN STOP {device-name}-OSH-MODE
180 IF {device-name}-OSH-MODE THEN END
190 REM ***** Lock-in OSC once enabled *****
200 IF TIME-ON( {device-name}-OSC-MODE ) > {device-name}-OSC-MIN-RUNTIME * 1.66667 AND {device-name}-RAT < {device-name}-OSC-RAT-SP THEN STOP {device-name}-OSC-MODE
210 IF {device-name}-OSC-MODE THEN END
220 REM ***** Optimum start heat *****
230 IF {device-name}-HTG-LOCKOUT THEN GOTO 280
240 IF+ TIME < {device-name}-OCC-MODE-FIRST-ON AND TIME > {device-name}-OCC-MODE-FIRST-ON - SLIDE( {device-name}-LOW-SP-DEV , 0 , -6 , 0 , A ) THEN START {device-name}-OSH-MODE
250 IF {device-name}-OSH-MODE THEN END
260 REM ***** Optimum start cool *****
270 IF {device-name}-CLG-LOCKOUT THEN END
280 IF+ TIME < {device-name}-OCC-MODE-FIRST-ON AND TIME > {device-name}-OCC-MODE-FIRST-ON - SLIDE( {device-name}-HIGH-SP-DEV , 0 , 6 , 0 , B ) THEN START {device-name}-OSC-MODE
