REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Heating / Cooling Lockout
REM ======================================================================

REM ***** Set lockout icons *****
IF {device-name}-HTG-LOCKOUT THEN STOP {device-name}-HTG-LO-ICON ELSE START {device-name}-HTG-LO-ICON
IF {device-name}-CLG-LOCKOUT THEN STOP {device-name}-CLG-LO-ICON ELSE START {device-name}-CLG-LO-ICON

REM ***** Heating lockout *****
IF MAX( {device-name}-NSB-MODE , {device-name}-OSH-MODE , {device-name}-FRZ-PRTC-MODE ) THEN STOP {device-name}-HTG-LOCKOUT , START {device-name}-CLG-LOCKOUT , END
A = SWITCH( A , {device-name}-NET-OAT , {device-name}-HTG-LO-SP - 2 , {device-name}-HTG-LO-SP )
IF A THEN START {device-name}-HTG-LOCKOUT ELSE STOP {device-name}-HTG-LOCKOUT

REM ***** Cooling lockout *****
IF MAX( {device-name}-NSF-MODE , {device-name}-OSC-MODE ) THEN STOP {device-name}-CLG-LOCKOUT , START {device-name}-HTG-LOCKOUT , END
C = SWITCH( C , {device-name}-NET-OAT , {device-name}-CLG-LO-SP + 2 , {device-name}-CLG-LO-SP )
IF C THEN START {device-name}-CLG-LOCKOUT ELSE STOP {device-name}-CLG-LOCKOUT
