REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Configuration Program
REM  Reads network data, calculates enthalpies, processes zone data
REM ======================================================================

REM ***** Set outside air variables from parent controller *****
{device-name}-NET-OAT = {parent}AV1
{device-name}-NET-OAH = {parent}AV2
{device-name}-NET-OA-ERH = ENTHALPY( {device-name}-NET-OAT , {device-name}-NET-OAH , 1 )

REM ***** Set network occupied command *****
{device-name}-NET-OCC-CMD = {parent}BV11

REM ***** Set network snow day *****
{device-name}-SNOW-DAY = {parent}BV9

REM ***** Set zone variables from parent *****
{device-name}-HIGH-RMT = {parent}AV17
{device-name}-AVG-RMT = {parent}AV18
{device-name}-LOW-RMT = {parent}AV19
{device-name}-CLG-DMD = {parent}AV111
{device-name}-HTG-REQS = {parent}AV112
{device-name}-ZONE-DMP-POS = {parent}AV113
{device-name}-AHU-TOT-ZONES = {parent}AV114
{device-name}-BYPASS-REQS = {parent}AV115
{device-name}-NSB-REQS = {parent}AV116
{device-name}-NSF-REQS = {parent}AV117
{device-name}-HIGH-SP-DEV = {parent}AV118
{device-name}-LOW-SP-DEV = {parent}AV119
{device-name}-MSTR-FIRST-ON = {parent}AV16

REM ***** Calculate return air enthalpy *****
{device-name}-RA-ERH = ENTHALPY( {device-name}-RAT , {device-name}-RAH , 1 )

REM ***** Calculate room average enthalpy *****
{device-name}-AVG-RM-ERH = ENTHALPY( {device-name}-AVG-RMT , {device-name}-RMH , 1 )

REM ***** Determine active discharge static pressure *****
{device-name}-ACT-DSP = {device-name}-SA-DSP

REM ***** Determine first occupancy for local schedule *****
{device-name}-LOCAL-FIRST-ON = SCHED( 1 , FIRST_ON )

REM ***** Report AHU OK status to parent *****
{parent}BV10 = {device-name}-AHU-OK

REM ***** Publish SAT for VAV network *****
{device-name}-SAT-PUB = {device-name}-SAT

REM **** BV151 — Link to HW plant OK status at commissioning
REM **** BV152 — Link to CHW plant OK status at commissioning
REM **** AV155 — Link to HW plant supply temp at commissioning
