REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Occupancy Modes
REM  1=Occupied / 2=Bypass / 3=Standby / 4=Unoccupied
REM  5=NSB / 6=NSF / 7=OSH / 8=OSC
REM ======================================================================

REM ***** Snow day override — force unoccupied *****
IF {device-name}-SNOW-DAY THEN STOP {device-name}-OCC-CMD , {device-name}-OCC-MODE = 4 , GOTO 170
IF {device-name}-USE-LOC-SCHD THEN {device-name}-OCC-CMD = sched1 ELSE {device-name}-OCC-CMD = {device-name}-NET-OCC-CMD

REM ***** Determine occupied mode *****
IF {device-name}-OCC-CMD THEN {device-name}-OCC-MODE = 1 , STOP {device-name}-BYPASS-MODE , STOP {device-name}-STNDBY-MODE , STOP {device-name}-NSB-MODE , STOP {device-name}-NSF-MODE , END

REM ***** Determine bypass mode *****
{device-name}-BYPASS-MODE = SWITCH( {device-name}-BYPASS-MODE , {device-name}-BYPASS-REQS , {device-name}-BYPASS-REQS-SP * 0.5 , {device-name}-BYPASS-REQS-SP )
IF {device-name}-BYPASS-MODE THEN {device-name}-OCC-MODE = 2 , END

REM ***** Determine OSH, OSC, and standby modes *****
IF {device-name}-OSH-MODE THEN {device-name}-OCC-MODE = 7 , END
IF {device-name}-OSC-MODE THEN {device-name}-OCC-MODE = 8 , END
IF {device-name}-STNDBY-MODE THEN {device-name}-OCC-MODE = 3 , END

REM ***** Determine night setback mode *****
{device-name}-NSB-MODE = SWITCH( {device-name}-NSB-MODE , {device-name}-NSB-REQS , {device-name}-NSB-SP * 0.5 , {device-name}-NSB-SP )
IF {device-name}-NSB-MODE THEN {device-name}-OCC-MODE = 5 , END

REM ***** Determine night set-forward / unoccupied *****
{device-name}-NSF-MODE = SWITCH( {device-name}-NSF-MODE , {device-name}-NSF-REQS , {device-name}-NSF-SP * 0.5 , {device-name}-NSF-SP )
IF {device-name}-NSF-MODE THEN {device-name}-OCC-MODE = 6 ELSE {device-name}-OCC-MODE = 4
