REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Optimum Start Heat / Cool Mode
REM ======================================================================

Z = MAX( {device-name}-OSH-MODE , {device-name}-OSC-MODE )
IF- Z THEN START {device-name}-STNDBY-MODE

REM ***** Calculate pre-start times based on OAT *****
A = SLIDE( {device-name}-NET-OAT , 50 , 20 , 0 , {device-name}-OSH-MAX-PRESTART * 1.66667 )
B = SLIDE( {device-name}-NET-OAT , 50 , 80 , 0 , {device-name}-OSC-MAX-PRESTART * 1.66667 )

REM ***** Determine first-on time *****
IF {device-name}-USE-LOC-SCHD THEN {device-name}-OCC-MODE-FIRST-ON = {device-name}-LOCAL-FIRST-ON ELSE {device-name}-OCC-MODE-FIRST-ON = {device-name}-MSTR-FIRST-ON

REM ***** Disable on snow days *****
IF {device-name}-SNOW-DAY THEN STOP {device-name}-OSH-MODE , STOP {device-name}-OSC-MODE , END

REM ***** Disable at occupancy *****
IF {device-name}-OCC-CMD THEN STOP {device-name}-OSH-MODE , STOP {device-name}-OSC-MODE , END

REM ***** Lock-in OSH once enabled — stop when RAT satisfied *****
IF TIME-ON( {device-name}-OSH-MODE ) > {device-name}-OSH-MIN-RUNTIME * 1.66667 AND {device-name}-RAT > {device-name}-OSH-RAT-SP THEN STOP {device-name}-OSH-MODE
IF {device-name}-OSH-MODE THEN END

REM ***** Lock-in OSC once enabled *****
IF TIME-ON( {device-name}-OSC-MODE ) > {device-name}-OSC-MIN-RUNTIME * 1.66667 AND {device-name}-RAT < {device-name}-OSC-RAT-SP THEN STOP {device-name}-OSC-MODE
IF {device-name}-OSC-MODE THEN END

REM ***** Optimum start heat *****
IF {device-name}-HTG-LOCKOUT THEN GOTO 270 ELSE GOTO 250
IF+ TIME < {device-name}-OCC-MODE-FIRST-ON AND TIME > {device-name}-OCC-MODE-FIRST-ON - SLIDE( {device-name}-LOW-SP-DEV , 0 , -6 , 0 , A ) THEN START {device-name}-OSH-MODE
IF {device-name}-OSH-MODE THEN END

REM ***** Optimum start cool *****
IF {device-name}-CLG-LOCKOUT THEN END ELSE GOTO 290
IF+ TIME < {device-name}-OCC-MODE-FIRST-ON AND TIME > {device-name}-OCC-MODE-FIRST-ON - SLIDE( {device-name}-HIGH-SP-DEV , 0 , 6 , 0 , B ) THEN START {device-name}-OSC-MODE
