REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — HVAC Mode Determination
REM  1=Ventilation / 2=Cooling / 3=Reheat / 4=Heat / 5=Initialize
REM ======================================================================

REM ***** Initialize on power loss *****
IF+ POWER-LOSS THEN {device-name}-HVAC-MODE = 5 , START A
IF TIME-ON( A ) > 0:05:00 THEN STOP A
IF A THEN END

REM ***** Force cooling in NSF, OSC, or heating lockout *****
IF MAX( {device-name}-NSF-MODE , {device-name}-OSC-MODE , {device-name}-HTG-LOCKOUT ) THEN {device-name}-HVAC-MODE = 2 , END

REM ***** Force heating in NSB, OSH, or freeze protection *****
IF MAX( {device-name}-NSB-MODE , {device-name}-OSH-MODE , {device-name}-FRZ-PRTC-MODE ) THEN {device-name}-HVAC-MODE = 4 ELSE {device-name}-HVAC-MODE = 2
