REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — ERW Defrost Mode
REM ======================================================================

REM ***** Limit ERW defrost setpoint *****
{device-name}-ERW-DEFROST-SP = LIMIT( {device-name}-ERW-DEFROST-SP , 10 , 35 )

REM ***** Set bypass damper loop setpoints *****
{device-name}-OA-BYP-SP = {device-name}-ERW-DEFROST-SP + 5
{device-name}-EA-BYP-SP = {device-name}-ERW-DEFROST-SP + 5

REM ***** Determine defrost mode from ERW exhaust leaving temp *****
IF TIME-ON( {device-name}-SF-S ) < {device-name}-OAD-DELAY * 1.6667 THEN STOP {device-name}-ERW-DEFROST-MODE , END
A = SWITCH( A , {device-name}-ERW-EA-DAT , {device-name}-ERW-DEFROST-SP + 2 , {device-name}-ERW-DEFROST-SP - 2 )
IF A THEN START {device-name}-ERW-DEFROST-MODE
IF NOT A AND TIME-ON( {device-name}-ERW-DEFROST-MODE ) > {device-name}-ERW-DEFROST-MIN-RT * 1.6667 THEN STOP {device-name}-ERW-DEFROST-MODE
