REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Occupancy-Based DCV OA Damper Minimum
REM ======================================================================

REM ***** Zero OA minimum until fan running past delay *****
IF NOT {device-name}-SF-S THEN {device-name}-ACT-OAD-MIN-POS = 0 , END

REM ***** Set OA minimum based on occupancy *****
IF {device-name}-OCC-MODE < 3 THEN A = {device-name}-OAD-MIN-POS ELSE A = 0

REM ***** Apply after OA damper delay *****
IF TIME-ON( {device-name}-SF-S ) > {device-name}-OAD-DELAY * 1.6667 THEN {device-name}-ACT-OAD-MIN-POS = A ELSE {device-name}-ACT-OAD-MIN-POS = 0
