REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Economizer Dry Bulb Enable/Disable
REM ======================================================================

REM ***** Lockout in heating mode or initialization *****
IF {device-name}-HVAC-MODE > 2 THEN STOP {device-name}-ECON-MODE , END

REM ***** Check safeties *****
A = MAX( {device-name}-LTC , {device-name}-SA-HPS )
IF A THEN STOP {device-name}-ECON-MODE , END

REM ***** Disable during OSH *****
IF {device-name}-OSH-MODE THEN STOP {device-name}-ECON-MODE , END

REM ***** Check dry bulb high limit *****
B = SWITCH( B , {device-name}-NET-OAT , {device-name}-ECON-HI-DB-SP - 2 , {device-name}-ECON-HI-DB-SP )
IF B THEN STOP {device-name}-ECON-MODE , END

REM ***** Disable during freeze protection *****
IF {device-name}-FRZ-PRTC-MODE THEN START C ELSE STOP C
IF C THEN STOP {device-name}-ECON-MODE , END

REM ***** Delay after fan start *****
IF TIME-ON( {device-name}-SF-S ) < {device-name}-OAD-DELAY * 1.66667 THEN START D ELSE STOP D
IF D THEN STOP {device-name}-ECON-MODE , END

REM ***** Enable economizer when OAT below lockout *****
START {device-name}-ECON-MODE
