REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — 100% Outside Air (DOAS/MAU)
REM ======================================================================

REM ***** OA damper always 100% when fan running *****
IF {device-name}-SF-S THEN {device-name}-ACT-OAD-MIN-POS = 100 ELSE {device-name}-ACT-OAD-MIN-POS = 0
