REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Fixed Minimum OA Damper Position
REM ======================================================================

REM ***** Zero OA minimum until fan running past delay *****
IF NOT {device-name}-SF-S THEN {device-name}-ACT-OAD-MIN-POS = 0 , END

REM ***** Apply fixed minimum after delay *****
IF TIME-ON( {device-name}-SF-S ) > {device-name}-OAD-DELAY * 1.6667 THEN {device-name}-ACT-OAD-MIN-POS = {device-name}-OAD-MIN-POS ELSE {device-name}-ACT-OAD-MIN-POS = 0
