REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Duct Static Pressure Setpoint Reset
REM ======================================================================

REM ***** Limit initial DSP setpoint *****
{device-name}-INITIAL-DSP-SP = LIMIT( {device-name}-INITIAL-DSP-SP , {device-name}-DSP-MIN-SP , {device-name}-DSP-MAX-SP )

REM ***** Reset DSP SP to initial when fan starts *****
IF NOT {device-name}-SF THEN {device-name}-ACT-DSP-SP = 0 , END
IF+ {device-name}-SF-S THEN {device-name}-ACT-DSP-SP = {device-name}-INITIAL-DSP-SP , END

REM ***** Sample zone damper positions at reset interval *****
IF INTERVAL( {device-name}-DSP-RESET-INTRVL * 1.66667 ) THEN GOTO 100 ELSE GOTO 150

REM ***** Reset DSP SP based on zone damper positions *****
A = SWITCH( A , {device-name}-ZONE-DMP-POS , {device-name}-ZONE-DMP-INC-SP - 0.5 , {device-name}-ZONE-DMP-INC-SP )
B = SWITCH( B , {device-name}-ZONE-DMP-POS , {device-name}-ZONE-DMP-DEC-SP + 0.5 , {device-name}-ZONE-DMP-DEC-SP )
IF A THEN {device-name}-ACT-DSP-SP = {device-name}-ACT-DSP-SP + {device-name}-DSP-SP-INCR
IF B THEN {device-name}-ACT-DSP-SP = {device-name}-ACT-DSP-SP - {device-name}-DSP-SP-INCR
{device-name}-ACT-DSP-SP = LIMIT( {device-name}-ACT-DSP-SP , {device-name}-DSP-MIN-SP , {device-name}-DSP-MAX-SP )
