REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Single Zone VAV Fan Speed Control
REM  Zone temp cascade resets SAT SP, fan speed from SAT PID loop
REM  Per ASHRAE Guideline 36 Section 5.18
REM ======================================================================

REM ***** Fan off — zero speed *****
IF NOT {device-name}-SF-S THEN {device-name}-SF-VFD-SPD = 0 , END

REM ***** Zone temp cascade — reset SAT setpoint from zone temp error *****
REM Cooling: zone temp above cooling SP → lower SAT SP (more cooling)
REM Heating: zone temp below heating SP → raise SAT SP (less cooling / more heat)
A = {device-name}-ZNT - {device-name}-ZNT-CLG-SP
B = {device-name}-ZNT-HTG-SP - {device-name}-ZNT
IF A > 0 THEN {device-name}-ACT-SAT-SP = {device-name}-ACT-SAT-SP - {device-name}-SAT-SP-INCR
IF B > 0 THEN {device-name}-ACT-SAT-SP = {device-name}-ACT-SAT-SP + {device-name}-SAT-SP-INCR
{device-name}-ACT-SAT-SP = LIMIT( {device-name}-ACT-SAT-SP , {device-name}-MIN-CLG-SAT-RST , {device-name}-MAX-HTG-SAT-RST )

REM ***** Heating mode — reduced fan speed *****
IF {device-name}-HVAC-MODE = 4 THEN {device-name}-SF-VFD-SPD = {device-name}-SZ-FAN-HTG-SPD , END

REM ***** Cooling/vent mode — fan speed from SAT PID loop output *****
{device-name}-SF-VFD-SPD = SLIDE( {device-name}-SZ-FAN-LOOP , 0 , 100 , {device-name}-SZ-FAN-MIN-SPD , {device-name}-SZ-FAN-MAX-SPD )
