REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Supply Air Temperature Setpoint Reset
REM ======================================================================

REM ***** Limit initial/OSH/OSC supply air temp setpoints *****
{device-name}-OSH-SAT-SP = LIMIT( {device-name}-OSH-SAT-SP , {device-name}-OSC-SAT-SP + 10 , 90 )
{device-name}-OSC-SAT-SP = LIMIT( {device-name}-OSC-SAT-SP , 55 , {device-name}-OSH-SAT-SP - 10 )
{device-name}-HEAT-INITIAL-SAT-SP = LIMIT( {device-name}-HEAT-INITIAL-SAT-SP , {device-name}-COOL-INITIAL-SAT-SP + 4 , {device-name}-OSH-SAT-SP )
{device-name}-COOL-INITIAL-SAT-SP = LIMIT( {device-name}-COOL-INITIAL-SAT-SP , {device-name}-OSC-SAT-SP , {device-name}-HEAT-INITIAL-SAT-SP - 4 )

REM ***** Set initial SAT SP based on HVAC mode *****
IF {device-name}-HVAC-MODE = 2 THEN {device-name}-INITIAL-SAT-SP = {device-name}-COOL-INITIAL-SAT-SP , GOTO 120
IF {device-name}-HVAC-MODE = 4 THEN {device-name}-INITIAL-SAT-SP = {device-name}-HEAT-INITIAL-SAT-SP ELSE {device-name}-INITIAL-SAT-SP = ( {device-name}-HEAT-INITIAL-SAT-SP - {device-name}-COOL-INITIAL-SAT-SP ) / 2 + {device-name}-COOL-INITIAL-SAT-SP

REM ***** Reset to initial on fan start *****
IF+ {device-name}-SF-S THEN {device-name}-ACT-SAT-SP = {device-name}-INITIAL-SAT-SP , END

REM ***** Reset to initial on occupancy mode change *****
IF+ {device-name}-OCC-MODE < 4 THEN {device-name}-ACT-SAT-SP = {device-name}-INITIAL-SAT-SP , GOTO 310
IF {device-name}-OCC-MODE = 5 OR {device-name}-OCC-MODE = 7 THEN {device-name}-ACT-SAT-SP = {device-name}-OSH-SAT-SP , GOTO 310
IF {device-name}-OCC-MODE = 6 OR {device-name}-OCC-MODE = 8 THEN {device-name}-ACT-SAT-SP = {device-name}-OSC-SAT-SP , GOTO 310
IF {device-name}-OSH-MODE THEN {device-name}-ACT-SAT-SP = {device-name}-OSH-SAT-SP , GOTO 310
IF {device-name}-OSC-MODE THEN {device-name}-ACT-SAT-SP = {device-name}-OSC-SAT-SP , GOTO 310

REM ***** Sample cooling demand at reset interval *****
IF INTERVAL( {device-name}-SAT-RESET-INTRVL * 1.66667 ) THEN GOTO 250 ELSE GOTO 300

REM ***** Reset SAT SP based on cooling demand *****
B = SWITCH( B , {device-name}-CLG-DMD , {device-name}-CLG-DMD-INC-SP + 0.25 , {device-name}-CLG-DMD-INC-SP )
C = SWITCH( C , {device-name}-CLG-DMD , {device-name}-CLG-DMD-DEC-SP - 0.25 , {device-name}-CLG-DMD-DEC-SP )
IF B THEN {device-name}-ACT-SAT-SP = {device-name}-ACT-SAT-SP + {device-name}-SAT-SP-INCR
IF C THEN {device-name}-ACT-SAT-SP = {device-name}-ACT-SAT-SP - {device-name}-SAT-SP-INCR
{device-name}-ACT-SAT-SP = LIMIT( {device-name}-ACT-SAT-SP , 55 , 80 )

REM ***** Limit between OSC and OSH setpoints *****
{device-name}-ACT-SAT-SP = LIMIT( {device-name}-ACT-SAT-SP , {device-name}-OSC-SAT-SP , {device-name}-OSH-SAT-SP )

REM ***** Set MAT setpoint from SAT SP *****
G = SLIDE( {device-name}-NET-OAT , 25 , 60 , 55 , 50 )
{device-name}-ACT-MAT-SP = {device-name}-ACT-SAT-SP - {device-name}-MAT-SP-OFFSET
{device-name}-ACT-MAT-SP = LIMIT( {device-name}-ACT-MAT-SP , G , {device-name}-ACT-SAT-SP )
