REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Economizer Differential Temperature Enable/Disable
REM ======================================================================

REM ***** Lockout in heating mode or initialization *****
IF {device-name}-HVAC-MODE > 2 THEN STOP {device-name}-ECON-MODE , END

REM ***** Check safeties *****
A = MAX( {device-name}-LTC , {device-name}-SA-HPS )
IF A THEN STOP {device-name}-ECON-MODE , END

REM ***** Disable during OSH *****
IF {device-name}-OSH-MODE THEN STOP {device-name}-ECON-MODE , END

REM ***** Disable during freeze protection *****
IF {device-name}-FRZ-PRTC-MODE THEN START B ELSE STOP B
IF B THEN STOP {device-name}-ECON-MODE , END

REM ***** Delay after fan start *****
IF TIME-ON( {device-name}-SF-S ) < {device-name}-OAD-DELAY * 1.66667 THEN START C ELSE STOP C
IF C THEN STOP {device-name}-ECON-MODE , END

REM ***** Enable when OAT < RAT (differential comparison) *****
{device-name}-ECON-MODE = SWITCH( {device-name}-ECON-MODE , {device-name}-NET-OAT , {device-name}-RAT , {device-name}-RAT - 2 )
