REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Economizer Enthalpy Enable/Disable
REM ======================================================================

REM ***** Lockout economizer in heating mode or initialization *****
IF {device-name}-HVAC-MODE > 2 THEN STOP {device-name}-ECON-MODE , END

REM ***** Check safeties *****
A = MAX( {device-name}-LTC , {device-name}-SA-HPS )
IF A THEN STOP {device-name}-ECON-MODE , END

REM ***** Disable during optimum start heat *****
IF {device-name}-OSH-MODE THEN STOP {device-name}-ECON-MODE , END

REM ***** Check dry bulb high limit *****
B = SWITCH( B , {device-name}-NET-OAT , {device-name}-ECON-HI-DB-SP - 2 , {device-name}-ECON-HI-DB-SP )
IF B THEN STOP {device-name}-ECON-MODE , END

REM ***** Disable during freeze protection *****
IF {device-name}-FRZ-PRTC-MODE THEN START C ELSE STOP C
IF C THEN STOP {device-name}-ECON-MODE , END

REM ***** Check enthalpy high limit *****
D = SWITCH( D , {device-name}-NET-OA-ERH , {device-name}-ECON-HI-ERH-SP - 2 , {device-name}-ECON-HI-ERH-SP )
IF D THEN STOP {device-name}-ECON-MODE , END

REM ***** Delay after fan start *****
IF TIME-ON( {device-name}-SF-S ) < {device-name}-OAD-DELAY * 1.66667 THEN START E ELSE STOP E
IF E THEN STOP {device-name}-ECON-MODE , END

REM ***** Enable when OA enthalpy < RA enthalpy *****
{device-name}-ECON-MODE = SWITCH( {device-name}-ECON-MODE , {device-name}-NET-OA-ERH , {device-name}-RA-ERH , {device-name}-RA-ERH - 2 )
