REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — DCV CO2-Based OA Damper Minimum Position
REM ======================================================================

REM ***** Zero OA minimum until fan running past delay *****
IF NOT {device-name}-SF-S THEN {device-name}-ACT-OAD-MIN-POS = 0 , END

REM ***** Slide OA damper min position based on CO2 level *****
A = SLIDE( {device-name}-RA-CO2 , {device-name}-CO2-MIN-SP , {device-name}-CO2-MAX-SP , {device-name}-MIN-OAD-DCV-POS , {device-name}-MAX-OAD-DCV-POS )
A = LIMIT( A , {device-name}-MIN-OAD-DCV-POS , {device-name}-MAX-OAD-DCV-POS )

REM ***** Apply after OA damper delay *****
IF TIME-ON( {device-name}-SF-S ) > {device-name}-OAD-DELAY * 1.6667 THEN {device-name}-ACT-OAD-MIN-POS = A ELSE {device-name}-ACT-OAD-MIN-POS = 0
