REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Low Temperature Cutout
REM ======================================================================

IF {device-name}-LTC THEN STOP {device-name}-LTC-SD-CMD
IF TIME-OFF( {device-name}-LTC ) > 0:00:20 THEN START {device-name}-LTC-SD-CMD
