REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Supply Air High Static Pressure Cutout
REM ======================================================================

IF {device-name}-SA-HPS THEN STOP {device-name}-SA-HPS-SD-CMD ELSE START {device-name}-SA-HPS-SD-CMD
IF TIME-OFF( {device-name}-SA-HPS ) > 0:00:20 THEN START {device-name}-SA-HPS-SD-CMD
