REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Gas Heater 4-Stage Loop-Threshold Control
REM ======================================================================

REM ***** Disable on safety *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-GAS-VLV-1 , STOP {device-name}-GAS-VLV-2 , STOP {device-name}-GAS-VLV-3 , STOP {device-name}-GAS-VLV-4 , END

REM ***** Disable when fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-GAS-VLV-1 , STOP {device-name}-GAS-VLV-2 , STOP {device-name}-GAS-VLV-3 , STOP {device-name}-GAS-VLV-4 , END

REM ***** Check gas pressure safety *****
IF NOT {device-name}-GAS-PRSR THEN STOP {device-name}-GAS-VLV-1 , STOP {device-name}-GAS-VLV-2 , STOP {device-name}-GAS-VLV-3 , STOP {device-name}-GAS-VLV-4 , START {device-name}-GAS-FAIL , END
STOP {device-name}-GAS-FAIL

REM ***** Heating lockout *****
IF {device-name}-HTG-LOCKOUT THEN STOP {device-name}-GAS-VLV-1 , STOP {device-name}-GAS-VLV-2 , STOP {device-name}-GAS-VLV-3 , STOP {device-name}-GAS-VLV-4 , END

REM ***** LTC override — enable stage 1 *****
IF {device-name}-LTC THEN START {device-name}-GAS-VLV-1 , END

REM ***** Heating mode gate *****
IF NOT ( {device-name}-HVAC-MODE = 4 AND {device-name}-SF-S ) THEN STOP {device-name}-GAS-VLV-1 , STOP {device-name}-GAS-VLV-2 , STOP {device-name}-GAS-VLV-3 , STOP {device-name}-GAS-VLV-4 , END

REM ***** Stage 1 — enable when loop output > 25% *****
IF loop7 > 25 THEN START {device-name}-GAS-VLV-1
IF loop7 < 18 THEN STOP {device-name}-GAS-VLV-1 , STOP {device-name}-GAS-VLV-2 , STOP {device-name}-GAS-VLV-3 , STOP {device-name}-GAS-VLV-4

REM ***** Stage 2 — enable when loop output > Stage 2 SP *****
IF loop7 > {device-name}-GAS-STG2-SP AND {device-name}-GAS-VLV-1 THEN START {device-name}-GAS-VLV-2
IF loop7 < ( {device-name}-GAS-STG2-SP - 7 ) THEN STOP {device-name}-GAS-VLV-2 , STOP {device-name}-GAS-VLV-3 , STOP {device-name}-GAS-VLV-4

REM ***** Stage 3 — enable when loop output > Stage 3 SP *****
IF loop7 > {device-name}-GAS-STG3-SP AND {device-name}-GAS-VLV-2 THEN START {device-name}-GAS-VLV-3
IF loop7 < ( {device-name}-GAS-STG3-SP - 7 ) THEN STOP {device-name}-GAS-VLV-3 , STOP {device-name}-GAS-VLV-4

REM ***** Stage 4 — enable when loop output > Stage 4 SP *****
IF loop7 > {device-name}-GAS-STG4-SP AND {device-name}-GAS-VLV-3 THEN START {device-name}-GAS-VLV-4
IF loop7 < ( {device-name}-GAS-STG4-SP - 7 ) THEN STOP {device-name}-GAS-VLV-4
