10 REM ======================================================================
20 REM  Generated by SBS Composition Engine v2
30 REM  {device-name} — Return Air High Static Pressure Cutout
40 REM ======================================================================
50 IF {device-name}-RA-HPS THEN STOP {device-name}-RA-HPS-SD-CMD ELSE START {device-name}-RA-HPS-SD-CMD
60 IF TIME-OFF( {device-name}-RA-HPS ) > 0:00:20 THEN START {device-name}-RA-HPS-SD-CMD
