REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Relief Fan Constant Speed Control
REM ======================================================================

REM ***** Safety shutdown — stop fan *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-RLF , END

REM ***** Stop when supply fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-RLF , END

REM ***** Start fan when supply fan running *****
IF {device-name}-SF-S THEN START {device-name}-RLF ELSE STOP {device-name}-RLF

REM ***** Failure detection *****
IF TIME-ON( {device-name}-RLF ) > 0:00:30 AND NOT {device-name}-RLF-S THEN START {device-name}-RLF-FAIL
IF TIME-ON( {device-name}-RLF-S ) > 0:01:00 THEN STOP {device-name}-RLF-FAIL
