REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Supply Fan VFD Control
REM ======================================================================

REM ***** Set internal variables *****
A = {device-name}-SF-VFD-SPD
B = SLIDE( loop1 , 0 , 100 , {device-name}-SF-MIN-SPEED , {device-name}-SF-MAX-SPEED )

REM ***** Stop fan on safety shutdown *****
IF {device-name}-SAFETY-SD-ALARM THEN {device-name}-SF-VFD-SPD = 0 , STOP {device-name}-SF , C = 0 , END

REM ***** Stop fan during initialization *****
IF {device-name}-HVAC-MODE = 5 THEN {device-name}-SF-VFD-SPD = 0 , STOP {device-name}-SF , C = 0 , END

REM ***** Start/stop based on occupancy mode *****
REM 1=Occupied / 2=Bypass / 3=Standby / 4=Unoccupied / 5-8=Extended
IF {device-name}-OCC-MODE < 3 THEN START C ELSE STOP C
IF {device-name}-OCC-MODE > 4 THEN START D ELSE STOP D
IF C OR D THEN START {device-name}-SF ELSE STOP {device-name}-SF

REM ***** Zero speed when fan off *****
IF NOT {device-name}-SF THEN {device-name}-SF-VFD-SPD = 0 , E = 0 , GOTO 210

REM ***** Ramp speed to setpoint *****
IF {device-name}-SF THEN E = RAMP( ABS( A - B ) > 1 , A , B , {device-name}-SF-SPEED-RAMP * 1.66667 ) ELSE E = 0
IF ABS( A - B ) < 1 THEN E = B
{device-name}-SF-VFD-SPD = E

REM ***** Fan failure detection *****
IF TIME-ON( {device-name}-SF ) > 0:00:30 AND NOT {device-name}-SF-S THEN START {device-name}-SF-FAIL
IF TIME-ON( {device-name}-SF-S ) > 0:01:00 THEN STOP {device-name}-SF-FAIL
