REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Electric Heat 3-Stage
REM ======================================================================

REM ***** Disable on safety *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-ELEC-HTR-1 , STOP {device-name}-ELEC-HTR-2 , STOP {device-name}-ELEC-HTR-3 , END

REM ***** Disable when fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-ELEC-HTR-1 , STOP {device-name}-ELEC-HTR-2 , STOP {device-name}-ELEC-HTR-3 , END

REM ***** Heating lockout *****
IF {device-name}-HTG-LOCKOUT THEN STOP {device-name}-ELEC-HTR-1 , STOP {device-name}-ELEC-HTR-2 , STOP {device-name}-ELEC-HTR-3 , END

REM ***** Stage 1 — enable in heating mode *****
IF {device-name}-HVAC-MODE = 4 AND {device-name}-SF-S THEN START {device-name}-ELEC-HTR-1 ELSE STOP {device-name}-ELEC-HTR-1 , STOP {device-name}-ELEC-HTR-2 , STOP {device-name}-ELEC-HTR-3 , END

REM ***** Stage 2 — enable when loop output > 33% *****
IF loop7 > 33 AND {device-name}-ELEC-HTR-1 THEN START {device-name}-ELEC-HTR-2
IF loop7 < 25 THEN STOP {device-name}-ELEC-HTR-2 , STOP {device-name}-ELEC-HTR-3

REM ***** Stage 3 — enable when loop output > 66% *****
IF loop7 > 66 AND {device-name}-ELEC-HTR-2 THEN START {device-name}-ELEC-HTR-3
IF loop7 < 55 THEN STOP {device-name}-ELEC-HTR-3
