REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Exhaust Air High Static Pressure Cutout
REM ======================================================================

IF {device-name}-EA-HPS THEN STOP {device-name}-EA-HPS-SD-CMD ELSE START {device-name}-EA-HPS-SD-CMD
IF TIME-OFF( {device-name}-EA-HPS ) > 0:00:20 THEN START {device-name}-EA-HPS-SD-CMD
