REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Gas Heater On/Off Control
REM ======================================================================

REM ***** Disable on safety *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-GAS-VLV , END

REM ***** Disable when fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-GAS-VLV , END

REM ***** Check gas pressure safety *****
IF NOT {device-name}-GAS-PRSR THEN STOP {device-name}-GAS-VLV , START {device-name}-GAS-FAIL , END
STOP {device-name}-GAS-FAIL

REM ***** Heating lockout *****
IF {device-name}-HTG-LOCKOUT THEN STOP {device-name}-GAS-VLV , END

REM ***** LTC override — enable heater *****
IF {device-name}-LTC THEN START {device-name}-GAS-VLV , END

REM ***** Enable in heating mode *****
IF {device-name}-HVAC-MODE = 4 AND {device-name}-SF-S THEN START {device-name}-GAS-VLV ELSE STOP {device-name}-GAS-VLV
