REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Dual Duct Hot Deck HW Valve Control
REM ======================================================================

REM ***** Set internal variables *****
A = {device-name}-HW-VLV
B = loop7

REM ***** LTC override — valve full open *****
IF {device-name}-LTC THEN {device-name}-HW-VLV = 100 , END

REM ***** SA HPS override — valve closed *****
IF {device-name}-SA-HPS THEN {device-name}-HW-VLV = 0 , END

REM ***** Freeze protection — valve from freeze loop *****
IF NOT {device-name}-SF-S AND {device-name}-FRZ-PRTC-MODE THEN {device-name}-HW-VLV = loop9 , END

REM ***** Heating lockout — valve closed *****
IF {device-name}-HTG-LOCKOUT THEN {device-name}-HW-VLV = 0 , END

REM ***** Defrost override — valve full open *****
IF+ {device-name}-ERW-DEFROST-MODE THEN {device-name}-HW-VLV = 100 , END

REM ***** Normal modulation from HW valve loop *****
IF {device-name}-SF-S THEN {device-name}-HW-VLV = RAMP( ABS( A - B ) > 1 , A , B , {device-name}-HTG-RAMP * 1.66667 ) ELSE {device-name}-HW-VLV = 0 , GOTO 190
IF ABS( A - B ) < 1 THEN {device-name}-HW-VLV = B , END

REM ***** Fan off — freeze protection or close *****
IF NOT {device-name}-SF-S AND {device-name}-FRZ-PRTC-MODE THEN {device-name}-HW-VLV = loop9 ELSE {device-name}-HW-VLV = 0
