REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Relief Fan VFD Control
REM ======================================================================

REM ***** Safety shutdown — stop fan *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-RLF , {device-name}-RLF-VFD-SPD = 0 , C = 0 , D = 0 , END

REM ***** Stop when supply fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-RLF , {device-name}-RLF-VFD-SPD = 0 , C = 0 , D = 0 , END

REM ***** Start/stop logic *****
IF {device-name}-SF-S THEN START {device-name}-RLF ELSE STOP {device-name}-RLF
IF TIME-ON( {device-name}-RLF ) > 0:01:30 THEN {device-name}-RLF-VFD-SPD = loop5 , GOTO 100 ELSE {device-name}-RLF-VFD-SPD = {device-name}-RLF-MIN-SPEED , GOTO 70

REM ***** Speed ramp *****
B = {device-name}-RLF-VFD-SPD
C = SLIDE( loop5 , 0 , 100 , {device-name}-RLF-MIN-SPEED , {device-name}-RLF-MAX-SPEED )
IF {device-name}-RLF-S THEN D = RAMP( ABS( B - C ) > 1 , B , C , {device-name}-RLF-SPEED-RAMP * 1.6667 ) ELSE D = 0 , END
IF ABS( B - C ) < 1 THEN D = C
{device-name}-RLF-VFD-SPD = D

REM ***** Failure detection *****
IF TIME-ON( {device-name}-RLF ) > 0:00:30 AND NOT {device-name}-RLF-S THEN START {device-name}-RLF-FAIL
IF TIME-ON( {device-name}-RLF-S ) > 0:01:00 THEN STOP {device-name}-RLF-FAIL
