REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — SCR Electric Heat Modulating Control
REM ======================================================================

REM ***** Set internal variables *****
A = {device-name}-ELEC-SCR
B = loop7

REM ***** Disable on safety *****
IF {device-name}-SAFETY-SD-ALARM THEN {device-name}-ELEC-SCR = 0 , END

REM ***** Disable when fan off *****
IF NOT {device-name}-SF-S THEN {device-name}-ELEC-SCR = 0 , END

REM ***** LTC override — output full *****
IF {device-name}-LTC THEN {device-name}-ELEC-SCR = 100 , END

REM ***** Heating lockout *****
IF {device-name}-HTG-LOCKOUT THEN {device-name}-ELEC-SCR = 0 , END

REM ***** Normal modulation from heating loop *****
IF {device-name}-SF-S THEN {device-name}-ELEC-SCR = RAMP( ABS( A - B ) > 1 , A , B , {device-name}-HTG-RAMP * 1.66667 ) ELSE {device-name}-ELEC-SCR = 0 , END
IF ABS( A - B ) < 1 THEN {device-name}-ELEC-SCR = B
