REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Return Fan Constant Speed Control
REM ======================================================================

REM ***** Safety shutdown — stop fan *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-RF , END

REM ***** Stop when supply fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-RF , END

REM ***** Start fan when supply fan running *****
IF {device-name}-SF-S THEN START {device-name}-RF ELSE STOP {device-name}-RF

REM ***** Failure detection *****
IF TIME-ON( {device-name}-RF ) > 0:00:30 AND NOT {device-name}-RF-S THEN START {device-name}-RF-FAIL
IF TIME-ON( {device-name}-RF-S ) > 0:01:00 THEN STOP {device-name}-RF-FAIL
