REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Electric Heat 2-Stage
REM ======================================================================

REM ***** Disable on safety *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-ELEC-HTR-1 , STOP {device-name}-ELEC-HTR-2 , END

REM ***** Disable when fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-ELEC-HTR-1 , STOP {device-name}-ELEC-HTR-2 , END

REM ***** Heating lockout *****
IF {device-name}-HTG-LOCKOUT THEN STOP {device-name}-ELEC-HTR-1 , STOP {device-name}-ELEC-HTR-2 , END

REM ***** Stage 1 — enable in heating mode *****
IF {device-name}-HVAC-MODE = 4 AND {device-name}-SF-S THEN START {device-name}-ELEC-HTR-1 ELSE STOP {device-name}-ELEC-HTR-1 , STOP {device-name}-ELEC-HTR-2 , END

REM ***** Stage 2 — enable when SAT drops below SP by offset *****
IF {device-name}-SAT < {device-name}-ACT-SAT-SP - {device-name}-ELEC-STG2-SP THEN START {device-name}-ELEC-HTR-2
IF {device-name}-SAT > {device-name}-ACT-SAT-SP - 2 THEN STOP {device-name}-ELEC-HTR-2
