REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Outside Air / Return Air Damper Control
REM ======================================================================

REM ***** Calculate OA airflow *****
{device-name}-OA-FLOW-ACT = {device-name}-OA-AREA * {device-name}-OA-VEL * {device-name}-OA-K-FACTOR

REM ***** Set internal variables *****
A = {device-name}-OAD
B = {device-name}-ACT-OAD-MIN-POS
IF {device-name}-ECON-MODE THEN C = {device-name}-MAT-LOOP3 ELSE C = 0
IF {device-name}-SF-S THEN H = {device-name}-OAD-MIN-POS ELSE H = 0
D = {device-name}-MAT-LL-LOOP2
E = MAX( B , C , H )
F = MIN( D , E )

REM ***** Set return air damper — inverse of OA damper *****
IF {device-name}-SF-S THEN {device-name}-RAD = 100 - {device-name}-OAD ELSE {device-name}-RAD = 0
{device-name}-RAD = LIMIT( {device-name}-RAD , 0 , 100 )

REM ***** Close dampers on safety shutdown *****
IF {device-name}-SAFETY-SD-ALARM THEN {device-name}-OAD = 0 , {device-name}-RAD = 100 , F = 0 , G = 0 , END

REM ***** Hold closed during damper delay *****
IF TIME-ON( {device-name}-SF-S ) < {device-name}-OAD-DELAY * 1.6667 THEN {device-name}-OAD = 0 , F = 0 , G = 0 , END

REM ***** Ramp damper to target *****
IF {device-name}-SF-S THEN G = RAMP( ABS( A - F ) > 1 , A , F , {device-name}-DAMP-RAMP * 1.66667 )
IF ABS( A - F ) < 1 THEN G = F
{device-name}-OAD = G
