REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Supply Fan Constant Speed Control
REM ======================================================================

REM ***** Stop fan on safety shutdown *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-SF , END

REM ***** Stop fan during initialization *****
IF {device-name}-HVAC-MODE = 5 THEN STOP {device-name}-SF , END

REM ***** Start/stop based on occupancy mode *****
REM 1=Occupied / 2=Bypass / 3=Standby / 4=Unoccupied / 5-8=Extended
IF {device-name}-OCC-MODE < 3 THEN START A ELSE STOP A
IF {device-name}-OCC-MODE > 4 THEN START B ELSE STOP B
IF A OR B THEN START {device-name}-SF ELSE STOP {device-name}-SF

REM ***** Fan failure detection *****
IF TIME-ON( {device-name}-SF ) > 0:00:30 AND NOT {device-name}-SF-S THEN START {device-name}-SF-FAIL
IF TIME-ON( {device-name}-SF-S ) > 0:01:00 THEN STOP {device-name}-SF-FAIL
