REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Dual Duct Hot Deck Electric Heat
REM ======================================================================

REM ***** Disable on safety *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-ELEC-HTR-1 , END

REM ***** Disable when fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-ELEC-HTR-1 , END

REM ***** Heating lockout *****
IF {device-name}-HTG-LOCKOUT THEN STOP {device-name}-ELEC-HTR-1 , END

REM ***** Enable in heating mode *****
IF {device-name}-HVAC-MODE = 4 AND {device-name}-SF-S THEN START {device-name}-ELEC-HTR-1 ELSE STOP {device-name}-ELEC-HTR-1
