REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Exhaust Fan Constant Speed Control
REM ======================================================================

REM ***** Safety shutdown — stop fan *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-EF , {device-name}-EAD = 0 , END

REM ***** Stop when supply fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-EF , {device-name}-EAD = 0 , GOTO 80

REM ***** Open EA damper when SF running *****
IF {device-name}-SF-S THEN {device-name}-EAD = 100

REM ***** Wait for EA damper end switch *****
IF NOT {device-name}-EA-DMP-ES THEN STOP {device-name}-EF , GOTO 80

REM ***** Start fan when damper open *****
IF {device-name}-SF-S AND {device-name}-EA-DMP-ES THEN START {device-name}-EF ELSE STOP {device-name}-EF

REM ***** Failure detection *****
IF TIME-ON( {device-name}-EF ) > 0:00:30 AND NOT {device-name}-EF-S THEN START {device-name}-EF-FAIL
IF TIME-ON( {device-name}-EF-S ) > 0:01:00 THEN STOP {device-name}-EF-FAIL
