REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Return Fan VFD Control
REM ======================================================================

REM ***** Safety shutdown — stop fan *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-RF , {device-name}-RF-VFD-SPD = 0 , C = 0 , D = 0 , END

REM ***** Stop when supply fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-RF , {device-name}-RF-VFD-SPD = 0 , C = 0 , D = 0 , END

REM ***** Start/stop logic *****
IF {device-name}-SF-S THEN START {device-name}-RF ELSE STOP {device-name}-RF
IF TIME-ON( {device-name}-RF ) > 0:01:30 THEN {device-name}-RF-VFD-SPD = loop5 , GOTO 100 ELSE {device-name}-RF-VFD-SPD = {device-name}-RF-MIN-SPEED , GOTO 70

REM ***** Speed ramp *****
B = {device-name}-RF-VFD-SPD
C = SLIDE( loop5 , 0 , 100 , {device-name}-RF-MIN-SPEED , {device-name}-RF-MAX-SPEED )
IF {device-name}-RF-S THEN D = RAMP( ABS( B - C ) > 1 , B , C , {device-name}-RF-SPEED-RAMP * 1.6667 ) ELSE D = 0 , END
IF ABS( B - C ) < 1 THEN D = C
{device-name}-RF-VFD-SPD = D

REM ***** Failure detection *****
IF TIME-ON( {device-name}-RF ) > 0:00:30 AND NOT {device-name}-RF-S THEN START {device-name}-RF-FAIL
IF TIME-ON( {device-name}-RF-S ) > 0:01:00 THEN STOP {device-name}-RF-FAIL
