REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Exhaust Fan VFD Control
REM ======================================================================

REM ***** Calculate exhaust airflow setpoint *****
IF {device-name}-SF-S THEN {device-name}-EA-FLOW-SP = {device-name}-OA-FLOW-ACT * {device-name}-EA-FLOW-%OA ELSE {device-name}-EA-FLOW-SP = 0

REM ***** Safety shutdown — stop fan *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-EF , {device-name}-EF-VFD-SPD = 0 , STOP A , C = 0 , D = 0 , GOTO 110

REM ***** Stop when supply fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-EF , {device-name}-EF-VFD-SPD = 0 , {device-name}-EAD = 0 , STOP A , C = 0 , D = 0 , GOTO 110

REM ***** Open EA damper when SF running *****
IF {device-name}-SF-S THEN {device-name}-EAD = 100

REM ***** Wait for EA damper end switch *****
IF NOT {device-name}-EA-DMP-ES THEN STOP {device-name}-EF , {device-name}-EF-VFD-SPD = 0 , C = 0 , D = 0 , GOTO 110

REM ***** Start/stop logic *****
IF {device-name}-SF-S AND {device-name}-EA-DMP-ES THEN START {device-name}-EF ELSE STOP {device-name}-EF
IF TIME-ON( {device-name}-EF ) > 0:01:30 THEN {device-name}-EF-VFD-SPD = {device-name}-EA-FLOW-LOOP5 , GOTO 150 ELSE {device-name}-EF-VFD-SPD = {device-name}-EA-MIN-SPEED , GOTO 110

REM ***** Speed ramp *****
B = {device-name}-EF-VFD-SPD
C = SLIDE( {device-name}-EA-FLOW-LOOP5 , 0 , 100 , {device-name}-EA-MIN-SPEED , {device-name}-EA-MAX-SPEED )
IF {device-name}-EF-S THEN D = RAMP( ABS( B - C ) > 1 , B , C , {device-name}-EF-SPEED-RAMP * 1.6667 ) ELSE D = 0 , GOTO 110
IF ABS( B - C ) < 1 THEN D = C
{device-name}-EF-VFD-SPD = D

REM ***** Failure detection *****
IF TIME-ON( {device-name}-EF ) > 0:00:30 AND NOT {device-name}-EF-S THEN START {device-name}-EF-FAIL
IF TIME-ON( {device-name}-EF-S ) > 0:01:00 THEN STOP {device-name}-EF-FAIL
