REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — CHW Coil Pump Control
REM  Standard pattern: valve open → pump on (no freeze logic)
REM ======================================================================

REM ***** Pump on when CHW valve open *****
IF {device-name}-CHW-VLV > 0 THEN START {device-name}-CHW-PMP ELSE STOP {device-name}-CHW-PMP

REM ***** Failure detection — commanded on, no status after 30s *****
IF TIME-ON( {device-name}-CHW-PMP ) > 0:00:30 AND NOT {device-name}-CHW-PMP-STS THEN START {device-name}-CHW-PMP-FAIL
IF {device-name}-CHW-PMP-STS THEN STOP {device-name}-CHW-PMP-FAIL
