REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Electric Humidifier Control
REM ======================================================================

REM ***** Disable when unoccupied *****
IF- {device-name}-OCC-CMD THEN {device-name}-HUM = 0 , END

REM ***** Disable when fan off *****
IF NOT {device-name}-SF-S THEN {device-name}-HUM = 0 , END

REM ***** Check humidifier status *****
IF NOT {device-name}-HUM-STS THEN {device-name}-HUM = 0 , END

REM ***** Modulate humidifier to maintain humidity setpoint *****
IF {device-name}-RAH < {device-name}-HUM-SP - {device-name}-HUM-DB THEN {device-name}-HUM = SLIDE( {device-name}-RAH , {device-name}-HUM-SP - {device-name}-HUM-DB , {device-name}-HUM-SP , 100 , 0 )
IF {device-name}-RAH > {device-name}-HUM-SP THEN {device-name}-HUM = 0
