REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Glycol Preheat Valve Control
REM  Pump is a separate optional module (ph-hw-pump → PRG49-PH-PMP)
REM ======================================================================

REM ***** Set internal variables *****
A = {device-name}-PH-VLV
B = loop13

REM ***** Close valve when fan off and not in freeze protection *****
IF NOT {device-name}-SF-S AND NOT {device-name}-FRZ-PRTC-MODE THEN {device-name}-PH-VLV = 0 , GOTO 100

REM ***** Freeze protection — valve full open *****
IF NOT {device-name}-SF-S AND {device-name}-FRZ-PRTC-MODE THEN {device-name}-PH-VLV = 100 , GOTO 100

REM ***** Normal modulation *****
IF {device-name}-SF-S THEN {device-name}-PH-VLV = RAMP( ABS( A - B ) > 1 , A , B , 0.5 * 1.66667 ) ELSE {device-name}-PH-VLV = 0
IF ABS( A - B ) < 1 THEN {device-name}-PH-VLV = B
