REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Electric Preheat Control
REM ======================================================================

REM ***** Disable on safety *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-PH-HTR , END

REM ***** Freeze protection — enable heater *****
IF {device-name}-FRZ-PRTC-MODE THEN START {device-name}-PH-HTR , END

REM ***** Disable when fan off and no freeze *****
IF NOT {device-name}-SF-S AND NOT {device-name}-FRZ-PRTC-MODE THEN STOP {device-name}-PH-HTR , END

REM ***** Enable when preheat temp below setpoint *****
A = SWITCH( A , {device-name}-PH-T , {device-name}-PH-SP , {device-name}-PH-SP + 3 )
IF A AND {device-name}-SF-S THEN START {device-name}-PH-HTR ELSE STOP {device-name}-PH-HTR
