REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Dual Duct Cold Deck CHW Valve Control
REM ======================================================================

REM ***** Set internal variables *****
A = {device-name}-CHW-VLV
B = loop8

REM ***** LTC override — valve full open *****
IF {device-name}-LTC THEN {device-name}-CHW-VLV = 100 , END

REM ***** SA HPS override — valve closed *****
IF {device-name}-SA-HPS THEN {device-name}-CHW-VLV = 0 , END

REM ***** Cooling lockout — valve closed *****
IF {device-name}-CLG-LOCKOUT THEN {device-name}-CHW-VLV = 0 , END

REM ***** CHW not available — valve closed *****
IF NOT {device-name}-CHW-AVAIL THEN {device-name}-CHW-VLV = 0 , END

REM ***** Normal modulation from CHW valve loop *****
IF {device-name}-SF-S THEN {device-name}-CHW-VLV = RAMP( ABS( A - B ) > 1 , A , B , {device-name}-CLG-RAMP * 1.66667 ) ELSE {device-name}-CHW-VLV = 0 , END
IF ABS( A - B ) < 1 THEN {device-name}-CHW-VLV = B

REM ***** CHW system call — notify plant *****
IF NOT {device-name}-SF-S THEN STOP A , STOP B , STOP {device-name}-CHWS-CALL , END
A = SWITCH( A , {device-name}-CHW-VLV , 2 , 10 )
IF TIME-ON( A ) > 0:10:00 THEN START B
IF TIME-OFF( A ) > 0:20:00 THEN STOP B
IF {device-name}-SF-S AND A THEN START {device-name}-CHWS-CALL ELSE STOP {device-name}-CHWS-CALL
