REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Energy Recovery Wheel Control
REM  FIXED SPEED ONLY — start/stop + bypass dampers for capacity
REM ======================================================================

REM ***** ERW off when fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-ERW , GOTO 100

REM ***** Wait for OA damper delay before enabling *****
IF TIME-ON( {device-name}-SF-S ) > {device-name}-OAD-DELAY * 1.6667 THEN START A ELSE STOP A

REM ***** Enable during defrost *****
IF {device-name}-ERW-DEFROST-MODE AND A THEN START B ELSE STOP B

REM ***** Enable when NOT in economizer mode *****
IF NOT {device-name}-ECON-MODE AND A THEN START C ELSE STOP C

REM ***** Start ERW if defrost or non-economizer conditions met *****
IF B OR C THEN START {device-name}-ERW ELSE STOP {device-name}-ERW

REM ***** ERW failure detection *****
IF TIME-ON( {device-name}-ERW ) > 0:01:00 AND NOT {device-name}-ERW-STATUS THEN START {device-name}-ERW-FAIL
IF TIME-ON( {device-name}-ERW-STATUS ) > 0:01:30 THEN STOP {device-name}-ERW-FAIL
