REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Subcooling Dehumidification Control
REM ======================================================================

REM ***** Dehumidification by subcooling *****
REM Lower SAT setpoint when zone humidity exceeds dehumid setpoint

IF- {device-name}-OCC-CMD THEN STOP {device-name}-DEHUM-MODE , END

REM ***** Check if dehumidification needed *****
IF {device-name}-ZN-RH > {device-name}-DEHUM-SP + {device-name}-DEHUM-DB THEN START {device-name}-DEHUM-MODE
IF {device-name}-ZN-RH < {device-name}-DEHUM-SP THEN STOP {device-name}-DEHUM-MODE

REM ***** Override SAT setpoint when dehumidifying *****
IF {device-name}-DEHUM-MODE THEN {device-name}-ACT-SAT-SP = MIN( {device-name}-ACT-SAT-SP , {device-name}-DEHUM-SAT-SP )
