REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Preheat HW Valve + Pump Control
REM ======================================================================

REM ***** Set internal variables *****
A = {device-name}-PH-VLV
B = loop13

REM ***** Close valve when fan off and not in freeze protection *****
IF NOT {device-name}-SF-S AND NOT {device-name}-FRZ-PRTC-MODE THEN {device-name}-PH-VLV = 0 , GOTO 100

REM ***** Freeze protection — valve from freeze loop *****
IF NOT {device-name}-SF-S AND {device-name}-FRZ-PRTC-MODE THEN {device-name}-PH-VLV = 100 , GOTO 100

REM ***** Normal modulation *****
IF {device-name}-SF-S THEN {device-name}-PH-VLV = RAMP( ABS( A - B ) > 1 , A , B , 0.5 * 1.66667 ) ELSE {device-name}-PH-VLV = 0
IF ABS( A - B ) < 1 THEN {device-name}-PH-VLV = B

REM ***** Pump control — valve open OR freeze → pump on *****
IF {device-name}-PH-VLV > 0 THEN START C ELSE STOP C
D = SWITCH( D , {device-name}-NET-OAT , {device-name}-FRZ-PRTC-SP + 5 , {device-name}-FRZ-PRTC-SP )
IF C OR D THEN START {device-name}-PH-PMP ELSE STOP {device-name}-PH-PMP

REM ***** Pump failure *****
IF TIME-ON( {device-name}-PH-PMP ) > 0:00:30 AND NOT {device-name}-PH-PMP-FAIL THEN START {device-name}-PH-PMP-FAIL
