REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Heating Coil Face/Bypass Damper Control
REM ======================================================================
REM  0%   = full bypass (no air through heating coil)
REM  100% = full face   (all air through heating coil)
REM
REM  Behavior:
REM    Heating mode      → 100% face (full through coil)
REM    Cooling mode      → modulate based on HWC LAT vs SAT setpoint
REM    Economizer active → minimum face (coordinate with OA damper)
REM    DAT below freeze  → 100% face (force warm air through coil)
REM    Fan off / safety  → 100% face (stagnation freeze protection)
REM ======================================================================
REM
REM Default: full face (heating-mode safe assumption)
{device-name}-HTG-FBP-CMD = 100.0
REM
REM Cooling mode (HVAC-MODE=2): modulate F/B from HW coil LAT vs SAT setpoint.
REM HWC-DAT below SAT-SP → coil is cool → bias bypass to mix warmer air.
REM HWC-DAT above SAT-SP → coil is warm → bias face to draw on coil.
IF {device-name}-HVAC-MODE = 2 THEN {device-name}-HTG-FBP-CMD = SLIDE( {device-name}-HWC-DAT - {device-name}-ACT-SAT-SP , -4.0 , 4.0 , {device-name}-HTG-FBP-MIN-FACE , 100.0 )
REM
REM Economizer active: minimum face position (let OA bypass coil)
IF {device-name}-ECON-MODE THEN {device-name}-HTG-FBP-CMD = {device-name}-HTG-FBP-MIN-FACE
REM
REM Heating modes (Reheat=3, Heat=4): force full face
IF {device-name}-HVAC-MODE = 3 THEN {device-name}-HTG-FBP-CMD = 100.0
IF {device-name}-HVAC-MODE = 4 THEN {device-name}-HTG-FBP-CMD = 100.0
REM
REM Freeze-protection mode (from FRZ-PRTN-MODE-PRG): force full face
IF {device-name}-FRZ-PRTC-MODE THEN {device-name}-HTG-FBP-CMD = 100.0
REM
REM Safety: DAT below configured freeze threshold → force full face
IF {device-name}-HWC-DAT < {device-name}-HTG-FBP-FREEZE-SP THEN {device-name}-HTG-FBP-CMD = 100.0
REM
REM Safety: supply fan off → force full face (prevents stagnation freezing)
IF NOT {device-name}-SF-STS THEN {device-name}-HTG-FBP-CMD = 100.0
REM
REM Safety: any shutdown alarm → force full face
IF {device-name}-SAFETY-SD-ALARM THEN {device-name}-HTG-FBP-CMD = 100.0
REM
REM Clamp to actuator range
{device-name}-HTG-FBP-CMD = LIMIT( {device-name}-HTG-FBP-CMD , 0.0 , 100.0 )
REM
REM Drive physical damper output
{device-name}-HTG-FBP-DMP = {device-name}-HTG-FBP-CMD
