REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — DX Cooling Single Stage
REM ======================================================================

REM ***** Disable on safety *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-DX-COMP-1 , END

REM ***** Disable when fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-DX-COMP-1 , END

REM ***** Cooling lockout *****
IF {device-name}-CLG-LOCKOUT THEN STOP {device-name}-DX-COMP-1 , END

REM ***** Check refrigerant safeties *****
IF {device-name}-DX-HP OR {device-name}-DX-LP THEN STOP {device-name}-DX-COMP-1 , START {device-name}-DX-FAIL , END

REM ***** Minimum on/off time protection *****
IF TIME-ON( {device-name}-DX-COMP-1 ) < {device-name}-DX-MIN-ON-TIME * 1.6667 AND {device-name}-DX-COMP-1 THEN END
IF TIME-OFF( {device-name}-DX-COMP-1 ) < {device-name}-DX-MIN-OFF-TIME * 1.6667 AND NOT {device-name}-DX-COMP-1 THEN END

REM ***** Enable in cooling mode when SAT above SP *****
A = SWITCH( A , {device-name}-SAT , {device-name}-ACT-SAT-SP - 1 , {device-name}-ACT-SAT-SP + 1 )
IF A AND {device-name}-HVAC-MODE = 2 THEN START {device-name}-DX-COMP-1 ELSE STOP {device-name}-DX-COMP-1
