REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Preheat Pump Control
REM ======================================================================

REM ***** Pump on when PH valve open *****
IF {device-name}-PH-VLV > 0 THEN START A ELSE STOP A

REM ***** Pump on for freeze protection *****
B = SWITCH( B , {device-name}-NET-OAT , {device-name}-FRZ-PRTC-SP + 5 , {device-name}-FRZ-PRTC-SP )
IF B THEN START C ELSE STOP C

REM ***** Start pump if valve open OR freeze *****
IF A OR C THEN START {device-name}-PH-PMP ELSE STOP {device-name}-PH-PMP

REM ***** Failure detection — commanded on, no status after 30s *****
IF TIME-ON( {device-name}-PH-PMP ) > 0:00:30 AND NOT {device-name}-PH-PMP-STS THEN START {device-name}-PH-PMP-FAIL
IF {device-name}-PH-PMP-STS THEN STOP {device-name}-PH-PMP-FAIL
