REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — HW Coil Pump Control
REM  Standard pattern: valve open OR freeze → pump on
REM ======================================================================

REM ***** Pump on when HW valve open *****
IF {device-name}-HW-VLV > 0 THEN START A ELSE STOP A

REM ***** Pump on for freeze protection *****
B = SWITCH( B , {device-name}-NET-OAT , {device-name}-FRZ-PRTC-SP + 5 , {device-name}-FRZ-PRTC-SP )
IF B THEN START C ELSE STOP C

REM ***** Start pump if valve open OR freeze *****
IF A OR C THEN START {device-name}-HW-PMP ELSE STOP {device-name}-HW-PMP

REM ***** Failure detection — commanded on, no status after 30s *****
IF TIME-ON( {device-name}-HW-PMP ) > 0:00:30 AND NOT {device-name}-HW-PMP-STS THEN START {device-name}-HW-PMP-FAIL
IF {device-name}-HW-PMP-STS THEN STOP {device-name}-HW-PMP-FAIL
