REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — DX Cooling 2-Stage
REM ======================================================================

REM ***** Disable on safety *****
IF {device-name}-SAFETY-SD-ALARM THEN STOP {device-name}-DX-COMP-1 , STOP {device-name}-DX-COMP-2 , END

REM ***** Disable when fan off *****
IF NOT {device-name}-SF-S THEN STOP {device-name}-DX-COMP-1 , STOP {device-name}-DX-COMP-2 , END

REM ***** Cooling lockout *****
IF {device-name}-CLG-LOCKOUT THEN STOP {device-name}-DX-COMP-1 , STOP {device-name}-DX-COMP-2 , END

REM ***** Refrigerant safeties *****
IF {device-name}-DX-HP OR {device-name}-DX-LP THEN STOP {device-name}-DX-COMP-1 , STOP {device-name}-DX-COMP-2 , START {device-name}-DX-FAIL , END

REM ***** Min on/off time — Stage 1 *****
IF TIME-ON( {device-name}-DX-COMP-1 ) < {device-name}-DX-MIN-ON-TIME * 1.6667 AND {device-name}-DX-COMP-1 THEN END
IF TIME-OFF( {device-name}-DX-COMP-1 ) < {device-name}-DX-MIN-OFF-TIME * 1.6667 AND NOT {device-name}-DX-COMP-1 THEN END

REM ***** Stage 1 — enable in cooling mode *****
A = SWITCH( A , {device-name}-SAT , {device-name}-ACT-SAT-SP - 1 , {device-name}-ACT-SAT-SP + 1 )
IF A AND {device-name}-HVAC-MODE = 2 THEN START {device-name}-DX-COMP-1 ELSE STOP {device-name}-DX-COMP-1 , STOP {device-name}-DX-COMP-2 , END

REM ***** Stage 2 — enable when SAT exceeds SP by stage 2 offset *****
IF {device-name}-SAT > {device-name}-ACT-SAT-SP + {device-name}-DX-STG2-SP AND {device-name}-DX-COMP-1 THEN START {device-name}-DX-COMP-2
IF {device-name}-SAT < {device-name}-ACT-SAT-SP + 1 THEN STOP {device-name}-DX-COMP-2
