REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — AHU Running OK Status
REM ======================================================================

IF {device-name}-SF-S AND NOT {device-name}-SAFETY-SD-ALARM THEN START {device-name}-AHU-OK ELSE STOP {device-name}-AHU-OK
