REM **** Makeup Water Flow Monitoring
REM **** Generated by SBS Composition Engine v2

REM **** Totalize flow — 60 second execution interval ****
{device-name}-MAKEUP-WTR-TTL = {device-name}-MAKEUP-WTR-TTL + {device-name}-MAKEUP-WTR-FLOW

REM **** High flow alarm — SWITCH with deadband ****
A = SWITCH( A , {device-name}-MAKEUP-WTR-FLOW , {device-name}-MAKEUP-WTR-HI-SP - 5 , {device-name}-MAKEUP-WTR-HI-SP )
IF A THEN START {device-name}-MAKEUP-WTR-ALARM ELSE STOP {device-name}-MAKEUP-WTR-ALARM

REM **** Reset totalizer on command ****
IF {device-name}-MAKEUP-WTR-RESET THEN {device-name}-MAKEUP-WTR-TTL = 0 , STOP {device-name}-MAKEUP-WTR-RESET
