10 REM ========================================
20 REM  {device-name} Combustion Damper Monitor
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 REM Interlock: boiler cannot fire if damper closed
60 IF {device-name}-BLR1-COMB-DMPR-STS = CLOSED THEN {device-name}-COMB-DMPR-ALARM = ON
