10 REM ========================================
20 REM  {device-name} Boiler Fire Rate Control
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 REM Fire rate modulation per boiler
60 REM Each boiler ramps from low fire to high fire proportionally
70 DEV = {device-name}-ACT-HWS-TEMP-SP - {device-name}-HWS-T
80 REM Boiler 1 fire rate
90 IF {device-name}-BLR1-SS = ON THEN RATE1 = {device-name}-B1-LOW-FIRE + (DEV / 20) * ({device-name}-B1-HI-FIRE - {device-name}-B1-LOW-FIRE)
100 IF RATE1 < {device-name}-B1-LOW-FIRE THEN RATE1 = {device-name}-B1-LOW-FIRE
110 IF RATE1 > {device-name}-B1-HI-FIRE THEN RATE1 = {device-name}-B1-HI-FIRE
120 {device-name}-BLR1-MOD = RATE1 * {device-name}-B1-VOLT-BURN%-CNV
