REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Cascade Boiler Control
REM  Enable boilers and communicate supply temp setpoint
REM ======================================================================

REM ***** Enable boilers when system is enabled *****
IF {device-name}-HW-SYS-ENAB THEN START {device-name}-BLRS-ENABLE ELSE STOP {device-name}-BLRS-ENABLE

REM ***** Write setpoint to boiler master *****
{device-name}-BLRS-SPT = {device-name}-ACT-HWS-TEMP-SP

REM ***** Monitor boiler alarms *****
START {device-name}-BLR-AVAIL
IF {device-name}-BLR1-ALARM THEN START {device-name}-BLR1-ALARM-STS , STOP {device-name}-BLR-AVAIL
IF NOT {device-name}-BLR1-ALARM THEN STOP {device-name}-BLR1-ALARM-STS
IF {device-name}-BLR2-ALARM THEN START {device-name}-BLR2-ALARM-STS , STOP {device-name}-BLR-AVAIL
IF NOT {device-name}-BLR2-ALARM THEN STOP {device-name}-BLR2-ALARM-STS
