REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Heat Exchanger Modulating Valve
REM ======================================================================

REM ***** Delta T monitoring *****
{device-name}-HX-DELTA-T = {device-name}-HX-SUPW-T - {device-name}-HX-RETW-T

REM ***** Valve from PID loop *****
A = {device-name}-HX-VLV
B = loop3
IF {device-name}-HW-SYS-ENAB THEN {device-name}-HX-VLV = RAMP( ABS( A - B ) > 1 , A , B , 3.33 ) ELSE {device-name}-HX-VLV = 0
IF ABS( A - B ) < 1 THEN {device-name}-HX-VLV = B
