REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Boiler Isolation Valve Sequencing
REM  Open isolation valve BEFORE boiler enable, close AFTER disable
REM ======================================================================

REM ***** Boiler 1 isolation valve *****
IF {device-name}-BLR1-SS OR {device-name}-BLR1-S/S THEN START {device-name}-BLR1-ISO-VLV ELSE A = A + INTERVAL
IF A > {device-name}-ISO-VLV-OPEN-DLY THEN STOP {device-name}-BLR1-ISO-VLV , A = 0
IF {device-name}-BLR1-SS OR {device-name}-BLR1-S/S THEN A = 0

REM ***** Boiler 2 isolation valve *****
IF {device-name}-BLR2-SS OR {device-name}-BLR2-S/S THEN START {device-name}-BLR2-ISO-VLV ELSE B = B + INTERVAL
IF B > {device-name}-ISO-VLV-OPEN-DLY THEN STOP {device-name}-BLR2-ISO-VLV , B = 0
IF {device-name}-BLR2-SS OR {device-name}-BLR2-S/S THEN B = 0
