REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Boiler Fire Rate Modulation
REM  Controls 0-10V fire rate output per boiler
REM ======================================================================

REM ***** Boiler supply temp setpoint *****
{device-name}-BLR-SUPPLY-STPNT = {device-name}-ACT-HWS-TEMP-SP

REM ***** Boiler 1 fire rate *****
IF NOT {device-name}-BLR1-SS THEN {device-name}-BLR1-MOD = 0 , GOTO 100
{device-name}-B1-DEV = {device-name}-BLR-SUPPLY-STPNT - {device-name}-HWS-T
RATE = {device-name}-B1-LOW-FIRE + ( {device-name}-B1-DEV / 20 ) * ( {device-name}-B1-HI-FIRE - {device-name}-B1-LOW-FIRE )
IF RATE < {device-name}-B1-LOW-FIRE THEN RATE = {device-name}-B1-LOW-FIRE
IF RATE > {device-name}-B1-HI-FIRE THEN RATE = {device-name}-B1-HI-FIRE
{device-name}-BLR1-MOD = RATE * {device-name}-B1-VOLT-BURN%-CNV / 100

REM ***** Boiler 2 fire rate *****
IF NOT {device-name}-BLR2-SS THEN {device-name}-BLR2-MOD = 0 , END
{device-name}-B2-DEV = {device-name}-BLR-SUPPLY-STPNT - {device-name}-HWS-T
RATE = {device-name}-B2-LOW-FIRE + ( {device-name}-B2-DEV / 20 ) * ( {device-name}-B2-HI-FIRE - {device-name}-B2-LOW-FIRE )
IF RATE < {device-name}-B2-LOW-FIRE THEN RATE = {device-name}-B2-LOW-FIRE
IF RATE > {device-name}-B2-HI-FIRE THEN RATE = {device-name}-B2-HI-FIRE
{device-name}-BLR2-MOD = RATE * {device-name}-B2-VOLT-BURN%-CNV / 100
