REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — VFD Pump Lead/Lag Rotation
REM  Same logic as constant speed — schedule + failure swap
REM ======================================================================

REM ***** Read lead pump from rotation schedule *****
{device-name}-LEAD-HWP = {device-name}-HWP-LEAD-SCHED

REM ***** Swap if scheduled lead is failed or OOS *****
IF {device-name}-LEAD-HWP = 1 AND ( {device-name}-HWP1-FAIL OR {device-name}-HWP1-OOS ) THEN {device-name}-LEAD-HWP = 2
IF {device-name}-LEAD-HWP = 2 AND ( {device-name}-HWP2-FAIL OR {device-name}-HWP2-OOS ) THEN {device-name}-LEAD-HWP = 1

REM ***** Lead pump failure flag *****
IF {device-name}-LEAD-HWP = 1 THEN {device-name}-LEAD-HWP-FAIL = {device-name}-HWP1-FAIL
IF {device-name}-LEAD-HWP = 2 THEN {device-name}-LEAD-HWP-FAIL = {device-name}-HWP2-FAIL

REM ***** System off — stop everything *****
IF NOT {device-name}-HW-SYS-ENAB THEN STOP {device-name}-LEAD-HWP-SS , STOP {device-name}-LAG-HWP-SS , END

REM ***** Start lead pump *****
START {device-name}-LEAD-HWP-SS

REM ***** Lag pump on lead failure only *****
IF {device-name}-LEAD-HWP-FAIL THEN START {device-name}-LAG-HWP-SS ELSE STOP {device-name}-LAG-HWP-SS

REM ***** Any pump running *****
IF {device-name}-HWP1-STS OR {device-name}-HWP2-STS THEN START {device-name}-ANY-HWP-ON ELSE STOP {device-name}-ANY-HWP-ON
