REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — HW Supply Temperature Setpoint
REM  OA reset with network valve position feedback trim
REM ======================================================================

REM ***** OA Reset calculation *****
REM  Linear reset: at OA-MIN -> HW-MAX, at OA-MAX -> HW-MIN
OA = {device-name}-NET-OAT
OMIN = {device-name}-CFG-RESET-OA-MIN
OMAX = {device-name}-CFG-RESET-OA-MAX
HMIN = {device-name}-CFG-RESET-HW-MIN
HMAX = {device-name}-CFG-RESET-HW-MAX

IF OA < OMIN THEN OA = OMIN
IF OA > OMAX THEN OA = OMAX
{device-name}-HHW-OA-RESET = HMAX - ( OA - OMIN ) / ( OMAX - OMIN ) * ( HMAX - HMIN )

REM ***** Valve position feedback trim *****
REM  If avg valve < 30% -> reduce SPT, if > 70% -> increase SPT
V = {device-name}-NET-HWV-POS-AVG
IF V < 30 THEN {device-name}-HHW-HWV-OFFSET = ( V - 50 ) * 0.3
IF V > 70 THEN {device-name}-HHW-HWV-OFFSET = ( V - 50 ) * 0.3
IF V >= 30 AND V <= 70 THEN {device-name}-HHW-HWV-OFFSET = 0

REM ***** Active setpoint = OA reset + valve trim *****
{device-name}-ACT-HWS-TEMP-SP = {device-name}-HHW-OA-RESET + {device-name}-HHW-HWV-OFFSET

REM ***** Clamp to min/max *****
IF {device-name}-ACT-HWS-TEMP-SP < HMIN THEN {device-name}-ACT-HWS-TEMP-SP = HMIN
IF {device-name}-ACT-HWS-TEMP-SP > HMAX THEN {device-name}-ACT-HWS-TEMP-SP = HMAX
