REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Heat Exchanger 1/3 + 2/3 Floating Valve Sequence
REM  Stage 1: 1/3 opens 0-100%. Once full open ->
REM  Stage 2: 2/3 opens, 1/3 closes. 2/3 full open ->
REM  Stage 3: 1/3 reopens for remaining capacity
REM ======================================================================

{device-name}-HX-DELTA-T = {device-name}-HX-SUPW-T - {device-name}-HX-RETW-T

REM ***** PID loop output 0-100 *****
P = loop3
IF NOT {device-name}-HW-SYS-ENAB THEN {device-name}-HX-VLV-1/3-POS = 0 , {device-name}-HX-VLV-2/3-POS = 0 , END

REM ***** Stage 1: 1/3 valve only (PID 0-33%) *****
IF P <= 33 THEN {device-name}-HX-VLV-1/3-POS = P * 3 , {device-name}-HX-VLV-2/3-POS = 0 , END

REM ***** Stage 2: 2/3 opens, 1/3 closes (PID 33-66%) *****
IF P <= 66 THEN {device-name}-HX-VLV-1/3-POS = 100 - ( P - 33 ) * 3 , {device-name}-HX-VLV-2/3-POS = ( P - 33 ) * 3 , END

REM ***** Stage 3: 2/3 full, 1/3 reopens (PID 66-100%) *****
{device-name}-HX-VLV-2/3-POS = 100
{device-name}-HX-VLV-1/3-POS = ( P - 66 ) * 2.94

REM ***** Write to physical outputs *****
{device-name}-HX-VLV-1/3 = {device-name}-HX-VLV-1/3-POS
{device-name}-HX-VLV-2/3 = {device-name}-HX-VLV-2/3-POS
