REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Network Data Reads from AHU Controllers
REM ======================================================================

REM ***** Aggregate heating requests from all AHUs *****
{device-name}-TOTAL-HTG-REQS = 0

REM ***** AHU 1 data reads *****
REM  Configured per-AHU by AHU-CFG programs
REM  Each AHU-CFG reads zone data via BACnet from the AHU device
REM  HW valve position is used for valve feedback trim in SPT program

REM ***** Write HW availability to all AHUs *****
REM  Each AHU reads {device-name}-HW-AVAIL via BACnet
