REM **** HW Pump 1 S/S program
REM **** Generated by SBS Composition Engine v2
REM **** Pump starts when system is enabled and pump is in lead
REM **** or system is enabled and lead pump has failed

REM **** Check out of service ****
IF {device-name}-HWP1-OOS THEN STOP {device-name}-HWP1-S/S , END

REM **** Check pump failure — do not restart until reset ****
IF {device-name}-HWP1-FAIL THEN STOP {device-name}-HWP1-S/S , END

REM **** Determine if pump 1 is lead or lag ****
REM **** If LEAD-HWP = 1, pump 1 is lead — run on LEAD-HWP-SS
REM **** If LEAD-HWP = 2, pump 1 is lag  — run on LAG-HWP-SS
IF {device-name}-LEAD-HWP < 2 THEN A = {device-name}-LEAD-HWP-SS
IF {device-name}-LEAD-HWP >= 2 THEN A = {device-name}-LAG-HWP-SS

REM **** Start/stop pump ****
IF A AND NOT {device-name}-HWP1-OOS THEN START {device-name}-HWP1-S/S ELSE STOP {device-name}-HWP1-S/S

REM **** Failure detection — pump commanded on but no status proof ****
IF TIME-ON( {device-name}-HWP1-S/S ) > 0:00:30 AND NOT {device-name}-HWP1-STS THEN START {device-name}-HWP1-FAIL
IF {device-name}-HWP1-STS THEN STOP {device-name}-HWP1-FAIL

REM **** Reset failure on safety reset command ****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-HWP1-FAIL
