REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Boiler Lead Rotation
REM ======================================================================

REM ***** Lead boiler determined by schedule *****
{device-name}-LEAD-BLR = {device-name}-BLR-LEAD-SCHED
