REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Pump Lead/Lag Rotation
REM ======================================================================

REM ***** Lead pump from schedule *****
{device-name}-LEAD-HWP = {device-name}-HWP-LEAD-SCHED
