REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — HW Plant Configuration Program
REM  Reads network data, calculates enthalpy, determines system enable
REM ======================================================================

REM ***** Read outside air data from hardwired sensors *****
{device-name}-NET-OAT = {device-name}-OAT
{device-name}-NET-OAH = {device-name}-OAH

REM ***** Calculate outside air enthalpy *****
{device-name}-NET-OA-ERH = ENTHALPY( {device-name}-NET-OAT , {device-name}-NET-OAH , 1 )

REM ***** Calculate HW delta T *****
{device-name}-HW-DELTA-T = {device-name}-HWS-T - {device-name}-HWR-T

REM ***** System enable based on OA temperature *****
A = SWITCH( A , {device-name}-NET-OAT , {device-name}-CFG-HHW-OA-ENAB-SP + 3 , {device-name}-CFG-HHW-OA-ENAB-SP )
IF A THEN STOP {device-name}-HW-SYS-ENAB ELSE START {device-name}-HW-SYS-ENAB
