10 REM ========================================
20 REM  {device-name} HW System Status
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 {device-name}-HW-DELTA-T = {device-name}-HWS-T - {device-name}-HWR-T
60 REM HW Available flag - set when system is enabled and no critical alarms
70 IF {device-name}-HW-SYS-ENAB = ON AND {device-name}-ALARM-INHIBIT = OFF THEN {device-name}-HW-AVAIL = ON ELSE {device-name}-HW-AVAIL = OFF
