REM **** Network Data Reads from AHU Controllers
REM **** Generated by SBS Composition Engine v2
REM **** Aggregate heating requests from all served AHUs

{device-name}-TOTAL-HTG-REQS = 0

REM **** Per-AHU data reads configured in AHU-CFG programs ****
REM **** HW valve positions feed back to SPT program for trim ****
REM **** HW available written to all AHUs via BACnet ****
