REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — HW Pump VFD Speed Control
REM  DP PID loop output drives pump speed through SLIDE + RAMP
REM ======================================================================

REM ***** Average DP from sensors *****
{device-name}-AVG-DP = ( {device-name}-HW-PRESS1 + {device-name}-HW-PRESS2 ) / 2

REM ***** Scale loop output to speed range *****
A = {device-name}-HWP1-SPEED
B = SLIDE( loop1 , 0 , 100 , {device-name}-HWP-MIN-SPEED , {device-name}-HWP-MAX-SPEED )

REM ***** Ramp speed — same pattern as AHU supply fan *****
IF {device-name}-ANY-HWP-ON THEN {device-name}-HWP1-SPEED = RAMP( ABS( A - B ) > 1 , A , B , 3.33 ) ELSE {device-name}-HWP1-SPEED = 0
IF ABS( A - B ) < 1 THEN {device-name}-HWP1-SPEED = B

REM ***** Both pumps track same speed when running *****
IF {device-name}-HWP2-STS THEN {device-name}-HWP2-SPEED = {device-name}-HWP1-SPEED ELSE {device-name}-HWP2-SPEED = 0

REM ***** Zero speed when no pump running *****
IF NOT {device-name}-ANY-HWP-ON THEN {device-name}-HWP1-SPEED = 0 , {device-name}-HWP2-SPEED = 0
