REM **** HW Plant Configuration Program
REM **** Generated by SBS Composition Engine v2
REM **** Network reads, enthalpy, runtime tracking, DP averaging

REM **** Set outside air variables from hardwired sensors ****
{device-name}-NET-OAT = {device-name}-OAT
{device-name}-NET-OAH = {device-name}-OAH

REM **** Calculate outside air enthalpy ****
{device-name}-NET-OA-ERH = ENTHALPY( {device-name}-NET-OAT , {device-name}-NET-OAH , 1 )

REM **** Calculate HW delta T ****
{device-name}-HW-DELTA-T = {device-name}-HWS-T - {device-name}-HWR-T

REM **** Pump runtime tracking (hours) ****
{device-name}-HWP1-RUNTIME = TIME-ON( {device-name}-HWP1-STS ) / 3600
{device-name}-HWP2-RUNTIME = TIME-ON( {device-name}-HWP2-STS ) / 3600

REM **** DP sensor averaging (moved here from speed program) ****
{device-name}-AVG-DP = ABS( ( {device-name}-HW-PRESS1 + {device-name}-HW-PRESS2 ) / 2 )

REM **** System enable — SWITCH with 3 degree deadband ****
A = SWITCH( A , {device-name}-NET-OAT , {device-name}-CFG-HHW-OA-ENAB-SP + 3 , {device-name}-CFG-HHW-OA-ENAB-SP )
IF A THEN STOP {device-name}-HW-SYS-ENAB ELSE START {device-name}-HW-SYS-ENAB
