REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — HW Plant System Status
REM ======================================================================

REM ***** HW Available flag — system enabled and no critical alarms *****
IF {device-name}-HW-SYS-ENAB AND NOT {device-name}-ALARM-INHIBIT THEN START {device-name}-HW-AVAIL ELSE STOP {device-name}-HW-AVAIL
