REM **** Secondary Pump Lead/Lag Rotation
REM **** Generated by SBS Composition Engine v2
REM **** Schedule rotation with failure swap

REM **** Calculate runtimes ****
A = TIME-ON( {device-name}-SHWP1-STS ) / 3600
B = TIME-ON( {device-name}-SHWP2-STS ) / 3600

REM **** Read lead from schedule ****
{device-name}-LEAD-SHWP = {device-name}-SHWP-LEAD-SCHED

REM **** Force swap on failure or OOS ****
IF {device-name}-LEAD-SHWP < 2 AND {device-name}-SHWP1-FAIL THEN {device-name}-LEAD-SHWP = 2
IF {device-name}-LEAD-SHWP < 2 AND {device-name}-SHWP1-OOS THEN {device-name}-LEAD-SHWP = 2
IF {device-name}-LEAD-SHWP >= 2 AND {device-name}-SHWP2-FAIL THEN {device-name}-LEAD-SHWP = 1
IF {device-name}-LEAD-SHWP >= 2 AND {device-name}-SHWP2-OOS THEN {device-name}-LEAD-SHWP = 1

REM **** Clamp ****
{device-name}-LEAD-SHWP = LIMIT( {device-name}-LEAD-SHWP , 1 , 2 )

REM **** Lead failure flag ****
IF {device-name}-LEAD-SHWP < 2 THEN {device-name}-LEAD-SHWP-FAIL = {device-name}-SHWP1-FAIL
IF {device-name}-LEAD-SHWP >= 2 THEN {device-name}-LEAD-SHWP-FAIL = {device-name}-SHWP2-FAIL

REM **** System off — stop all ****
IF NOT {device-name}-HW-SYS-ENAB THEN STOP {device-name}-LEAD-SHWP-SS , STOP {device-name}-LAG-SHWP-SS , END

REM **** Start lead ****
START {device-name}-LEAD-SHWP-SS

REM **** Lag on lead failure ****
IF {device-name}-LEAD-SHWP-FAIL THEN START {device-name}-LAG-SHWP-SS ELSE STOP {device-name}-LAG-SHWP-SS

REM **** Any secondary running ****
IF {device-name}-SHWP1-STS OR {device-name}-SHWP2-STS THEN START {device-name}-ANY-SHWP-ON ELSE STOP {device-name}-ANY-SHWP-ON
