REM **** Boiler Staging Control
REM **** Generated by SBS Composition Engine v2
REM **** Deviation-based staging with OOS check and lead/lag

REM **** System off — stop all boilers ****
IF NOT {device-name}-HW-SYS-ENAB THEN STOP {device-name}-BLR1-S/S , STOP {device-name}-BLR2-S/S , STOP {device-name}-LEAD-BLR-SS , STOP {device-name}-LAG-BLR-SS , RELINQUISH {device-name}-BLR1-MOD , RELINQUISH {device-name}-BLR2-MOD , END

REM **** Boiler 1 OOS check ****
IF {device-name}-BLR1-OOS THEN STOP {device-name}-BLR1-S/S , {device-name}-BLR1-MOD = 0

REM **** Boiler 2 OOS check ****
IF {device-name}-BLR2-OOS THEN STOP {device-name}-BLR2-S/S , {device-name}-BLR2-MOD = 0

REM **** Calculate deviation from setpoint ****
{device-name}-LEAD-BLR-DEV = {device-name}-ACT-HWS-TEMP-SP - {device-name}-HWS-T
{device-name}-TOTAL-BLRS-REQUESTED = 0

REM **** Lead boiler staging — SWITCH with 5 deg on / -5 deg off ****
A = SWITCH( A , {device-name}-LEAD-BLR-DEV , -5 , 5 )
IF A AND {device-name}-ANY-HWP-ON THEN START {device-name}-LEAD-BLR-SS ELSE STOP {device-name}-LEAD-BLR-SS
IF {device-name}-LEAD-BLR-SS THEN {device-name}-TOTAL-BLRS-REQUESTED = {device-name}-TOTAL-BLRS-REQUESTED + 1

REM **** Lag boiler — SWITCH 5/15 deg deadband, only with lead running ****
B = SWITCH( B , {device-name}-LEAD-BLR-DEV , 5 , 15 )
IF B AND {device-name}-LEAD-BLR-SS THEN START {device-name}-LAG-BLR-SS ELSE STOP {device-name}-LAG-BLR-SS
IF {device-name}-LAG-BLR-SS THEN {device-name}-TOTAL-BLRS-REQUESTED = {device-name}-TOTAL-BLRS-REQUESTED + 1

REM **** Map lead/lag to physical boilers ****
IF {device-name}-LEAD-BLR < 2 THEN {device-name}-BLR1-SS = {device-name}-LEAD-BLR-SS , {device-name}-BLR2-SS = {device-name}-LAG-BLR-SS
IF {device-name}-LEAD-BLR >= 2 THEN {device-name}-BLR2-SS = {device-name}-LEAD-BLR-SS , {device-name}-BLR1-SS = {device-name}-LAG-BLR-SS

REM **** Write S/S — interlock with alarms AND OOS ****
IF {device-name}-BLR1-SS AND NOT {device-name}-BLR1-ALARM AND NOT {device-name}-BLR1-OOS THEN START {device-name}-BLR1-S/S ELSE STOP {device-name}-BLR1-S/S
IF {device-name}-BLR2-SS AND NOT {device-name}-BLR2-ALARM AND NOT {device-name}-BLR2-OOS THEN START {device-name}-BLR2-S/S ELSE STOP {device-name}-BLR2-S/S

REM **** Boiler failure — alarm while commanded on ****
IF {device-name}-BLR1-ALARM AND {device-name}-BLR1-SS THEN START {device-name}-BLR1-FAIL ELSE STOP {device-name}-BLR1-FAIL
IF {device-name}-BLR2-ALARM AND {device-name}-BLR2-SS THEN START {device-name}-BLR2-FAIL ELSE STOP {device-name}-BLR2-FAIL

REM **** Lead boiler failure flag ****
IF {device-name}-LEAD-BLR < 2 THEN {device-name}-LEAD-BLR-FAIL = {device-name}-BLR1-FAIL
IF {device-name}-LEAD-BLR >= 2 THEN {device-name}-LEAD-BLR-FAIL = {device-name}-BLR2-FAIL

REM **** Reset failures ****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-BLR1-FAIL , STOP {device-name}-BLR2-FAIL , STOP {device-name}-LEAD-BLR-FAIL
