REM **** Secondary Pump Lead/Lag Rotation
REM **** Generated by SBS Composition Engine v2

REM **** Immediate failover ****
IF {device-name}-LEAD-SHWP < 2 AND {device-name}-SHWP1-FAIL THEN {device-name}-LEAD-SHWP = 2
IF {device-name}-LEAD-SHWP < 2 AND {device-name}-SHWP1-OOS THEN {device-name}-LEAD-SHWP = 2
IF {device-name}-LEAD-SHWP >= 2 AND {device-name}-SHWP2-FAIL THEN {device-name}-LEAD-SHWP = 1
IF {device-name}-LEAD-SHWP >= 2 AND {device-name}-SHWP2-OOS THEN {device-name}-LEAD-SHWP = 1

REM **** Runtime-based rotation ****
IF {device-name}-SHWP1-RUNTIME > {device-name}-SHWP2-RUNTIME AND {device-name}-LEAD-SHWP < 2 AND {device-name}-SHWP1-RUNTIME - {device-name}-SHWP2-RUNTIME > 1 THEN {device-name}-LEAD-SHWP = 2
IF {device-name}-SHWP2-RUNTIME > {device-name}-SHWP1-RUNTIME AND {device-name}-LEAD-SHWP >= 2 AND {device-name}-SHWP2-RUNTIME - {device-name}-SHWP1-RUNTIME > 1 THEN {device-name}-LEAD-SHWP = 1

{device-name}-LEAD-SHWP = LIMIT( {device-name}-LEAD-SHWP , 1 , 2 )

IF {device-name}-LEAD-SHWP < 2 THEN {device-name}-LEAD-SHWP-FAIL = {device-name}-SHWP1-FAIL
IF {device-name}-LEAD-SHWP >= 2 THEN {device-name}-LEAD-SHWP-FAIL = {device-name}-SHWP2-FAIL

IF NOT {device-name}-HW-SYS-ENAB THEN STOP {device-name}-LEAD-SHWP-SS , STOP {device-name}-LAG-SHWP-SS , END

START {device-name}-LEAD-SHWP-SS
IF {device-name}-LEAD-SHWP-FAIL THEN START {device-name}-LAG-SHWP-SS ELSE STOP {device-name}-LAG-SHWP-SS
IF {device-name}-SHWP1-STS OR {device-name}-SHWP2-STS THEN START {device-name}-ANY-SHWP-ON ELSE STOP {device-name}-ANY-SHWP-ON
