REM **** Lead/Lag Program
REM **** Generated by SBS Composition Engine v2
REM **** Runtime-based pump rotation with failure swap
REM **** Combined pump and boiler rotation (when full control boilers present)

REM **** Immediate failover on pump failure — no schedule needed ****
IF {device-name}-LEAD-HWP < 2 AND {device-name}-HWP1-FAIL THEN {device-name}-LEAD-HWP = 2
IF {device-name}-LEAD-HWP < 2 AND {device-name}-HWP1-OOS THEN {device-name}-LEAD-HWP = 2
IF {device-name}-LEAD-HWP >= 2 AND {device-name}-HWP2-FAIL THEN {device-name}-LEAD-HWP = 1
IF {device-name}-LEAD-HWP >= 2 AND {device-name}-HWP2-OOS THEN {device-name}-LEAD-HWP = 1

REM **** Runtime-based rotation — swap when higher runtime pump is lead ****
REM **** Only swap if rotation hold time has elapsed ****
IF {device-name}-HWP1-RUNTIME > {device-name}-HWP2-RUNTIME AND {device-name}-LEAD-HWP < 2 AND {device-name}-HWP1-RUNTIME - {device-name}-HWP2-RUNTIME > 1 AND TIME-ON( {device-name}-LEAD-HWP-SS ) / 3600 > {device-name}-HWP-ROTATION-HOLD THEN {device-name}-LEAD-HWP = 2
IF {device-name}-HWP2-RUNTIME > {device-name}-HWP1-RUNTIME AND {device-name}-LEAD-HWP >= 2 AND {device-name}-HWP2-RUNTIME - {device-name}-HWP1-RUNTIME > 1 AND TIME-ON( {device-name}-LEAD-HWP-SS ) / 3600 > {device-name}-HWP-ROTATION-HOLD THEN {device-name}-LEAD-HWP = 1

REM **** Clamp lead pump to valid range ****
{device-name}-LEAD-HWP = LIMIT( {device-name}-LEAD-HWP , 1 , 2 )

REM **** Set lead pump failure flag ****
IF {device-name}-LEAD-HWP < 2 THEN {device-name}-LEAD-HWP-FAIL = {device-name}-HWP1-FAIL
IF {device-name}-LEAD-HWP >= 2 THEN {device-name}-LEAD-HWP-FAIL = {device-name}-HWP2-FAIL

REM **** System off — stop all pump commands ****
IF NOT {device-name}-HW-SYS-ENAB THEN STOP {device-name}-LEAD-HWP-SS , STOP {device-name}-LAG-HWP-SS , END

REM **** System on — start lead pump ****
START {device-name}-LEAD-HWP-SS

REM **** Start lag pump ONLY if lead has failed ****
IF {device-name}-LEAD-HWP-FAIL THEN START {device-name}-LAG-HWP-SS ELSE STOP {device-name}-LAG-HWP-SS

REM **** Any pump running ****
IF {device-name}-HWP1-STS OR {device-name}-HWP2-STS THEN START {device-name}-ANY-HWP-ON ELSE STOP {device-name}-ANY-HWP-ON

REM **** Boiler lead/lag (full control only — uses same rotation pattern) ****
REM **** If LEAD-BLR exists, swap on failure same as pumps ****
IF {device-name}-LEAD-BLR < 2 AND {device-name}-BLR1-FAIL THEN {device-name}-LEAD-BLR = 2
IF {device-name}-LEAD-BLR >= 2 AND {device-name}-BLR2-FAIL THEN {device-name}-LEAD-BLR = 1
{device-name}-LEAD-BLR = LIMIT( {device-name}-LEAD-BLR , 1 , 2 )
