REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — HW Pump 1 Start/Stop Control
REM  Pattern: one program per pump, lead/lag in separate program
REM ======================================================================

REM ***** Determine if this pump should run *****
REM  Run if: (lead pump AND system enabled) OR (lag pump AND lead failed)
IF {device-name}-LEAD-HWP = 1 THEN A = {device-name}-LEAD-HWP-SS
IF {device-name}-LEAD-HWP = 2 THEN A = {device-name}-LAG-HWP-SS

REM ***** Out of service override *****
IF {device-name}-HWP1-OOS THEN STOP {device-name}-HWP1-S/S , END

REM ***** Start/stop pump *****
IF A AND NOT {device-name}-HWP1-FAIL THEN START {device-name}-HWP1-S/S ELSE STOP {device-name}-HWP1-S/S

REM ***** Failure detection — commanded on, no status after 30 sec *****
IF TIME-ON( {device-name}-HWP1-S/S ) > 0:00:30 AND NOT {device-name}-HWP1-STS THEN START {device-name}-HWP1-FAIL
IF {device-name}-HWP1-STS THEN STOP {device-name}-HWP1-FAIL

REM ***** Reset failure on safety reset command *****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-HWP1-FAIL
