10 REM ========================================
20 REM  {device-name} Mixing Valve Control
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 {device-name}-HWV-PID-SP = {device-name}-ACT-HWS-TEMP-SP
60 REM Valve position from PID loop
70 {device-name}-HW-MIXING-VLV = LOOP({device-name}-HWV-PID)
