REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Secondary Pump VFD Speed
REM  DP PID loop output → SLIDE → RAMP → speed output
REM ======================================================================

REM ***** Scale loop output to speed range *****
A = {device-name}-SHWP1-SPEED
B = SLIDE( loop1 , 0 , 100 , {device-name}-HWP-MIN-SPEED , {device-name}-HWP-MAX-SPEED )

REM ***** Ramp speed *****
IF {device-name}-SHWP1-STS THEN {device-name}-SHWP1-SPEED = RAMP( ABS( A - B ) > 1 , A , B , 3.33 ) ELSE {device-name}-SHWP1-SPEED = 0
IF ABS( A - B ) < 1 THEN {device-name}-SHWP1-SPEED = B

REM ***** Pump 2 tracks same speed *****
IF {device-name}-SHWP2-STS THEN {device-name}-SHWP2-SPEED = {device-name}-SHWP1-SPEED ELSE {device-name}-SHWP2-SPEED = 0
