REM **** Cascade Boiler Control
REM **** Generated by SBS Composition Engine v2
REM **** Enable boilers when system enabled and pump proven

REM **** Enable boilers — requires system on AND at least one pump running ****
IF {device-name}-HW-SYS-ENAB AND {device-name}-ANY-HWP-ON THEN START {device-name}-BLRS-ENABLE ELSE STOP {device-name}-BLRS-ENABLE

REM **** Write supply temp setpoint to boiler master ****
{device-name}-BLRS-SPT = {device-name}-ACT-HWS-TEMP-SP

REM **** Monitor boiler alarms — set availability ****
START {device-name}-BLR-AVAIL
IF {device-name}-BLR1-ALARM THEN START {device-name}-BLR1-ALARM-STS , STOP {device-name}-BLR-AVAIL ELSE STOP {device-name}-BLR1-ALARM-STS
IF {device-name}-BLR2-ALARM THEN START {device-name}-BLR2-ALARM-STS , STOP {device-name}-BLR-AVAIL ELSE STOP {device-name}-BLR2-ALARM-STS
