REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Boiler Lead/Lag Rotation
REM  Schedule driven with automatic failure swap
REM ======================================================================

REM ***** Read lead boiler from schedule *****
{device-name}-LEAD-BLR = {device-name}-BLR-LEAD-SCHED

REM ***** Force swap on lead boiler failure *****
IF {device-name}-LEAD-BLR = 1 AND {device-name}-BLR1-FAIL THEN {device-name}-LEAD-BLR = 2
IF {device-name}-LEAD-BLR = 2 AND {device-name}-BLR2-FAIL THEN {device-name}-LEAD-BLR = 1
