REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Secondary Pump Control
REM ======================================================================

REM ***** Start lead secondary pump when system enabled *****
IF {device-name}-HW-SYS-ENAB THEN START {device-name}-SHWP1 ELSE STOP {device-name}-SHWP1

REM ***** Secondary pump 1 failure — start pump 2 *****
IF {device-name}-SHWP1 AND NOT {device-name}-SHWP1-STS THEN A = A + INTERVAL ELSE A = 0
IF A > 30 THEN START {device-name}-SHWP1-FAIL
IF {device-name}-SHWP1-FAIL THEN START {device-name}-SHWP2 ELSE STOP {device-name}-SHWP2
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-SHWP1-FAIL , A = 0
