REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — HW Pump Lead/Lag Rotation
REM  
REM  Schedule sets normal lead pump. Failure forces automatic swap.
REM  Lead pump runs whenever system is enabled.
REM  Lag pump runs only on lead failure or manual command.
REM  
REM  Points used:
REM    LEAD-HWP         AV  — current lead pump number (1 or 2)
REM    LEAD-HWP-SS      BV  — lead pump run command
REM    LAG-HWP-SS       BV  — lag pump run command
REM    LEAD-HWP-FAIL    BV  — lead pump has failed
REM    ANY-HWP-ON       BV  — at least one pump confirmed running
REM    HWP{N}-FAIL      BV  — individual pump failure (from pump programs)
REM    HWP{N}-OOS       BV  — individual pump out of service
REM ======================================================================

REM ***** Read lead pump selection from rotation schedule *****
{device-name}-LEAD-HWP = {device-name}-HWP-LEAD-SCHED

REM ***** Check if scheduled lead pump is available *****
REM  If lead pump failed or OOS, swap to other pump
IF {device-name}-LEAD-HWP = 1 AND ( {device-name}-HWP1-FAIL OR {device-name}-HWP1-OOS ) THEN {device-name}-LEAD-HWP = 2
IF {device-name}-LEAD-HWP = 2 AND ( {device-name}-HWP2-FAIL OR {device-name}-HWP2-OOS ) THEN {device-name}-LEAD-HWP = 1

REM ***** Set lead pump failure flag based on current lead *****
IF {device-name}-LEAD-HWP = 1 THEN {device-name}-LEAD-HWP-FAIL = {device-name}-HWP1-FAIL
IF {device-name}-LEAD-HWP = 2 THEN {device-name}-LEAD-HWP-FAIL = {device-name}-HWP2-FAIL

REM ***** System off — stop everything *****
IF NOT {device-name}-HW-SYS-ENAB THEN STOP {device-name}-LEAD-HWP-SS , STOP {device-name}-LAG-HWP-SS , END

REM ***** Start lead pump when system enabled *****
START {device-name}-LEAD-HWP-SS

REM ***** Start lag pump ONLY if lead has failed *****
IF {device-name}-LEAD-HWP-FAIL THEN START {device-name}-LAG-HWP-SS ELSE STOP {device-name}-LAG-HWP-SS

REM ***** Any pump running — check actual status feedback *****
IF {device-name}-HWP1-STS OR {device-name}-HWP2-STS THEN START {device-name}-ANY-HWP-ON ELSE STOP {device-name}-ANY-HWP-ON
