REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Direct Boiler Staging Control
REM  Starts/stops boilers based on supply temp deviation
REM ======================================================================

REM ***** Calculate deviation from setpoint *****
DEV = {device-name}-ACT-HWS-TEMP-SP - {device-name}-HWS-T
{device-name}-LEAD-BLR-DEV = DEV
{device-name}-TOTAL-BLRS-REQUESTED = 0

REM ***** Lead boiler start/stop *****
REM  Start when deviation > 5°F, stop when deviation < -5°F
A = SWITCH( A , DEV , -5 , 5 )
IF A AND {device-name}-HW-SYS-ENAB THEN START {device-name}-LEAD-BLR-SS ELSE STOP {device-name}-LEAD-BLR-SS
IF {device-name}-LEAD-BLR-SS THEN {device-name}-TOTAL-BLRS-REQUESTED = {device-name}-TOTAL-BLRS-REQUESTED + 1

REM ***** Lag boiler staging *****
REM  Stage on when deviation > 15°F with lead running, off when < 5°F
B = SWITCH( B , DEV , 5 , 15 )
IF B AND {device-name}-LEAD-BLR-SS THEN START {device-name}-LAG-BLR-SS ELSE STOP {device-name}-LAG-BLR-SS
IF {device-name}-LAG-BLR-SS THEN {device-name}-TOTAL-BLRS-REQUESTED = {device-name}-TOTAL-BLRS-REQUESTED + 1

REM ***** Map lead/lag to physical boilers *****
IF {device-name}-LEAD-BLR = 1 THEN {device-name}-BLR1-SS = {device-name}-LEAD-BLR-SS , {device-name}-BLR2-SS = {device-name}-LAG-BLR-SS
IF {device-name}-LEAD-BLR = 2 THEN {device-name}-BLR2-SS = {device-name}-LEAD-BLR-SS , {device-name}-BLR1-SS = {device-name}-LAG-BLR-SS

REM ***** Write start/stop outputs *****
IF {device-name}-BLR1-SS AND NOT {device-name}-BLR1-ALARM THEN START {device-name}-BLR1-S/S ELSE STOP {device-name}-BLR1-S/S
IF {device-name}-BLR2-SS AND NOT {device-name}-BLR2-ALARM THEN START {device-name}-BLR2-S/S ELSE STOP {device-name}-BLR2-S/S

REM ***** Failure detection *****
IF {device-name}-BLR1-ALARM AND {device-name}-BLR1-SS THEN START {device-name}-BLR1-FAIL
IF NOT {device-name}-BLR1-ALARM THEN STOP {device-name}-BLR1-FAIL
IF {device-name}-BLR2-ALARM AND {device-name}-BLR2-SS THEN START {device-name}-BLR2-FAIL
IF NOT {device-name}-BLR2-ALARM THEN STOP {device-name}-BLR2-FAIL

REM ***** Lead boiler failure — swap *****
IF {device-name}-LEAD-BLR = 1 AND {device-name}-BLR1-FAIL THEN START {device-name}-LEAD-BLR-FAIL
IF {device-name}-LEAD-BLR = 2 AND {device-name}-BLR2-FAIL THEN START {device-name}-LEAD-BLR-FAIL
IF NOT {device-name}-BLR1-FAIL AND NOT {device-name}-BLR2-FAIL THEN STOP {device-name}-LEAD-BLR-FAIL

REM ***** System off — stop all *****
IF NOT {device-name}-HW-SYS-ENAB THEN STOP {device-name}-BLR1-S/S , STOP {device-name}-BLR2-S/S , STOP {device-name}-LEAD-BLR-SS , STOP {device-name}-LAG-BLR-SS
