REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — HW Pump 2 Start/Stop Control
REM ======================================================================

REM ***** Determine if this pump should run *****
IF {device-name}-LEAD-HWP = 2 THEN A = {device-name}-LEAD-HWP-SS
IF {device-name}-LEAD-HWP = 1 THEN A = {device-name}-LAG-HWP-SS

REM ***** Out of service override *****
IF {device-name}-HWP2-OOS THEN STOP {device-name}-HWP2-S/S , END

REM ***** Start/stop pump *****
IF A AND NOT {device-name}-HWP2-FAIL THEN START {device-name}-HWP2-S/S ELSE STOP {device-name}-HWP2-S/S

REM ***** Failure detection *****
IF TIME-ON( {device-name}-HWP2-S/S ) > 0:00:30 AND NOT {device-name}-HWP2-STS THEN START {device-name}-HWP2-FAIL
IF {device-name}-HWP2-STS THEN STOP {device-name}-HWP2-FAIL

REM ***** Reset failure on safety reset command *****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-HWP2-FAIL
