10 REM ========================================
20 REM  {device-name} VFD Pump Lead/Lag
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 {device-name}-LEAD-HWP = SCHEDULE({device-name}-HWP-LEAD-SCHED)
