10 REM ========================================
20 REM  {device-name} HW Supply Temp Setpoint
30 REM  OA Reset with Valve Position Feedback
40 REM  Generated by SBS Composition Engine v2
50 REM ========================================
60 REM OA Reset: linear interpolation between min/max OA temp and min/max HW temp
70 OA = {device-name}-NET-OAT
80 IF OA <= {device-name}-CFG-RESET-OA-MIN THEN HW-BASE = {device-name}-CFG-RESET-HW-MAX
90 IF OA >= {device-name}-CFG-RESET-OA-MAX THEN HW-BASE = {device-name}-CFG-RESET-HW-MIN
100 IF OA > {device-name}-CFG-RESET-OA-MIN AND OA < {device-name}-CFG-RESET-OA-MAX THEN HW-BASE = {device-name}-CFG-RESET-HW-MAX - (OA - {device-name}-CFG-RESET-OA-MIN) / ({device-name}-CFG-RESET-OA-MAX - {device-name}-CFG-RESET-OA-MIN) * ({device-name}-CFG-RESET-HW-MAX - {device-name}-CFG-RESET-HW-MIN)
110 REM Valve position offset
120 {device-name}-HHW-HWV-OFFSET = ({device-name}-NET-HWV-POS-AVG - 50) * 0.2
130 {device-name}-HHW-OA-RESET = HW-BASE
140 {device-name}-ACT-HWS-TEMP-SP = HW-BASE + {device-name}-HHW-HWV-OFFSET
