REM **** HW Pump 1 VFD Speed
REM **** Generated by SBS Composition Engine v2
REM **** Speed from DP PID loop with thermal interlock

REM **** Zero speed if pump not commanded on ****
IF NOT {device-name}-HWP1-S/S THEN {device-name}-HWP1-SPEED = 0 , END

REM **** Thermal interlock — do not ramp until HWS-T > threshold ****
IF {device-name}-HWS-T < {device-name}-HWS-T-MIN-FOR-SPD THEN {device-name}-HWP1-SPEED = {device-name}-HWP-MIN-SPEED , END

REM **** Scale DP loop output to speed range ****
A = {device-name}-HWP1-SPEED
B = SLIDE( loop1 , 0 , 100 , {device-name}-HWP-MIN-SPEED , {device-name}-HWP-MAX-SPEED )

REM **** Ramp speed with configurable rate ****
{device-name}-HWP1-SPEED = RAMP( ABS( A - B ) > 1 , A , B , {device-name}-HWP-RAMP-RATE * 1.6667 )
IF ABS( A - B ) < 1 THEN {device-name}-HWP1-SPEED = B
