REM **** Secondary Pump 1 VFD Speed
REM **** Generated by SBS Composition Engine v2
REM **** Speed from DP PID loop with SLIDE and RAMP

REM **** Zero speed if pump not running ****
IF NOT {device-name}-SHWP1-STS THEN {device-name}-SHWP1-SPEED = 0 , END

REM **** Scale DP loop output to speed range ****
A = {device-name}-SHWP1-SPEED
B = SLIDE( loop1 , 0 , 100 , {device-name}-HWP-MIN-SPEED , {device-name}-HWP-MAX-SPEED )

REM **** Ramp speed ****
{device-name}-SHWP1-SPEED = RAMP( ABS( A - B ) > 1 , A , B , 3.33 )
IF ABS( A - B ) < 1 THEN {device-name}-SHWP1-SPEED = B
