REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — HW Pump Lead/Lag Rotation
REM  Schedule determines lead pump. Failure forces swap.
REM ======================================================================

REM ***** Read lead pump from schedule *****
{device-name}-LEAD-HWP = {device-name}-HWP-LEAD-SCHED

REM ***** Force swap on lead pump failure *****
IF {device-name}-LEAD-HWP = 1 AND {device-name}-HWP1-FAIL THEN {device-name}-LEAD-HWP = 2
IF {device-name}-LEAD-HWP = 2 AND {device-name}-HWP2-FAIL THEN {device-name}-LEAD-HWP = 1

REM ***** Start lead pump when system enabled *****
IF {device-name}-HW-SYS-ENAB THEN START {device-name}-LEAD-HWP-SS ELSE STOP {device-name}-LEAD-HWP-SS

REM ***** Start lag pump on lead failure *****
IF {device-name}-HW-SYS-ENAB AND {device-name}-LEAD-HWP-FAIL THEN START {device-name}-LAG-HWP-SS ELSE STOP {device-name}-LAG-HWP-SS

REM ***** Lead pump failure flag *****
IF {device-name}-LEAD-HWP = 1 THEN {device-name}-LEAD-HWP-FAIL = {device-name}-HWP1-FAIL
IF {device-name}-LEAD-HWP = 2 THEN {device-name}-LEAD-HWP-FAIL = {device-name}-HWP2-FAIL

REM ***** Any pump running flag *****
IF {device-name}-HWP1-STS OR {device-name}-HWP2-STS THEN START {device-name}-ANY-HWP-ON ELSE STOP {device-name}-ANY-HWP-ON

REM ***** System off — stop all *****
IF NOT {device-name}-HW-SYS-ENAB THEN STOP {device-name}-LEAD-HWP-SS , STOP {device-name}-LAG-HWP-SS
