REM **** Heat Exchanger Modulating Valve
REM **** Generated by SBS Composition Engine v2

{device-name}-HX-DELTA-T = {device-name}-HX-SUPW-T - {device-name}-HX-RETW-T

REM **** Valve from PID loop — RAMP for smooth modulation ****
A = {device-name}-HX-VLV
B = loop3
IF {device-name}-HW-SYS-ENAB THEN {device-name}-HX-VLV = RAMP( ABS( A - B ) > 1 , A , B , 1.6667 ) ELSE {device-name}-HX-VLV = 0
IF ABS( A - B ) < 1 THEN {device-name}-HX-VLV = B
{device-name}-HX-VLV = LIMIT( {device-name}-HX-VLV , 0 , 100 )
