REM **** Secondary HW Pump 1 S/S program
REM **** Generated by SBS Composition Engine v2

IF SELECT( {device-name}-SHWP1 ) <> 1 THEN START {device-name}-SHWP1-OOS ELSE STOP {device-name}-SHWP1-OOS
IF {device-name}-SHWP1-OOS THEN STOP {device-name}-SHWP1 , END
IF {device-name}-SHWP1-FAIL THEN STOP {device-name}-SHWP1 , END

IF {device-name}-LEAD-SHWP < 2 THEN A = {device-name}-LEAD-SHWP-SS
IF {device-name}-LEAD-SHWP >= 2 THEN A = {device-name}-LAG-SHWP-SS

IF A AND NOT {device-name}-SHWP1-OOS THEN START {device-name}-SHWP1 ELSE STOP {device-name}-SHWP1

B = SWITCH( B , TIME-ON( {device-name}-SHWP1 ) , 0 , {device-name}-HWP-STOP-DELAY )
IF B AND NOT {device-name}-SHWP1-STS THEN START {device-name}-SHWP1-FAIL
IF {device-name}-SHWP1-STS THEN STOP {device-name}-SHWP1-FAIL
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-SHWP1-FAIL
