REM **** Heat Exchanger On/Off Valve
REM **** Generated by SBS Composition Engine v2

{device-name}-HX-DELTA-T = {device-name}-HX-SUPW-T - {device-name}-HX-RETW-T

REM **** On/off valve with SWITCH deadband ****
A = SWITCH( A , {device-name}-HX-SUPW-T , {device-name}-HX-SP + 3 , {device-name}-HX-SP )
IF {device-name}-HW-SYS-ENAB AND NOT A THEN START {device-name}-HX-VLV ELSE STOP {device-name}-HX-VLV
