REM **** Secondary Pump 2 VFD Speed
REM **** Generated by SBS Composition Engine v2

IF NOT {device-name}-SHWP2 THEN {device-name}-SHWP2-SPEED = 0 , END
IF {device-name}-SEC-HWS-T < {device-name}-HWS-T-MIN-FOR-SPD THEN {device-name}-SHWP2-SPEED = {device-name}-HWP-MIN-SPEED , END

A = {device-name}-SHWP2-SPEED
B = SLIDE( loop1 , 0 , 100 , {device-name}-HWP-MIN-SPEED , {device-name}-HWP-MAX-SPEED )
{device-name}-SHWP2-SPEED = RAMP( ABS( A - B ) > 1 , A , B , {device-name}-HWP-RAMP-RATE * 1.6667 )
IF ABS( A - B ) < 1 THEN {device-name}-SHWP2-SPEED = B
