REM **** HW Plant System Status
REM **** Generated by SBS Composition Engine v2

REM **** HW Available — system enabled and pump running and no critical alarms ****
IF {device-name}-HW-SYS-ENAB AND {device-name}-ANY-HWP-ON AND NOT {device-name}-ALARM-INHIBIT THEN START {device-name}-HW-AVAIL ELSE STOP {device-name}-HW-AVAIL
