REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — HW Pump 2 Start/Stop
REM ======================================================================

REM ***** Out of service — force off *****
IF {device-name}-HWP2-OOS THEN STOP {device-name}-HWP2-S/S , END

REM ***** Already failed — don't restart until reset *****
IF {device-name}-HWP2-FAIL THEN STOP {device-name}-HWP2-S/S , END

REM ***** Determine if pump 2 should run *****
REM  Pump 2 is lead: run on LEAD-HWP-SS
REM  Pump 2 is lag:  run on LAG-HWP-SS
IF {device-name}-LEAD-HWP = 2 THEN A = {device-name}-LEAD-HWP-SS
IF {device-name}-LEAD-HWP = 1 THEN A = {device-name}-LAG-HWP-SS

REM ***** Start/stop physical pump *****
IF A THEN START {device-name}-HWP2-S/S ELSE STOP {device-name}-HWP2-S/S

REM ***** Failure detection *****
IF TIME-ON( {device-name}-HWP2-S/S ) > 0:00:30 AND NOT {device-name}-HWP2-STS THEN START {device-name}-HWP2-FAIL
IF {device-name}-HWP2-STS THEN STOP {device-name}-HWP2-FAIL

REM ***** Reset failure on safety reset *****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-HWP2-FAIL
