REM **** Hot Water Supply Temperature Setpoint
REM **** Generated by SBS Composition Engine v2
REM **** OA reset with valve position feedback trim

REM **** OA Reset — SLIDE from OA range to HW range ****
REM **** At min OAT → max HW temp, at max OAT → min HW temp ****
{device-name}-HHW-OA-RESET = SLIDE( {device-name}-NET-OAT , {device-name}-CFG-RESET-OA-MIN , {device-name}-CFG-RESET-OA-MAX , {device-name}-CFG-RESET-HW-MAX , {device-name}-CFG-RESET-HW-MIN )

REM **** Valve position feedback trim ****
REM **** SLIDE avg valve pos (0-100) to offset range (-20 to +20) ****
{device-name}-HHW-HWV-OFFSET = SLIDE( {device-name}-NET-HWV-POS-AVG , 0 , 100 , -20 , 20 )

REM **** Active setpoint = OA reset + valve offset ****
{device-name}-ACT-HWS-TEMP-SP = {device-name}-HHW-OA-RESET + {device-name}-HHW-HWV-OFFSET

REM **** Clamp to configured min/max ****
{device-name}-ACT-HWS-TEMP-SP = LIMIT( {device-name}-ACT-HWS-TEMP-SP , {device-name}-CFG-RESET-HW-MIN , {device-name}-CFG-RESET-HW-MAX )
