REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Makeup Water Flow Monitoring
REM ======================================================================

REM ***** Totalize flow (gallons) *****
{device-name}-MAKEUP-WTR-TTL = {device-name}-MAKEUP-WTR-TTL + {device-name}-MAKEUP-WTR-FLOW * INTERVAL / 60

REM ***** High flow alarm *****
IF {device-name}-MAKEUP-WTR-FLOW > {device-name}-MAKEUP-WTR-HI-SP THEN START {device-name}-MAKEUP-WTR-ALARM ELSE STOP {device-name}-MAKEUP-WTR-ALARM

REM ***** Reset totalizer on command *****
IF {device-name}-MAKEUP-WTR-RESET THEN {device-name}-MAKEUP-WTR-TTL = 0 , STOP {device-name}-MAKEUP-WTR-RESET
