REM **** Secondary HW Pump 2 S/S program
REM **** Generated by SBS Composition Engine v2

IF SELECT( {device-name}-SHWP2-S/S ) <> 1 THEN START {device-name}-SHWP2-OOS ELSE STOP {device-name}-SHWP2-OOS
IF {device-name}-SHWP2-OOS THEN STOP {device-name}-SHWP2-S/S , END
IF {device-name}-SHWP2-FAIL THEN STOP {device-name}-SHWP2-S/S , END

IF {device-name}-LEAD-SHWP >= 2 THEN A = {device-name}-LEAD-SHWP-SS
IF {device-name}-LEAD-SHWP < 2 THEN A = {device-name}-LAG-SHWP-SS

IF A AND NOT {device-name}-SHWP2-OOS THEN START {device-name}-SHWP2-S/S ELSE STOP {device-name}-SHWP2-S/S

B = SWITCH( B , TIME-ON( {device-name}-SHWP2-S/S ) , 0 , {device-name}-HWP-STOP-DELAY )
IF B AND NOT {device-name}-SHWP2-STS THEN START {device-name}-SHWP2-FAIL
IF {device-name}-SHWP2-STS THEN STOP {device-name}-SHWP2-FAIL
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-SHWP2-FAIL
