REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Mixing Valve Control
REM ======================================================================

REM ***** Setpoint tracks active HWS temp setpoint *****
{device-name}-HWV-PID-SP = {device-name}-ACT-HWS-TEMP-SP

REM ***** Valve position from PID loop *****
A = {device-name}-HW-MIXING-VLV
B = loop2
IF {device-name}-HW-SYS-ENAB THEN {device-name}-HW-MIXING-VLV = RAMP( ABS( A - B ) > 1 , A , B , 3.33 ) ELSE {device-name}-HW-MIXING-VLV = 0
IF ABS( A - B ) < 1 THEN {device-name}-HW-MIXING-VLV = B
