10 REM ========================================
20 REM  {device-name} Primary Pump Control
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 REM Primary pumps run when any boiler is active
60 IF {device-name}-HW-SYS-ENAB = ON THEN {device-name}-PHWP1 = ON ELSE {device-name}-PHWP1 = OFF
