REM **** Boiler Lead Rotation Schedule
REM **** Generated by SBS Composition Engine v2

REM **** Lead boiler from rotation schedule ****
{device-name}-LEAD-BLR = {device-name}-BLR-LEAD-SCHED
{device-name}-LEAD-BLR = LIMIT( {device-name}-LEAD-BLR , 1 , 2 )
