REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Boiler Lead/Lag Rotation
REM  Schedule sets normal lead. Failure forces swap.
REM  
REM  Points:
REM    LEAD-BLR         AV  — current lead boiler number
REM    LEAD-BLR-SS      BV  — lead boiler run command  
REM    LAG-BLR-SS       BV  — lag boiler run command
REM    LEAD-BLR-FAIL    BV  — lead boiler has failed
REM    BLR{N}-FAIL      BV  — individual boiler failure
REM ======================================================================

REM ***** Read lead boiler from rotation schedule *****
{device-name}-LEAD-BLR = {device-name}-BLR-LEAD-SCHED

REM ***** Swap if scheduled lead has alarm *****
IF {device-name}-LEAD-BLR = 1 AND {device-name}-BLR1-FAIL THEN {device-name}-LEAD-BLR = 2
IF {device-name}-LEAD-BLR = 2 AND {device-name}-BLR2-FAIL THEN {device-name}-LEAD-BLR = 1

REM ***** Lead boiler failure flag *****
IF {device-name}-LEAD-BLR = 1 THEN {device-name}-LEAD-BLR-FAIL = {device-name}-BLR1-FAIL
IF {device-name}-LEAD-BLR = 2 THEN {device-name}-LEAD-BLR-FAIL = {device-name}-BLR2-FAIL
