REM **** HW Pump 2 S/S program
REM **** Generated by SBS Composition Engine v2
REM **** Pump starts when system enabled and pump is in lead
REM **** or system enabled and lead pump has failed

REM **** Determine out of service from output mode ****
IF SELECT( {device-name}-HWP2-S/S ) <> 1 THEN START {device-name}-HWP2-OOS ELSE STOP {device-name}-HWP2-OOS

REM **** Check out of service ****
IF {device-name}-HWP2-OOS THEN STOP {device-name}-HWP2-S/S , END

REM **** Check pump failure — do not restart until reset ****
IF {device-name}-HWP2-FAIL THEN STOP {device-name}-HWP2-S/S , END

REM **** Determine if pump 2 is lead or lag ****
IF {device-name}-LEAD-HWP >= 2 THEN A = {device-name}-LEAD-HWP-SS
IF {device-name}-LEAD-HWP < 2 THEN A = {device-name}-LAG-HWP-SS

REM **** Start/stop pump ****
IF A AND NOT {device-name}-HWP2-OOS THEN START {device-name}-HWP2-S/S ELSE STOP {device-name}-HWP2-S/S

REM **** Failure detection — SWITCH deadband on proof timing ****
B = SWITCH( B , TIME-ON( {device-name}-HWP2-S/S ) , 0 , {device-name}-HWP-STOP-DELAY )
IF B AND NOT {device-name}-HWP2-STS THEN START {device-name}-HWP2-FAIL
IF {device-name}-HWP2-STS THEN STOP {device-name}-HWP2-FAIL

REM **** Reset failure on safety reset ****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-HWP2-FAIL
