10 REM ========================================
20 REM  {device-name} HW Plant Configuration
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 REM Read network weather data
60 {device-name}-NET-OAT = OAT(BACNET)
70 {device-name}-NET-OAH = OAH(BACNET)
80 REM Calculate enthalpy
90 {device-name}-NET-OA-ERH = ENTHALPY({device-name}-NET-OAT, {device-name}-NET-OAH)
100 REM System enable logic
110 IF {device-name}-NET-OAT < {device-name}-CFG-HHW-OA-ENAB-SP THEN {device-name}-HW-SYS-ENAB = ON
120 IF {device-name}-NET-OAT > {device-name}-CFG-HHW-OA-ENAB-SP + 5 THEN {device-name}-HW-SYS-ENAB = OFF
