REM **** HW Pump VFD Speed Control
REM **** Generated by SBS Composition Engine v2
REM **** Secondary pump speed from DP PID loop

REM **** Average DP from sensors ****
{device-name}-AVG-DP = ( {device-name}-HW-PRESS1 + {device-name}-HW-PRESS2 ) / 2

REM **** Determine if pump is commanded on ****
IF NOT {device-name}-ANY-HWP-ON THEN {device-name}-HWP1-SPEED = 0 , {device-name}-HWP2-SPEED = 0 , END

REM **** Scale DP loop output to speed range ****
A = {device-name}-HWP1-SPEED
B = SLIDE( loop1 , 0 , 100 , {device-name}-HWP-MIN-SPEED , {device-name}-HWP-MAX-SPEED )

REM **** Ramp pump 1 speed ****
IF {device-name}-HWP1-STS THEN {device-name}-HWP1-SPEED = RAMP( ABS( A - B ) > 1 , A , B , 3.33 ) ELSE {device-name}-HWP1-SPEED = 0
IF {device-name}-HWP1-STS AND ABS( A - B ) < 1 THEN {device-name}-HWP1-SPEED = B

REM **** Pump 2 speed — tracks same target when running ****
C = {device-name}-HWP2-SPEED
IF {device-name}-HWP2-STS THEN {device-name}-HWP2-SPEED = RAMP( ABS( C - B ) > 1 , C , B , 3.33 ) ELSE {device-name}-HWP2-SPEED = 0
IF {device-name}-HWP2-STS AND ABS( C - B ) < 1 THEN {device-name}-HWP2-SPEED = B
