REM **** HW Pump 1 S/S program (single pump — no lead/lag)
REM **** Generated by SBS Composition Engine v2
REM **** Pump starts when system enabled, stops when disabled

REM **** Check out of service from output mode ****
IF SELECT( {device-name}-HWP1-S/S ) <> 1 THEN START {device-name}-HWP1-OOS ELSE STOP {device-name}-HWP1-OOS
IF {device-name}-HWP1-OOS THEN STOP {device-name}-HWP1-S/S , END

REM **** Check pump failure — do not restart until reset ****
IF {device-name}-HWP1-FAIL THEN STOP {device-name}-HWP1-S/S , END

REM **** Start/stop on system enable ****
IF {device-name}-HW-SYS-ENAB AND NOT {device-name}-HWP1-FAIL THEN START {device-name}-HWP1-S/S ELSE STOP {device-name}-HWP1-S/S

REM **** Failure detection — SWITCH deadband on proof timing ****
B = SWITCH( B , TIME-ON( {device-name}-HWP1-S/S ) , 0 , {device-name}-HWP-STOP-DELAY )
IF B AND NOT {device-name}-HWP1-STS THEN START {device-name}-HWP1-FAIL
IF {device-name}-HWP1-STS THEN STOP {device-name}-HWP1-FAIL

REM **** Any pump running ****
IF {device-name}-HWP1-STS THEN START {device-name}-ANY-HWP-ON ELSE STOP {device-name}-ANY-HWP-ON

REM **** Reset failure on safety reset ****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-HWP1-FAIL
