10 REM ========================================
20 REM  {device-name} HX 1/3 + 2/3 Valve Seq
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 {device-name}-HX-DELTA-T = {device-name}-HX-SUPW-T - {device-name}-HX-RETW-T
60 PID-OUT = LOOP({device-name}-HX-VLV-LOOP)
70 REM Stage 1: 1/3 valve opens 0-100%
80 IF PID-OUT <= 50 THEN {device-name}-HX-VLV-1/3-POS = PID-OUT * 2 : {device-name}-HX-VLV-2/3-POS = 0
90 REM Stage 2: 2/3 opens, 1/3 closes
100 IF PID-OUT > 50 AND PID-OUT <= 75 THEN {device-name}-HX-VLV-1/3-POS = 100 - (PID-OUT - 50) * 4 : {device-name}-HX-VLV-2/3-POS = (PID-OUT - 50) * 4
110 REM Stage 3: 2/3 full, 1/3 reopens for remainder
120 IF PID-OUT > 75 THEN {device-name}-HX-VLV-2/3-POS = 100 : {device-name}-HX-VLV-1/3-POS = (PID-OUT - 75) * 4
