10 REM ========================================
20 REM  {device-name} HX Valve On/Off
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 {device-name}-HX-DELTA-T = {device-name}-HX-SUPW-T - {device-name}-HX-RETW-T
60 IF {device-name}-HX-SUPW-T < {device-name}-HX-SP THEN {device-name}-HX-VLV = ON ELSE {device-name}-HX-VLV = OFF
