REM **** Secondary HW Pump 1 S/S program
REM **** Generated by SBS Composition Engine v2
REM **** Pump starts when system is enabled and pump is in lead
REM **** or system is enabled and lead pump has failed

REM **** Check out of service ****
IF {device-name}-SHWP1-OOS THEN STOP {device-name}-SHWP1 , END

REM **** Check pump failure ****
IF {device-name}-SHWP1-FAIL THEN STOP {device-name}-SHWP1 , END

REM **** Determine if pump 1 is lead or lag ****
IF {device-name}-LEAD-SHWP < 2 THEN A = {device-name}-LEAD-SHWP-SS
IF {device-name}-LEAD-SHWP >= 2 THEN A = {device-name}-LAG-SHWP-SS

REM **** Start/stop pump ****
IF A AND NOT {device-name}-SHWP1-OOS THEN START {device-name}-SHWP1 ELSE STOP {device-name}-SHWP1

REM **** Failure detection ****
IF TIME-ON( {device-name}-SHWP1 ) > 0:00:30 AND NOT {device-name}-SHWP1-STS THEN START {device-name}-SHWP1-FAIL
IF {device-name}-SHWP1-STS THEN STOP {device-name}-SHWP1-FAIL

REM **** Reset failure ****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-SHWP1-FAIL
