REM **** Combustion Air Damper Interlock
REM **** Generated by SBS Composition Engine v2
REM **** Alarm if any boiler firing and damper not confirmed open

STOP {device-name}-COMB-DMPR-ALARM
IF {device-name}-BLR1-S/S AND NOT {device-name}-BLR1-COMB-DMPR-STS THEN START {device-name}-COMB-DMPR-ALARM
IF {device-name}-BLR2-S/S AND NOT {device-name}-BLR2-COMB-DMPR-STS THEN START {device-name}-COMB-DMPR-ALARM
