10 REM ========================================
20 REM  {device-name} HW Pump Control
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 REM Start lead pump when system enabled
60 IF {device-name}-HW-SYS-ENAB = ON THEN {device-name}-LEAD-HWP-SS = ON
70 IF {device-name}-HW-SYS-ENAB = OFF THEN {device-name}-LEAD-HWP-SS = OFF
80 REM Pump failure detection (30 sec timeout)
90 IF {device-name}-HWP1-S/S = ON AND {device-name}-HWP1-STS = OFF AFTER 30 THEN {device-name}-HWP1-FAIL = ON
