REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Primary Pump Control
REM  Primary pumps run when any boiler is active
REM ======================================================================

REM ***** Primary pumps follow system enable *****
IF {device-name}-HW-SYS-ENAB THEN START {device-name}-PHWP1 ELSE STOP {device-name}-PHWP1

REM ***** Primary pump 1 failure detection *****
IF {device-name}-PHWP1 AND NOT {device-name}-PHWP1-STS THEN A = A + INTERVAL ELSE A = 0
IF A > 30 THEN START {device-name}-PHWP1-FAIL
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-PHWP1-FAIL , A = 0

REM ***** If pump 1 fails, start pump 2 *****
IF {device-name}-PHWP1-FAIL THEN START {device-name}-PHWP2 ELSE STOP {device-name}-PHWP2

REM ***** Primary pump 2 failure detection *****
IF {device-name}-PHWP2 AND NOT {device-name}-PHWP2-STS THEN B = B + INTERVAL ELSE B = 0
IF B > 30 THEN START {device-name}-PHWP2-FAIL
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-PHWP2-FAIL , B = 0
