REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Secondary Pump Control
REM  Lead secondary pump starts on system enable. Standby on failure.
REM ======================================================================

REM ***** Start lead secondary pump *****
IF {device-name}-HW-SYS-ENAB AND NOT {device-name}-SHWP1-FAIL THEN START {device-name}-SHWP1 ELSE STOP {device-name}-SHWP1

REM ***** Secondary pump 1 failure *****
IF TIME-ON( {device-name}-SHWP1 ) > 0:00:30 AND NOT {device-name}-SHWP1-STS THEN START {device-name}-SHWP1-FAIL
IF {device-name}-SHWP1-STS THEN STOP {device-name}-SHWP1-FAIL

REM ***** Standby: pump 2 starts on pump 1 failure *****
IF {device-name}-HW-SYS-ENAB AND {device-name}-SHWP1-FAIL AND NOT {device-name}-SHWP2-FAIL THEN START {device-name}-SHWP2 ELSE STOP {device-name}-SHWP2

REM ***** Secondary pump 2 failure *****
IF TIME-ON( {device-name}-SHWP2 ) > 0:00:30 AND NOT {device-name}-SHWP2-STS THEN START {device-name}-SHWP2-FAIL
IF {device-name}-SHWP2-STS THEN STOP {device-name}-SHWP2-FAIL

REM ***** Reset failures *****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-SHWP1-FAIL , STOP {device-name}-SHWP2-FAIL
