10 REM ========================================
20 REM  {device-name} Boiler Lead Rotation
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 REM Lead boiler determined by schedule
60 {device-name}-LEAD-BLR = SCHEDULE({device-name}-BLR-LEAD-SCHED)
