REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Cascade Boiler Control
REM  Enable boilers when system enabled AND pump proven
REM ======================================================================

REM ***** Enable boilers: system enabled AND at least one pump running *****
IF {device-name}-HW-SYS-ENAB AND {device-name}-ANY-HWP-ON THEN START {device-name}-BLRS-ENABLE ELSE STOP {device-name}-BLRS-ENABLE

REM ***** Write setpoint to boiler master *****
{device-name}-BLRS-SPT = {device-name}-ACT-HWS-TEMP-SP

REM ***** Boiler availability — all boilers no alarm *****
START {device-name}-BLR-AVAIL

REM ***** Monitor boiler 1 alarm *****
IF {device-name}-BLR1-ALARM THEN START {device-name}-BLR1-ALARM-STS , STOP {device-name}-BLR-AVAIL ELSE STOP {device-name}-BLR1-ALARM-STS

REM ***** Monitor boiler 2 alarm *****
IF {device-name}-BLR2-ALARM THEN START {device-name}-BLR2-ALARM-STS , STOP {device-name}-BLR-AVAIL ELSE STOP {device-name}-BLR2-ALARM-STS

REM ***** System off — disable boilers *****
IF NOT {device-name}-HW-SYS-ENAB THEN STOP {device-name}-BLRS-ENABLE
