REM **** 3-Way Hot Water Mixing Valve Control
REM **** Generated by SBS Composition Engine v2
REM **** Reference: Lordstown PRG6 (S. Boyce) — LIMIT(50, 100)

{device-name}-HWV-PID-SP = {device-name}-ACT-HWS-TEMP-SP

REM **** Modulate mixing valve from PID loop ****
A = {device-name}-HW-MIXING-VLV
B = loop2
IF {device-name}-HW-SYS-ENAB THEN {device-name}-HW-MIXING-VLV = RAMP( ABS( A - B ) > 1 , A , B , 1.6667 ) ELSE {device-name}-HW-MIXING-VLV = 0
IF ABS( A - B ) < 1 THEN {device-name}-HW-MIXING-VLV = B

REM **** Clamp valve — 50% minimum prevents thermal shock ****
{device-name}-HW-MIXING-VLV = LIMIT( {device-name}-HW-MIXING-VLV , 50 , 100 )
