REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Direct Boiler Staging Control
REM  Staging: deviation-based with SWITCH deadband
REM  Lead/lag mapped to physical boilers
REM ======================================================================

REM ***** Calculate deviation from setpoint *****
DEV = {device-name}-ACT-HWS-TEMP-SP - {device-name}-HWS-T
{device-name}-LEAD-BLR-DEV = DEV
{device-name}-TOTAL-BLRS-REQUESTED = 0

REM ***** System off — stop everything *****
IF NOT {device-name}-HW-SYS-ENAB THEN STOP {device-name}-BLR1-S/S , STOP {device-name}-BLR2-S/S , STOP {device-name}-LEAD-BLR-SS , STOP {device-name}-LAG-BLR-SS , END

REM ***** Lead boiler staging — start on +5°F dev, stop on -5°F *****
A = SWITCH( A , DEV , -5 , 5 )
IF A THEN START {device-name}-LEAD-BLR-SS ELSE STOP {device-name}-LEAD-BLR-SS
IF {device-name}-LEAD-BLR-SS THEN {device-name}-TOTAL-BLRS-REQUESTED = {device-name}-TOTAL-BLRS-REQUESTED + 1

REM ***** Lag boiler staging — start on +15°F dev with lead running *****
B = SWITCH( B , DEV , 5 , 15 )
IF B AND {device-name}-LEAD-BLR-SS THEN START {device-name}-LAG-BLR-SS ELSE STOP {device-name}-LAG-BLR-SS
IF {device-name}-LAG-BLR-SS THEN {device-name}-TOTAL-BLRS-REQUESTED = {device-name}-TOTAL-BLRS-REQUESTED + 1

REM ***** Map lead/lag to physical boilers *****
IF {device-name}-LEAD-BLR = 1 THEN {device-name}-BLR1-SS = {device-name}-LEAD-BLR-SS , {device-name}-BLR2-SS = {device-name}-LAG-BLR-SS
IF {device-name}-LEAD-BLR = 2 THEN {device-name}-BLR2-SS = {device-name}-LEAD-BLR-SS , {device-name}-BLR1-SS = {device-name}-LAG-BLR-SS

REM ***** Write start/stop outputs — interlock with alarms *****
IF {device-name}-BLR1-SS AND NOT {device-name}-BLR1-ALARM THEN START {device-name}-BLR1-S/S ELSE STOP {device-name}-BLR1-S/S
IF {device-name}-BLR2-SS AND NOT {device-name}-BLR2-ALARM THEN START {device-name}-BLR2-S/S ELSE STOP {device-name}-BLR2-S/S

REM ***** Failure detection — alarm while commanded on *****
IF {device-name}-BLR1-ALARM AND {device-name}-BLR1-SS THEN START {device-name}-BLR1-FAIL
IF NOT {device-name}-BLR1-ALARM THEN STOP {device-name}-BLR1-FAIL
IF {device-name}-BLR2-ALARM AND {device-name}-BLR2-SS THEN START {device-name}-BLR2-FAIL
IF NOT {device-name}-BLR2-ALARM THEN STOP {device-name}-BLR2-FAIL

REM ***** Lead boiler failure flag *****
IF {device-name}-LEAD-BLR = 1 THEN {device-name}-LEAD-BLR-FAIL = {device-name}-BLR1-FAIL
IF {device-name}-LEAD-BLR = 2 THEN {device-name}-LEAD-BLR-FAIL = {device-name}-BLR2-FAIL

REM ***** Reset failures *****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-BLR1-FAIL , STOP {device-name}-BLR2-FAIL , STOP {device-name}-LEAD-BLR-FAIL
