10 REM ========================================
20 REM  {device-name} Secondary Pump Control
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 REM Secondary pumps distribute to building
60 IF {device-name}-HW-SYS-ENAB = ON THEN {device-name}-SHWP1 = ON ELSE {device-name}-SHWP1 = OFF
