REM **** Boiler Isolation Valve Control
REM **** Generated by SBS Composition Engine v2
REM **** Open valve BEFORE boiler enable, close AFTER disable with delay

REM **** Boiler 1 isolation valve — open when boiler commanded ****
IF {device-name}-BLR1-SS OR {device-name}-BLR1-S/S THEN START {device-name}-BLR1-ISO-VLV
IF NOT {device-name}-BLR1-SS AND NOT {device-name}-BLR1-S/S AND TIME-OFF( {device-name}-BLR1-S/S ) > {device-name}-ISO-VLV-OPEN-DLY THEN STOP {device-name}-BLR1-ISO-VLV

REM **** Boiler 2 isolation valve ****
IF {device-name}-BLR2-SS OR {device-name}-BLR2-S/S THEN START {device-name}-BLR2-ISO-VLV
IF NOT {device-name}-BLR2-SS AND NOT {device-name}-BLR2-S/S AND TIME-OFF( {device-name}-BLR2-S/S ) > {device-name}-ISO-VLV-OPEN-DLY THEN STOP {device-name}-BLR2-ISO-VLV
