10 REM ========================================
20 REM  {device-name} Secondary Pump Speed
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 SPEED = LOOP({device-name}-HW-DP-LOOP)
60 IF SPEED < {device-name}-HWP-MIN-SPEED THEN SPEED = {device-name}-HWP-MIN-SPEED
70 IF SPEED > {device-name}-HWP-MAX-SPEED THEN SPEED = {device-name}-HWP-MAX-SPEED
80 {device-name}-SHWP1-SPEED = SPEED
