REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — HW Pump 1 Start/Stop
REM  
REM  This pump runs when:
REM    - It is the lead pump (LEAD-HWP=1) AND LEAD-HWP-SS is on
REM    - OR it is the lag pump (LEAD-HWP=2) AND LAG-HWP-SS is on
REM  Stops when: out of service, failed, or not commanded
REM ======================================================================

REM ***** Out of service — force off *****
IF {device-name}-HWP1-OOS THEN STOP {device-name}-HWP1-S/S , END

REM ***** Already failed — don't restart until reset *****
IF {device-name}-HWP1-FAIL THEN STOP {device-name}-HWP1-S/S , END

REM ***** Determine if pump 1 should run *****
REM  Pump 1 is lead: run on LEAD-HWP-SS
REM  Pump 1 is lag:  run on LAG-HWP-SS
IF {device-name}-LEAD-HWP = 1 THEN A = {device-name}-LEAD-HWP-SS
IF {device-name}-LEAD-HWP = 2 THEN A = {device-name}-LAG-HWP-SS

REM ***** Start/stop physical pump *****
IF A THEN START {device-name}-HWP1-S/S ELSE STOP {device-name}-HWP1-S/S

REM ***** Failure detection — commanded on, no status after 30 seconds *****
IF TIME-ON( {device-name}-HWP1-S/S ) > 0:00:30 AND NOT {device-name}-HWP1-STS THEN START {device-name}-HWP1-FAIL
IF {device-name}-HWP1-STS THEN STOP {device-name}-HWP1-FAIL

REM ***** Reset failure on safety reset *****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-HWP1-FAIL
