REM **** Lead/Lag Program
REM **** Generated by SBS Composition Engine v2
REM **** Handles rotation for both HW pumps and boilers
REM **** Rotation occurs weekly at midnight per schedule

REM **** Calculate pump runtimes from BACnet properties ****
A = TIME-ON( {device-name}-HWP1-STS ) / 3600
B = TIME-ON( {device-name}-HWP2-STS ) / 3600

REM **** Read lead pump from rotation schedule ****
{device-name}-LEAD-HWP = {device-name}-HWP-LEAD-SCHED

REM **** Force swap if scheduled lead pump has failed or is OOS ****
IF {device-name}-LEAD-HWP < 2 AND {device-name}-HWP1-FAIL THEN {device-name}-LEAD-HWP = 2
IF {device-name}-LEAD-HWP < 2 AND {device-name}-HWP1-OOS THEN {device-name}-LEAD-HWP = 2
IF {device-name}-LEAD-HWP >= 2 AND {device-name}-HWP2-FAIL THEN {device-name}-LEAD-HWP = 1
IF {device-name}-LEAD-HWP >= 2 AND {device-name}-HWP2-OOS THEN {device-name}-LEAD-HWP = 1

REM **** Clamp lead pump to valid range ****
{device-name}-LEAD-HWP = LIMIT( {device-name}-LEAD-HWP , 1 , 2 )

REM **** Set lead pump failure flag based on current lead ****
IF {device-name}-LEAD-HWP < 2 THEN {device-name}-LEAD-HWP-FAIL = {device-name}-HWP1-FAIL
IF {device-name}-LEAD-HWP >= 2 THEN {device-name}-LEAD-HWP-FAIL = {device-name}-HWP2-FAIL

REM **** System off — stop all pump commands ****
IF NOT {device-name}-HW-SYS-ENAB THEN STOP {device-name}-LEAD-HWP-SS , STOP {device-name}-LAG-HWP-SS , END

REM **** System on — start lead pump ****
START {device-name}-LEAD-HWP-SS

REM **** Start lag pump ONLY if lead has failed ****
IF {device-name}-LEAD-HWP-FAIL THEN START {device-name}-LAG-HWP-SS ELSE STOP {device-name}-LAG-HWP-SS

REM **** Any pump running — from actual status feedback ****
IF {device-name}-HWP1-STS OR {device-name}-HWP2-STS THEN START {device-name}-ANY-HWP-ON ELSE STOP {device-name}-ANY-HWP-ON
