REM **** Secondary Pump VFD Speed
REM **** Generated by SBS Composition Engine v2
REM **** DP PID loop → SLIDE → RAMP → speed output

REM **** Scale DP loop output to speed range ****
A = {device-name}-SHWP1-SPEED
B = SLIDE( loop1 , 0 , 100 , {device-name}-HWP-MIN-SPEED , {device-name}-HWP-MAX-SPEED )

REM **** Ramp pump 1 speed ****
IF {device-name}-SHWP1-STS THEN {device-name}-SHWP1-SPEED = RAMP( ABS( A - B ) > 1 , A , B , 3.33 ) ELSE {device-name}-SHWP1-SPEED = 0
IF {device-name}-SHWP1-STS AND ABS( A - B ) < 1 THEN {device-name}-SHWP1-SPEED = B

REM **** Pump 2 tracks same speed ****
C = {device-name}-SHWP2-SPEED
IF {device-name}-SHWP2-STS THEN {device-name}-SHWP2-SPEED = RAMP( ABS( C - B ) > 1 , C , B , 3.33 ) ELSE {device-name}-SHWP2-SPEED = 0
IF {device-name}-SHWP2-STS AND ABS( C - B ) < 1 THEN {device-name}-SHWP2-SPEED = B
