REM **** Heat Exchanger 1/3 + 2/3 Floating Valve Sequence
REM **** Generated by SBS Composition Engine v2
REM **** Stage 1: 1/3 opens 0-100%
REM **** Stage 2: 2/3 opens, 1/3 closes
REM **** Stage 3: 2/3 full, 1/3 reopens

{device-name}-HX-DELTA-T = {device-name}-HX-SUPW-T - {device-name}-HX-RETW-T

IF NOT {device-name}-HW-SYS-ENAB THEN {device-name}-HX-VLV-1/3 = 0 , {device-name}-HX-VLV-2/3 = 0 , END

REM **** PID loop output 0-100 ****
P = loop3

REM **** Stage 1: 1/3 valve (PID 0-33%) ****
IF P <= 33 THEN {device-name}-HX-VLV-1/3 = SLIDE( P , 0 , 33 , 0 , 100 ) , {device-name}-HX-VLV-2/3 = 0 , END

REM **** Stage 2: 2/3 opens, 1/3 closes (PID 33-66%) ****
IF P <= 66 THEN {device-name}-HX-VLV-1/3 = SLIDE( P , 33 , 66 , 100 , 0 ) , {device-name}-HX-VLV-2/3 = SLIDE( P , 33 , 66 , 0 , 100 ) , END

REM **** Stage 3: 2/3 full, 1/3 reopens (PID 66-100%) ****
{device-name}-HX-VLV-2/3 = 100
{device-name}-HX-VLV-1/3 = SLIDE( P , 66 , 100 , 0 , 100 )
