10 REM ========================================
20 REM  {device-name} Pump VFD Speed Control
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 REM Average DP sensors
60 {device-name}-AVG-DP = ({device-name}-HW-PRESS1 + {device-name}-HW-PRESS2) / 2
70 REM Speed from DP PID loop output
80 SPEED = LOOP({device-name}-HW-DP-LOOP)
90 IF SPEED < {device-name}-HWP-MIN-SPEED THEN SPEED = {device-name}-HWP-MIN-SPEED
100 IF SPEED > {device-name}-HWP-MAX-SPEED THEN SPEED = {device-name}-HWP-MAX-SPEED
110 {device-name}-HWP1-SPEED = SPEED
