REM **** Boiler Firing Rate Control
REM **** Generated by SBS Composition Engine v2
REM **** Per-boiler fire rate with low/hi limits and voltage conversion

REM **** Boiler supply temp setpoint from OA reset ****
{device-name}-BLR-SUPPLY-STPNT = {device-name}-ACT-HWS-TEMP-SP

REM **** Boiler #1 deviation ****
{device-name}-B1-DEV = {device-name}-BLR-SUPPLY-STPNT - {device-name}-HWS-T

REM **** Boiler #1 Enable/Disable from start/stop temps ****
{device-name}-BLR1-SS = SWITCH( {device-name}-BLR1-SS , {device-name}-B1-DEV , {device-name}-B1-STOP , {device-name}-B1-START )

REM **** Boiler #1 Fire Rate — SLIDE deviation to fire range ****
IF NOT {device-name}-BLR1-S/S THEN {device-name}-BLR1-MOD = 0 , END
C = SLIDE( {device-name}-B1-DEV , 0 , 20 , {device-name}-B1-LOW-FIRE , {device-name}-B1-HI-FIRE )
{device-name}-BLR1-MOD = C * {device-name}-B1-VOLT-BURN%-CNV / 100
{device-name}-BLR1-MOD = LIMIT( {device-name}-BLR1-MOD , 0 , 10 )

REM **** Boiler #2 deviation ****
{device-name}-B2-DEV = {device-name}-BLR-SUPPLY-STPNT - {device-name}-HWS-T

REM **** Boiler #2 Enable/Disable ****
{device-name}-BLR2-SS = SWITCH( {device-name}-BLR2-SS , {device-name}-B2-DEV , {device-name}-B2-STOP , {device-name}-B2-START )

REM **** Boiler #2 Fire Rate ****
IF NOT {device-name}-BLR2-S/S THEN {device-name}-BLR2-MOD = 0 , END
D = SLIDE( {device-name}-B2-DEV , 0 , 20 , {device-name}-B2-LOW-FIRE , {device-name}-B2-HI-FIRE )
{device-name}-BLR2-MOD = D * {device-name}-B2-VOLT-BURN%-CNV / 100
{device-name}-BLR2-MOD = LIMIT( {device-name}-BLR2-MOD , 0 , 10 )
