10 REM ========================================
20 REM  {device-name} Network Data Reads
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 REM Read zone data from each AHU via BACnet
60 REM Aggregate heating requests
70 {device-name}-TOTAL-HTG-REQS = 0
80 REM Per-AHU reads configured in AHU-CFG programs
