10 REM ========================================
20 REM  {device-name} Heat Exchanger Valve
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 {device-name}-HX-DELTA-T = {device-name}-HX-SUPW-T - {device-name}-HX-RETW-T
60 {device-name}-HX-VLV = LOOP({device-name}-HX-VLV-LOOP)
