10 REM ========================================
20 REM  {device-name} Isolation Valve Control
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 REM Open isolation valve before boiler enable
60 REM Close after boiler disable with delay
