10 REM ========================================
20 REM  {device-name} Makeup Water Monitor
30 REM  Generated by SBS Composition Engine v2
40 REM ========================================
50 REM Totalize flow
60 {device-name}-MAKEUP-WTR-TTL = {device-name}-MAKEUP-WTR-TTL + {device-name}-MAKEUP-WTR-FLOW * INTERVAL / 60
70 REM Alarm on high flow
80 IF {device-name}-MAKEUP-WTR-FLOW > {device-name}-MAKEUP-WTR-HI-SP THEN {device-name}-MAKEUP-WTR-ALARM = ON
90 REM Reset totalizer
100 IF {device-name}-MAKEUP-WTR-RESET = ON THEN {device-name}-MAKEUP-WTR-TTL = 0 : {device-name}-MAKEUP-WTR-RESET = OFF
