REM ======================================================================
REM  Generated by SBS Composition Engine v2
REM  {device-name} — Boiler Lead/Lag Rotation
REM ======================================================================

REM ***** Lead boiler from schedule *****
{device-name}-LEAD-BLR = {device-name}-BLR-LEAD-SCHED

REM ***** If lead fails, force swap *****
IF {device-name}-LEAD-BLR-FAIL AND {device-name}-LEAD-BLR = 1 THEN {device-name}-LEAD-BLR = 2
IF {device-name}-LEAD-BLR-FAIL AND {device-name}-LEAD-BLR = 2 THEN {device-name}-LEAD-BLR = 1
