"""
SBS Controls — Base Module: Exhaust Fan (Simple On/Off with Status)

Simple exhaust fan with start/stop command and current-sensing status.
Schedule-based operation via occupancy command.

    - EF-CMD (DO) — exhaust fan command
    - EF-STS (DI) — exhaust fan status (current switch)
    - Schedule-based operation via OCC-CMD

Point Naming:
    All points use {device-name} prefix per SBS standard.
    Example: {device-name}-EF-CMD -> EF-1-EF-CMD when composed.
"""

from app.modules import register_base

module = {
    "id": "base_exhaust_fan",
    "name": "Exhaust Fan - Simple On/Off (Base)",
    "feature": "BASE",
    "category": "core",
    "requires": [],
    "conflicts": [],
    "exec_order": 10,

    "objects": {
        "AI": [],
        "AO": [],
        "AV": [],
        "BI": [
            {
                "name": "{device-name}-EF-STS",
                "desc": "Exhaust Fan Status (current switch)",
                "states": {0: "Off", 1: "On"},
            },
        ],
        "BO": [
            {
                "name": "{device-name}-EF-CMD",
                "desc": "Exhaust Fan Start/Stop Command",
                "states": {0: "Stop", 1: "Start"},
                "default": 0,
            },
        ],
        "BV": [
            {
                "name": "{device-name}-OCC-CMD",
                "desc": "Occupancy Command (from schedule or BAS)",
                "states": {0: "Unoccupied", 1: "Occupied"},
                "default": 0,
            },
            {
                "name": "{device-name}-HAND-CMD",
                "desc": "Hand/Override Command",
                "states": {0: "Auto", 1: "Hand (Force On)"},
                "default": 0,
            },
        ],
        "MV": [],
    },

    "io_map": {
        "BI1": "{device-name}-EF-STS",
        "BO1": "{device-name}-EF-CMD",
    },

    "code": """\
REM ======================================================================
REM  {device-name} — EXHAUST FAN BASE: Schedule-Based Operation
REM  SBS Controls Division — Auto-generated by Composition Engine
REM ======================================================================

REM ── Read Inputs ──
EF_STS = BI1
OCC = BV1
HAND = BV2

REM ── Fan Command ──
IF HAND = 1 THEN
  REM Hand override — force fan on
  BO1 = 1
ELSE
  IF OCC = 1 THEN
    REM Occupied: fan on
    BO1 = 1
  ELSE
    REM Unoccupied: fan off
    BO1 = 0
  ENDIF
ENDIF

REM ── Fan Status Alarm ──
IF BO1 = 1 AND EF_STS = 0 THEN
  IF EF_FAIL_TMR = 0 THEN
    EF_FAIL_TMR = ELAPSED
  ENDIF
  IF (ELAPSED - EF_FAIL_TMR) > 30 THEN
    REM Fan failure alarm (30 second delay)
    EF_ALARM = 1
  ENDIF
ELSE
  EF_FAIL_TMR = 0
  EF_ALARM = 0
ENDIF

REM ── End of Base Module ──\
""",
}

register_base("EF", module)
