"""
SBS Controls — Base Module: Dedicated Outdoor Air System

This is the core module loaded for every DOAS equipment type.
100% outdoor air unit — no return air, no economizer in base.
Contains the fundamental points, I/O, and code:

    - Supply air temperature sensor (SAT)
    - Outside air temperature sensor (OAT)
    - Supply fan command and status (SF-CMD, SF-STS) — constant speed
    - Occupancy/mode determination (OCC-CMD, MODE)
    - Supply air temperature setpoints (SAT-SP, SAT-SP-MIN, SAT-SP-MAX)
    - Fan enable on schedule/occupancy

This is similar to AHU-CV but always 100% outdoor air, no mixed air
or return air damper in base. Heating/cooling coils are add-ons.

Point Naming:
    All points use {device-name} prefix per SBS standard.
    Example: {device-name}-SAT -> DOAS-1-SAT when composed.
"""

from app.modules import register_base

module = {
    "id": "base_doas",
    "name": "Dedicated Outdoor Air System (Base)",
    "feature": "BASE",
    "category": "core",
    "requires": [],
    "conflicts": [],
    "exec_order": 10,

    "objects": {
        "AI": [
            {
                "name": "{device-name}-SAT",
                "desc": "Supply Air Temperature",
                "units": "deg-f",
                "min": -20,
                "max": 150,
            },
            {
                "name": "{device-name}-OAT",
                "desc": "Outside Air Temperature",
                "units": "deg-f",
                "min": -40,
                "max": 130,
            },
        ],
        "AO": [],
        "AV": [
            {
                "name": "{device-name}-SAT-SP",
                "desc": "Supply Air Temperature Setpoint (Active)",
                "units": "deg-f",
                "min": 40,
                "max": 90,
                "default": 55.0,
            },
            {
                "name": "{device-name}-SAT-SP-MIN",
                "desc": "Supply Air Temp Setpoint - Minimum",
                "units": "deg-f",
                "min": 40,
                "max": 65,
                "default": 50.0,
            },
            {
                "name": "{device-name}-SAT-SP-MAX",
                "desc": "Supply Air Temp Setpoint - Maximum",
                "units": "deg-f",
                "min": 55,
                "max": 90,
                "default": 65.0,
            },
        ],
        "BI": [
            {
                "name": "{device-name}-SF-STS",
                "desc": "Supply Fan Status (current switch)",
                "states": {0: "Off", 1: "On"},
            },
        ],
        "BO": [
            {
                "name": "{device-name}-SF-CMD",
                "desc": "Supply Fan Start/Stop Command",
                "states": {0: "Stop", 1: "Start"},
                "default": 0,
            },
        ],
        "BV": [
            {
                "name": "{device-name}-OCC-CMD",
                "desc": "Occupancy Command (from schedule or BAS)",
                "states": {0: "Unoccupied", 1: "Occupied"},
                "default": 0,
            },
        ],
        "MV": [
            {
                "name": "{device-name}-MODE",
                "desc": "Operating Mode",
                "states": {1: "Off", 2: "Unoccupied", 3: "Occupied"},
                "default": 1,
            },
        ],
    },

    "io_map": {
        "UI1": "{device-name}-SAT",
        "UI2": "{device-name}-OAT",
        "BI1": "{device-name}-SF-STS",
        "BO1": "{device-name}-SF-CMD",
    },

    "code": """\
REM ======================================================================
REM  {device-name} — DOAS BASE: Dedicated Outdoor Air System Control
REM  SBS Controls Division — Auto-generated by Composition Engine
REM ======================================================================

REM ── Configuration Constants ──
REM 100% outdoor air — no return air or economizer in base

REM ── Read Inputs ──
SAT = AI1
OAT = AI2
FAN_STS = BI1
OCC = BV1
MODE = MV1

REM ── Mode Determination ──
REM Mode 1=Off, 2=Unocc, 3=Occ
IF OCC = 1 THEN
  MV1 = 3
ELSE
  IF MODE = 3 THEN
    REM Transition to unoccupied
    MV1 = 2
  ENDIF
  IF MODE = 1 THEN
    MV1 = 2
  ENDIF
ENDIF

MODE = MV1

REM ── Fan Command ──
IF MODE = 3 THEN
  REM Occupied: fan ON
  BO1 = 1
ELSE
  REM Unoccupied or Off: fan OFF (DOAS has no low-limit cycling)
  BO1 = 0
ENDIF

REM ── Supply Air Temp Setpoint ──
REM Clamp active setpoint within min/max range
SAT_SP = AV1
IF SAT_SP < AV2 THEN SAT_SP = AV2
IF SAT_SP > AV3 THEN SAT_SP = AV3
AV1 = SAT_SP

REM ── Fan Status Alarm ──
IF BO1 = 1 AND FAN_STS = 0 THEN
  IF FAN_FAIL_TMR = 0 THEN
    FAN_FAIL_TMR = ELAPSED
  ENDIF
  IF (ELAPSED - FAN_FAIL_TMR) > 30 THEN
    FAN_ALARM = 1
  ENDIF
ELSE
  FAN_FAIL_TMR = 0
  FAN_ALARM = 0
ENDIF

900 REM ── End of Base Module ──\
""",
}

register_base("DOAS", module)
