"""
SBS Controls — Base Module: Unit Heater

Simple unit heater with zone temperature sensor, fan command/status,
and zone temperature setpoint control.

    - ZNT (AI) — zone temperature sensor
    - FAN-CMD (DO) — unit heater fan command
    - FAN-STS (DI) — unit heater fan status
    - Zone setpoint — enable fan when below setpoint

Point Naming:
    All points use {device-name} prefix per SBS standard.
    Example: {device-name}-ZNT -> UH-1-ZNT when composed.
"""

from app.modules import register_base

module = {
    "id": "base_unit_heater",
    "name": "Unit Heater (Base)",
    "feature": "BASE",
    "category": "core",
    "requires": [],
    "conflicts": [],
    "exec_order": 10,

    "objects": {
        "AI": [
            {
                "name": "{device-name}-ZNT",
                "desc": "Zone Temperature",
                "units": "deg-f",
                "min": 40,
                "max": 120,
            },
        ],
        "AO": [],
        "AV": [
            {
                "name": "{device-name}-ZNT-HTG-SP",
                "desc": "Zone Heating Setpoint",
                "units": "deg-f",
                "min": 40,
                "max": 85,
                "default": 65.0,
            },
            {
                "name": "{device-name}-ZNT-DIFF",
                "desc": "Heating Differential (deadband)",
                "units": "deg-f",
                "min": 1,
                "max": 10,
                "default": 2.0,
            },
        ],
        "BI": [
            {
                "name": "{device-name}-FAN-STS",
                "desc": "Unit Heater Fan Status",
                "states": {0: "Off", 1: "On"},
            },
        ],
        "BO": [
            {
                "name": "{device-name}-FAN-CMD",
                "desc": "Unit Heater Fan Command",
                "states": {0: "Stop", 1: "Start"},
                "default": 0,
            },
        ],
        "BV": [
            {
                "name": "{device-name}-OCC-CMD",
                "desc": "Occupancy Command (from schedule or BAS)",
                "states": {0: "Unoccupied", 1: "Occupied"},
                "default": 0,
            },
        ],
        "MV": [],
    },

    "io_map": {
        "UI1": "{device-name}-ZNT",
        "BI1": "{device-name}-FAN-STS",
        "BO1": "{device-name}-FAN-CMD",
    },

    "code": """\
REM ======================================================================
REM  {device-name} — UNIT HEATER BASE: Zone Temperature Control
REM  SBS Controls Division — Auto-generated by Composition Engine
REM ======================================================================

REM ── Read Inputs ──
ZNT = AI1
FAN_STS = BI1
OCC = BV1

REM ── Configuration ──
HTG_SP = AV1
DIFF = AV2

REM ── Unit Heater Control ──
REM Enable fan when zone temp below setpoint, disable above setpoint + diff
IF ZNT < HTG_SP THEN
  REM Below setpoint — turn on unit heater
  BO1 = 1
ENDIF

IF ZNT > (HTG_SP + DIFF) THEN
  REM Above setpoint + differential — turn off unit heater
  BO1 = 0
ENDIF

REM ── Unoccupied Override ──
IF OCC = 0 THEN
  REM Unoccupied: lower setpoint by 10 degrees for energy savings
  UNOCC_SP = HTG_SP - 10
  IF ZNT < UNOCC_SP THEN
    BO1 = 1
  ENDIF
  IF ZNT > (UNOCC_SP + DIFF) THEN
    BO1 = 0
  ENDIF
ENDIF

REM ── Fan Status Alarm ──
IF BO1 = 1 AND FAN_STS = 0 THEN
  IF FAN_FAIL_TMR = 0 THEN
    FAN_FAIL_TMR = ELAPSED
  ENDIF
  IF (ELAPSED - FAN_FAIL_TMR) > 30 THEN
    FAN_ALARM = 1
  ENDIF
ELSE
  FAN_FAIL_TMR = 0
  FAN_ALARM = 0
ENDIF

REM ── End of Base Module ──\
""",
}

register_base("UH", module)
