"""
SBS Controls — Base Module: Rooftop Unit Variable Air Volume

Similar to AHU-VAV but designed for rooftop units with integrated DX cooling
capability. Contains the fundamental points, I/O, and code:

    - Supply air temperature sensor (SAT)
    - Return air temperature sensor (RAT)
    - Outside air temperature sensor (OAT)
    - Duct static pressure sensor (DSP)
    - Supply fan command and status (SF-CMD, SF-STS)
    - Occupancy/mode determination (OCC-CMD, MODE)
    - Supply air temperature setpoints (SAT-SP, SAT-SP-CLG, SAT-SP-HTG)
    - Mode state machine: OFF / UNOCC / OCC / WARMUP / COOLDOWN

Point Naming:
    All points use {device-name} prefix per SBS standard.
    Example: {device-name}-SAT -> RTU-1-SAT when composed.
"""

from app.modules import register_base

module = {
    "id": "base_rtu_vav",
    "name": "RTU - Variable Air Volume (Base)",
    "feature": "BASE",
    "category": "core",
    "requires": [],
    "conflicts": [],
    "exec_order": 10,

    "objects": {
        "AI": [
            {
                "name": "{device-name}-SAT",
                "desc": "Supply Air Temperature",
                "units": "deg-f",
                "min": -20,
                "max": 150,
            },
            {
                "name": "{device-name}-OAT",
                "desc": "Outside Air Temperature",
                "units": "deg-f",
                "min": -40,
                "max": 130,
            },
            {
                "name": "{device-name}-RAT",
                "desc": "Return Air Temperature",
                "units": "deg-f",
                "min": 40,
                "max": 120,
            },
            {
                "name": "{device-name}-DSP",
                "desc": "Duct Static Pressure",
                "units": "inwc",
                "min": 0,
                "max": 5.0,
            },
        ],
        "AO": [],
        "AV": [
            {
                "name": "{device-name}-SAT-SP",
                "desc": "Supply Air Temperature Setpoint (Active)",
                "units": "deg-f",
                "min": 40,
                "max": 90,
                "default": 55.0,
            },
            {
                "name": "{device-name}-SAT-SP-CLG",
                "desc": "Supply Air Temp Setpoint - Cooling",
                "units": "deg-f",
                "min": 50,
                "max": 65,
                "default": 55.0,
            },
            {
                "name": "{device-name}-SAT-SP-HTG",
                "desc": "Supply Air Temp Setpoint - Heating",
                "units": "deg-f",
                "min": 65,
                "max": 90,
                "default": 72.0,
            },
            {
                "name": "{device-name}-OCC-DLY",
                "desc": "Occupancy Start Delay (minutes)",
                "units": "minutes",
                "min": 0,
                "max": 60,
                "default": 0,
            },
        ],
        "BI": [
            {
                "name": "{device-name}-SF-STS",
                "desc": "Supply Fan Status (current switch)",
                "states": {0: "Off", 1: "On"},
            },
        ],
        "BO": [
            {
                "name": "{device-name}-SF-CMD",
                "desc": "Supply Fan Start/Stop Command",
                "states": {0: "Stop", 1: "Start"},
                "default": 0,
            },
        ],
        "BV": [
            {
                "name": "{device-name}-OCC-CMD",
                "desc": "Occupancy Command (from schedule or BAS)",
                "states": {0: "Unoccupied", 1: "Occupied"},
                "default": 0,
            },
            {
                "name": "{device-name}-EMER-STOP",
                "desc": "Emergency Stop (software)",
                "states": {0: "Normal", 1: "Emergency Stop"},
                "default": 0,
            },
        ],
        "MV": [
            {
                "name": "{device-name}-MODE",
                "desc": "Operating Mode",
                "states": {1: "Off", 2: "Unoccupied", 3: "Occupied",
                           4: "Warmup", 5: "Cooldown"},
                "default": 1,
            },
        ],
    },

    "io_map": {
        "UI1": "{device-name}-SAT",
        "UI2": "{device-name}-OAT",
        "UI3": "{device-name}-RAT",
        "UI4": "{device-name}-DSP",
        "BI1": "{device-name}-SF-STS",
        "BO1": "{device-name}-SF-CMD",
    },

    "code": """\
REM ======================================================================
REM  {device-name} — RTU VAV BASE: Mode & Occupancy Control
REM  SBS Controls Division — Auto-generated by Composition Engine
REM ======================================================================

REM ── Configuration Constants ──
WARMUP_TIME = 30
COOLDOWN_TIME = 15
UNOCC_LOW_LIMIT = 55
UNOCC_HIGH_LIMIT = 85

REM ── Read Inputs ──
SAT = AI1
OAT = AI2
RAT = AI3
DSP_VAL = AI4
FAN_STS = BI1
OCC = BV1
ESTOP = BV2
MODE = MV1

REM ── Emergency Stop Check ──
IF ESTOP = 1 THEN
  BO1 = 0
  MV1 = 1
  GOTO 900
ENDIF

REM ── Mode State Machine ──
REM Mode 1=Off, 2=Unocc, 3=Occ, 4=Warmup, 5=Cooldown

IF OCC = 0 THEN
  IF MODE = 3 THEN
    MV1 = 5
    COOLDOWN_START = ELAPSED
  ENDIF
  IF MODE = 5 THEN
    IF (ELAPSED - COOLDOWN_START) > (COOLDOWN_TIME * 60) THEN
      MV1 = 2
    ENDIF
  ENDIF
  IF MODE = 4 THEN
    MV1 = 2
  ENDIF
  IF MODE = 1 THEN
    MV1 = 2
  ENDIF
ELSE
  IF MODE = 2 OR MODE = 1 THEN
    MV1 = 4
    WARMUP_START = ELAPSED
  ENDIF
  IF MODE = 4 THEN
    IF (ELAPSED - WARMUP_START) > (WARMUP_TIME * 60) THEN
      MV1 = 3
    ENDIF
  ENDIF
  IF MODE = 5 THEN
    MV1 = 3
  ENDIF
ENDIF

MODE = MV1

REM ── Fan Command ──
IF MODE >= 3 THEN
  BO1 = 1
ELSE
  IF MODE = 2 THEN
    IF RAT < UNOCC_LOW_LIMIT OR RAT > UNOCC_HIGH_LIMIT THEN
      BO1 = 1
    ELSE
      BO1 = 0
    ENDIF
  ELSE
    BO1 = 0
  ENDIF
ENDIF

REM ── Supply Air Temp Setpoint Selection ──
IF MODE = 3 THEN
  AV1 = AV2
ELSE
  IF MODE = 4 THEN
    AV1 = AV4
  ELSE
    AV1 = AV2
  ENDIF
ENDIF

REM ── Fan Status Alarm ──
IF BO1 = 1 AND FAN_STS = 0 THEN
  IF FAN_FAIL_TMR = 0 THEN
    FAN_FAIL_TMR = ELAPSED
  ENDIF
  IF (ELAPSED - FAN_FAIL_TMR) > 30 THEN
    FAN_ALARM = 1
  ENDIF
ELSE
  FAN_FAIL_TMR = 0
  FAN_ALARM = 0
ENDIF

900 REM ── End of Base Module ──\
""",
}

register_base("RTU-VAV", module)
