"""
SBS Controls — Base Module: Fan Coil Unit (2-Pipe Cooling Only)

This is the core module loaded for every FCU equipment type.
Base configuration is 2-pipe cooling only with CHW valve and fan staging.

    - Zone temperature sensor (ZNT)
    - Fan command (FAN-CMD as DO) and status (FAN-STS as DI)
    - CHW valve (CHW-VLV as AO) for 2-pipe base
    - Zone temperature setpoints
    - Simple zone temp control: fan staging + valve modulation

Point Naming:
    All points use {device-name} prefix per SBS standard.
    Example: {device-name}-ZNT -> FCU-1-ZNT when composed.
"""

from app.modules import register_base

module = {
    "id": "base_fcu",
    "name": "Fan Coil Unit - 2-Pipe Cooling Only (Base)",
    "feature": "BASE",
    "category": "core",
    "requires": [],
    "conflicts": [],
    "exec_order": 10,

    "objects": {
        "AI": [
            {
                "name": "{device-name}-ZNT",
                "desc": "Zone Temperature",
                "units": "deg-f",
                "min": 40,
                "max": 120,
            },
        ],
        "AO": [
            {
                "name": "{device-name}-CHW-VLV",
                "desc": "Chilled Water Valve Command",
                "units": "percent",
                "min": 0,
                "max": 100,
                "default": 0,
            },
        ],
        "AV": [
            {
                "name": "{device-name}-ZNT-CLG-SP",
                "desc": "Zone Cooling Setpoint (Active)",
                "units": "deg-f",
                "min": 60,
                "max": 85,
                "default": 74.0,
            },
            {
                "name": "{device-name}-ZNT-HTG-SP",
                "desc": "Zone Heating Setpoint (Active)",
                "units": "deg-f",
                "min": 55,
                "max": 80,
                "default": 70.0,
            },
            {
                "name": "{device-name}-ZNT-OCC-CLG-SP",
                "desc": "Zone Occupied Cooling Setpoint",
                "units": "deg-f",
                "min": 65,
                "max": 85,
                "default": 74.0,
            },
            {
                "name": "{device-name}-ZNT-OCC-HTG-SP",
                "desc": "Zone Occupied Heating Setpoint",
                "units": "deg-f",
                "min": 60,
                "max": 80,
                "default": 70.0,
            },
            {
                "name": "{device-name}-ZNT-UNOCC-CLG-SP",
                "desc": "Zone Unoccupied Cooling Setpoint",
                "units": "deg-f",
                "min": 75,
                "max": 95,
                "default": 85.0,
            },
            {
                "name": "{device-name}-ZNT-UNOCC-HTG-SP",
                "desc": "Zone Unoccupied Heating Setpoint",
                "units": "deg-f",
                "min": 50,
                "max": 70,
                "default": 55.0,
            },
        ],
        "BI": [
            {
                "name": "{device-name}-FAN-STS",
                "desc": "Fan Status",
                "states": {0: "Off", 1: "On"},
            },
        ],
        "BO": [
            {
                "name": "{device-name}-FAN-CMD",
                "desc": "Fan Start/Stop Command",
                "states": {0: "Stop", 1: "Start"},
                "default": 0,
            },
        ],
        "BV": [
            {
                "name": "{device-name}-OCC-CMD",
                "desc": "Occupancy Command (from schedule or BAS)",
                "states": {0: "Unoccupied", 1: "Occupied"},
                "default": 0,
            },
        ],
        "MV": [],
    },

    "io_map": {
        "UI1": "{device-name}-ZNT",
        "BI1": "{device-name}-FAN-STS",
        "BO1": "{device-name}-FAN-CMD",
        "UO1": "{device-name}-CHW-VLV",
    },

    "code": """\
REM ======================================================================
REM  {device-name} — FCU BASE: Fan Coil Zone Control (2-Pipe Cooling)
REM  SBS Controls Division — Auto-generated by Composition Engine
REM ======================================================================

REM ── Read Inputs ──
ZNT = AI1
FAN_STS = BI1
OCC = BV1

REM ── Setpoint Selection ──
IF OCC = 1 THEN
  CLG_SP = AV3
  HTG_SP = AV4
ELSE
  CLG_SP = AV5
  HTG_SP = AV6
ENDIF
AV1 = CLG_SP
AV2 = HTG_SP

REM ── Fan Control ──
IF OCC = 1 THEN
  REM Occupied: fan always on
  BO1 = 1
ELSE
  REM Unoccupied: fan cycles on low/high limit
  IF ZNT > CLG_SP OR ZNT < HTG_SP THEN
    BO1 = 1
  ELSE
    BO1 = 0
  ENDIF
ENDIF

REM ── CHW Valve Control (Cooling) ──
IF BO1 = 1 THEN
  ZNT_ERR = ZNT - CLG_SP

  IF ZNT_ERR > 0 THEN
    REM Zone above cooling setpoint — open CHW valve
    CHW_OUT = (ZNT_ERR / 3) * 100
    IF CHW_OUT > 100 THEN CHW_OUT = 100
    IF CHW_OUT < 0 THEN CHW_OUT = 0
    AO1 = CHW_OUT
  ELSE
    REM At or below setpoint — close valve
    AO1 = 0
  ENDIF
ELSE
  REM Fan off — close valve
  AO1 = 0
ENDIF

REM ── Fan Status Alarm ──
IF BO1 = 1 AND FAN_STS = 0 THEN
  IF FAN_FAIL_TMR = 0 THEN
    FAN_FAIL_TMR = ELAPSED
  ENDIF
  IF (ELAPSED - FAN_FAIL_TMR) > 30 THEN
    FAN_ALARM = 1
  ENDIF
ELSE
  FAN_FAIL_TMR = 0
  FAN_ALARM = 0
ENDIF

REM ── End of Base Module ──\
""",
}

register_base("FCU", module)
