"""
SBS Controls — Base Module: AHU Variable Air Volume

Core module for every AHU-VAV equipment type. Outputs multiple PROGRAM
objects using proper Reliable Controls Control-BASIC syntax:

Programs:
    {device-name}-CFG-PRG   — Configuration: setpoint limits, deadbands
    {device-name}-MODE-PRG  — Occupancy mode + HVAC mode determination
    {device-name}-SP-PRG    — Active SAT setpoint calculation

Point Naming:
    All points use {device-name} prefix per SBS standard.
    Example: {device-name}-SAT -> AHU-1-SAT when composed.
"""

from app.modules import register_base

module = {
    "id": "base_ahu_vav",
    "name": "AHU - Variable Air Volume (Base)",
    "feature": "BASE",
    "category": "core",
    "requires": [],
    "conflicts": [],
    "exec_order": 10,

    "objects": {
        "AI": [
            {
                "name": "{device-name}-SAT",
                "desc": "Supply Air Temperature",
                "units": "deg-f",
                "min": -20,
                "max": 150,
            },
            {
                "name": "{device-name}-OAT",
                "desc": "Outside Air Temperature",
                "units": "deg-f",
                "min": -40,
                "max": 130,
            },
            {
                "name": "{device-name}-RAT",
                "desc": "Return Air Temperature",
                "units": "deg-f",
                "min": 40,
                "max": 120,
            },
        ],
        "AO": [],
        "AV": [
            {
                "name": "{device-name}-SAT-SP",
                "desc": "Supply Air Temperature Setpoint (Active)",
                "units": "deg-f",
                "min": 40,
                "max": 90,
                "default": 55.0,
            },
            {
                "name": "{device-name}-SAT-SP-MIN",
                "desc": "Supply Air Temp Setpoint Minimum Limit",
                "units": "deg-f",
                "min": 40,
                "max": 70,
                "default": 50.0,
            },
            {
                "name": "{device-name}-SAT-SP-MAX",
                "desc": "Supply Air Temp Setpoint Maximum Limit",
                "units": "deg-f",
                "min": 60,
                "max": 100,
                "default": 80.0,
            },
            {
                "name": "{device-name}-CFG-SAT-SP-DB",
                "desc": "SAT Setpoint Deadband",
                "units": "deg-f",
                "min": 0.5,
                "max": 5.0,
                "default": 2.0,
            },
        ],
        "BI": [
            {
                "name": "{device-name}-SF-STS",
                "desc": "Supply Fan Status (current switch)",
                "states": {0: "Off", 1: "On"},
            },
        ],
        "BO": [
            {
                "name": "{device-name}-SF-CMD",
                "desc": "Supply Fan Start/Stop Command",
                "states": {0: "Stop", 1: "Start"},
                "default": 0,
            },
        ],
        "BV": [
            {
                "name": "{device-name}-EMER-STOP",
                "desc": "Emergency Stop (software)",
                "states": {0: "Normal", 1: "Emergency Stop"},
                "default": 0,
            },
        ],
        "MV": [
            {
                "name": "{device-name}-OCC-MODE",
                "desc": "Occupancy Mode",
                "states": {0: "Off", 1: "Occupied", 2: "Bypass",
                           3: "Standby", 4: "Unoccupied"},
                "default": 0,
            },
            {
                "name": "{device-name}-HVAC-MODE",
                "desc": "HVAC Operating Mode",
                "states": {0: "Off", 1: "Heat", 2: "Cool"},
                "default": 0,
            },
        ],
        "SCHEDULE": [
            {
                "name": "{device-name}-SCHED",
                "desc": "Occupancy Schedule",
            },
        ],
    },

    "io_map": {
        "UI1": "{device-name}-SAT",
        "UI2": "{device-name}-OAT",
        "UI3": "{device-name}-RAT",
        "BI1": "{device-name}-SF-STS",
        "BO1": "{device-name}-SF-CMD",
    },

    "programs": [
        {
            "name": "{device-name}-CFG-PRG",
            "description": "Configuration — Setpoint Limits and Deadbands",
            "code": (
                "10 REM ***** CONFIGURATION PROGRAM *****\n"
                "20 REM SBS Controls — Auto-generated by Composition Engine\n"
                "30 REM Enforce setpoint limits and calculate deadbands\n"
                "40 REM\n"
                "50 REM ── Clamp SAT setpoint to min/max limits ──\n"
                "60 LET {device-name}-SAT-SP = LIMIT( {device-name}-SAT-SP , {device-name}-SAT-SP-MIN , {device-name}-SAT-SP-MAX )\n"
                "70 REM\n"
                "80 REM ── End Configuration ──\n"
                "90 END"
            ),
        },
        {
            "name": "{device-name}-MODE-PRG",
            "description": "Occupancy Mode and HVAC Mode Determination",
            "code": (
                "10 REM ***** MODE DETERMINATION PROGRAM *****\n"
                "20 REM SBS Controls — Auto-generated by Composition Engine\n"
                "30 REM Reads OCC-MODE and determines HVAC-MODE\n"
                "40 REM OCC-MODE: 0=Off, 1=Occ, 2=Bypass, 3=Standby, 4=Unocc\n"
                "50 REM HVAC-MODE: 0=Off, 1=Heat, 2=Cool\n"
                "60 REM\n"
                "70 REM ── Emergency Stop Check ──\n"
                "80 IF {device-name}-EMER-STOP THEN STOP {device-name}-SF-CMD , LET {device-name}-HVAC-MODE = 0 , END\n"
                "90 REM\n"
                "100 REM ── Off mode — shut down ──\n"
                "110 IF {device-name}-OCC-MODE = 0 THEN STOP {device-name}-SF-CMD , LET {device-name}-HVAC-MODE = 0 , END\n"
                "120 REM\n"
                "130 REM ── Occupied or Bypass — fan on ──\n"
                "140 IF {device-name}-OCC-MODE = 1 THEN START {device-name}-SF-CMD\n"
                "150 IF {device-name}-OCC-MODE = 2 THEN START {device-name}-SF-CMD\n"
                "160 REM\n"
                "170 REM ── Standby — fan off but ready ──\n"
                "180 IF {device-name}-OCC-MODE = 3 THEN STOP {device-name}-SF-CMD , LET {device-name}-HVAC-MODE = 0 , END\n"
                "190 REM\n"
                "200 REM ── Unoccupied — fan off ──\n"
                "210 IF {device-name}-OCC-MODE = 4 THEN STOP {device-name}-SF-CMD , LET {device-name}-HVAC-MODE = 0 , END\n"
                "220 REM\n"
                "230 REM ── Determine HVAC mode from SAT vs setpoint ──\n"
                "240 LET A = {device-name}-SAT\n"
                "250 LET B = {device-name}-SAT-SP\n"
                "260 LET C = {device-name}-CFG-SAT-SP-DB\n"
                "270 REM If SAT > SP + deadband then cooling needed\n"
                "280 IF A > ( B + C ) THEN LET {device-name}-HVAC-MODE = 2 , END\n"
                "290 REM If SAT < SP - deadband then heating needed\n"
                "300 IF A < ( B - C ) THEN LET {device-name}-HVAC-MODE = 1 , END\n"
                "310 REM Otherwise maintain current mode (deadband)\n"
                "320 END"
            ),
        },
        {
            "name": "{device-name}-SP-PRG",
            "description": "Active SAT Setpoint Calculation",
            "code": (
                "10 REM ***** SETPOINT CALCULATION PROGRAM *****\n"
                "20 REM SBS Controls — Auto-generated by Composition Engine\n"
                "30 REM Calculate active SAT-SP based on OCC-MODE\n"
                "40 REM\n"
                "50 REM ── Occupied: use cooling SAT setpoint (55F typical) ──\n"
                "60 IF {device-name}-OCC-MODE = 1 THEN LET {device-name}-SAT-SP = {device-name}-SAT-SP-MIN + 5\n"
                "70 REM\n"
                "80 REM ── Bypass: same as occupied ──\n"
                "90 IF {device-name}-OCC-MODE = 2 THEN LET {device-name}-SAT-SP = {device-name}-SAT-SP-MIN + 5\n"
                "100 REM\n"
                "110 REM ── Unoccupied: relax setpoint to save energy ──\n"
                "120 IF {device-name}-OCC-MODE = 4 THEN LET {device-name}-SAT-SP = {device-name}-SAT-SP-MAX - 5\n"
                "130 REM\n"
                "140 REM ── Enforce limits ──\n"
                "150 LET {device-name}-SAT-SP = LIMIT( {device-name}-SAT-SP , {device-name}-SAT-SP-MIN , {device-name}-SAT-SP-MAX )\n"
                "160 END"
            ),
        },
    ],
}

register_base("AHU-VAV", module)
