"""
SBS Controls — Base Module: VAV Terminal Unit (Cooling Only)

This is the core module loaded for every VAV terminal equipment type.
Contains the fundamental points, I/O, and code that every cooling-only
VAV box requires:

    - Zone temperature sensor (ZNT)
    - Airflow sensor (CFM)
    - Damper command (DMP-CMD)
    - Zone temperature setpoints (cooling/heating, occ/unocc)
    - Airflow setpoints (max, min, vent min)
    - Occupancy command
    - Cooling-only damper control logic

Point Naming:
    All points use {device-name} prefix per SBS standard.
    Example: {device-name}-ZNT -> VAV-1-01-ZNT when composed.
"""

from app.modules import register_base

module = {
    "id": "base_vav_terminal",
    "name": "VAV Terminal Unit - Cooling Only (Base)",
    "feature": "BASE",
    "category": "core",
    "requires": [],
    "conflicts": [],
    "exec_order": 10,

    "objects": {
        "AI": [
            {
                "name": "{device-name}-ZNT",
                "desc": "Zone Temperature",
                "units": "deg-f",
                "min": 40,
                "max": 120,
            },
            {
                "name": "{device-name}-CFM",
                "desc": "Airflow (CFM)",
                "units": "cfm",
                "min": 0,
                "max": 5000,
            },
        ],
        "AO": [
            {
                "name": "{device-name}-DMP-CMD",
                "desc": "Damper Command",
                "units": "percent",
                "min": 0,
                "max": 100,
                "default": 0,
            },
        ],
        "AV": [
            {
                "name": "{device-name}-ZNT-CLG-SP",
                "desc": "Zone Cooling Setpoint (Active)",
                "units": "deg-f",
                "min": 60,
                "max": 85,
                "default": 74.0,
            },
            {
                "name": "{device-name}-ZNT-HTG-SP",
                "desc": "Zone Heating Setpoint (Active)",
                "units": "deg-f",
                "min": 55,
                "max": 80,
                "default": 70.0,
            },
            {
                "name": "{device-name}-ZNT-OCC-CLG-SP",
                "desc": "Zone Occupied Cooling Setpoint",
                "units": "deg-f",
                "min": 65,
                "max": 85,
                "default": 74.0,
            },
            {
                "name": "{device-name}-ZNT-OCC-HTG-SP",
                "desc": "Zone Occupied Heating Setpoint",
                "units": "deg-f",
                "min": 60,
                "max": 80,
                "default": 70.0,
            },
            {
                "name": "{device-name}-ZNT-UNOCC-CLG-SP",
                "desc": "Zone Unoccupied Cooling Setpoint",
                "units": "deg-f",
                "min": 75,
                "max": 95,
                "default": 85.0,
            },
            {
                "name": "{device-name}-ZNT-UNOCC-HTG-SP",
                "desc": "Zone Unoccupied Heating Setpoint",
                "units": "deg-f",
                "min": 50,
                "max": 70,
                "default": 55.0,
            },
            {
                "name": "{device-name}-CFM-CLG-MAX",
                "desc": "Cooling Maximum Airflow",
                "units": "cfm",
                "min": 0,
                "max": 5000,
                "default": 1000,
            },
            {
                "name": "{device-name}-CFM-CLG-MIN",
                "desc": "Cooling Minimum Airflow",
                "units": "cfm",
                "min": 0,
                "max": 5000,
                "default": 300,
            },
            {
                "name": "{device-name}-CFM-VENT-MIN",
                "desc": "Ventilation Minimum Airflow",
                "units": "cfm",
                "min": 0,
                "max": 5000,
                "default": 150,
            },
        ],
        "BI": [],
        "BO": [],
        "BV": [
            {
                "name": "{device-name}-OCC-CMD",
                "desc": "Occupancy Command (from AHU or schedule)",
                "states": {0: "Unoccupied", 1: "Occupied"},
                "default": 0,
            },
        ],
        "MV": [],
    },

    "io_map": {
        "UI1": "{device-name}-ZNT",
        "UI2": "{device-name}-CFM",
        "UO1": "{device-name}-DMP-CMD",
    },

    "code": """\
REM ======================================================================
REM  {device-name} — VAV TERMINAL BASE: Cooling-Only Damper Control
REM  SBS Controls Division — Auto-generated by Composition Engine
REM ======================================================================

REM ── Read Inputs ──
ZNT = AI1
CFM = AI2
OCC = BV1

REM ── Setpoint Selection ──
IF OCC = 1 THEN
  REM Occupied setpoints
  CLG_SP = AV3
  HTG_SP = AV4
ELSE
  REM Unoccupied setpoints
  CLG_SP = AV5
  HTG_SP = AV6
ENDIF
REM Write active setpoints
AV1 = CLG_SP
AV2 = HTG_SP

REM ── Airflow Limits ──
CFM_MAX = AV7
CFM_MIN = AV8
CFM_VENT = AV9

REM ── Cooling-Only Damper Control ──
REM Modulate damper based on zone temp vs cooling setpoint
REM Respect min/max CFM limits

IF OCC = 1 THEN
  REM Occupied mode
  ZNT_ERR = ZNT - CLG_SP

  IF ZNT_ERR > 0 THEN
    REM Zone above cooling setpoint — increase airflow
    DMP_OUT = CFM_MIN + ((ZNT_ERR / 3) * (CFM_MAX - CFM_MIN))
    IF DMP_OUT > CFM_MAX THEN DMP_OUT = CFM_MAX
    REM Convert CFM target to damper percent (linear approximation)
    AO1 = ((DMP_OUT - CFM_MIN) / (CFM_MAX - CFM_MIN)) * 100
  ELSE
    REM At or below setpoint — hold minimum airflow
    AO1 = ((CFM_MIN - CFM_VENT) / (CFM_MAX - CFM_VENT)) * 100
    IF AO1 < 0 THEN AO1 = 0
  ENDIF

  REM Ensure minimum ventilation
  IF CFM < CFM_VENT THEN
    AO1 = AO1 + 10
    IF AO1 > 100 THEN AO1 = 100
  ENDIF
ELSE
  REM Unoccupied: close to minimum
  AO1 = 0

  REM Unoccupied low/high limit override
  IF ZNT < HTG_SP THEN
    REM Below heating setpoint — open damper to minimum
    AO1 = 20
  ENDIF
  IF ZNT > CLG_SP THEN
    REM Above cooling setpoint — open damper for cooling
    AO1 = 50
  ENDIF
ENDIF

REM Clamp damper output
IF AO1 > 100 THEN AO1 = 100
IF AO1 < 0 THEN AO1 = 0

REM ── End of Base Module ──\
""",
}

register_base("VAV", module)
