"""
SBS Controls — Base Module: Water Source Heat Pump

This is the core module loaded for every WSHP equipment type.
Contains the fundamental points, I/O, and code that every water source
heat pump requires:

    - Zone temperature sensor (ZNT)
    - Entering/Leaving water temperature (EWT, LWT)
    - Discharge air temperature (DAT)
    - Compressor command, status, and alarm (CMP-CMD, CMP-STS, CMP-ALM)
    - Reversing valve for heat/cool mode (REV-VLV)
    - Fan command and status (FAN-CMD, FAN-STS)
    - Zone temperature setpoints (ZNT-CLG-SP, ZNT-HTG-SP)
    - Mode selection (Off/Cool/Heat/Auto)
    - Anti-short-cycle timer (3 min)
    - Entering water temp safety lockout (below 50F or above 110F)

Point Naming:
    All points use {device-name} prefix per SBS standard.
    Example: {device-name}-ZNT -> WSHP-1-ZNT when composed.
"""

from app.modules import register_base

module = {
    "id": "base_wshp",
    "name": "Water Source Heat Pump (Base)",
    "feature": "BASE",
    "category": "core",
    "requires": [],
    "conflicts": [],
    "exec_order": 10,

    "objects": {
        "AI": [
            {
                "name": "{device-name}-ZNT",
                "desc": "Zone Temperature",
                "units": "deg-f",
                "min": 40,
                "max": 120,
            },
            {
                "name": "{device-name}-EWT",
                "desc": "Entering Water Temperature",
                "units": "deg-f",
                "min": 30,
                "max": 130,
            },
            {
                "name": "{device-name}-LWT",
                "desc": "Leaving Water Temperature",
                "units": "deg-f",
                "min": 30,
                "max": 130,
            },
            {
                "name": "{device-name}-DAT",
                "desc": "Discharge Air Temperature",
                "units": "deg-f",
                "min": 40,
                "max": 150,
            },
        ],
        "AO": [],
        "AV": [
            {
                "name": "{device-name}-ZNT-CLG-SP",
                "desc": "Zone Cooling Setpoint",
                "units": "deg-f",
                "min": 60,
                "max": 85,
                "default": 74.0,
            },
            {
                "name": "{device-name}-ZNT-HTG-SP",
                "desc": "Zone Heating Setpoint",
                "units": "deg-f",
                "min": 55,
                "max": 80,
                "default": 70.0,
            },
        ],
        "BI": [
            {
                "name": "{device-name}-CMP-STS",
                "desc": "Compressor Status",
                "states": {0: "Off", 1: "On"},
            },
            {
                "name": "{device-name}-CMP-ALM",
                "desc": "Compressor Alarm/Fault",
                "states": {0: "Normal", 1: "Fault"},
            },
            {
                "name": "{device-name}-FAN-STS",
                "desc": "Fan Status",
                "states": {0: "Off", 1: "On"},
            },
        ],
        "BO": [
            {
                "name": "{device-name}-CMP-CMD",
                "desc": "Compressor Start/Stop Command",
                "states": {0: "Stop", 1: "Start"},
                "default": 0,
            },
            {
                "name": "{device-name}-REV-VLV",
                "desc": "Reversing Valve (Energize for Heat)",
                "states": {0: "Cooling", 1: "Heating"},
                "default": 0,
            },
            {
                "name": "{device-name}-FAN-CMD",
                "desc": "Fan Start/Stop Command",
                "states": {0: "Stop", 1: "Start"},
                "default": 0,
            },
        ],
        "BV": [],
        "MV": [
            {
                "name": "{device-name}-MODE",
                "desc": "Operating Mode",
                "states": {1: "Off", 2: "Cool", 3: "Heat", 4: "Auto"},
                "default": 4,
            },
        ],
    },

    "io_map": {
        "UI1": "{device-name}-ZNT",
        "UI2": "{device-name}-EWT",
        "UI3": "{device-name}-LWT",
        "UI4": "{device-name}-DAT",
        "BI1": "{device-name}-CMP-STS",
        "BI2": "{device-name}-CMP-ALM",
        "BI3": "{device-name}-FAN-STS",
        "BO1": "{device-name}-CMP-CMD",
        "BO2": "{device-name}-REV-VLV",
        "BO3": "{device-name}-FAN-CMD",
    },

    "code": """\
REM ======================================================================
REM  {device-name} — WSHP BASE: Water Source Heat Pump Control
REM  SBS Controls Division — Auto-generated by Composition Engine
REM ======================================================================

REM ── Configuration Constants ──
REM Anti-short-cycle timer (seconds)
CMP_MIN_TIME = 180
REM Entering water temp safety limits
EWT_LOW_LIMIT = 50
EWT_HIGH_LIMIT = 110

REM ── Read Inputs ──
ZNT = AI1
EWT = AI2
LWT = AI3
DAT = AI4
CMP_STS = BI1
CMP_ALM = BI2
FAN_STS = BI3
MODE = MV1
CLG_SP = AV1
HTG_SP = AV2

REM ── Entering Water Temp Safety Lockout ──
IF EWT < EWT_LOW_LIMIT OR EWT > EWT_HIGH_LIMIT THEN
  REM Water temp out of safe range — shut down compressor
  BO1 = 0
  BO3 = 0
  EWT_LOCKOUT = 1
  GOTO 900
ELSE
  EWT_LOCKOUT = 0
ENDIF

REM ── Compressor Alarm Check ──
IF CMP_ALM = 1 THEN
  REM Compressor fault — immediate shutdown
  BO1 = 0
  BO3 = 0
  GOTO 900
ENDIF

REM ── Mode Selection & Zone Temp Control ──
REM Mode 1=Off, 2=Cool, 3=Heat, 4=Auto

IF MODE = 1 THEN
  REM Off — everything off
  BO1 = 0
  BO2 = 0
  BO3 = 0
  GOTO 900
ENDIF

REM Determine call for cooling or heating
CALL_COOL = 0
CALL_HEAT = 0

IF MODE = 2 THEN
  REM Cooling only
  IF ZNT > CLG_SP + 1 THEN CALL_COOL = 1
ENDIF
IF MODE = 3 THEN
  REM Heating only
  IF ZNT < HTG_SP - 1 THEN CALL_HEAT = 1
ENDIF
IF MODE = 4 THEN
  REM Auto mode — determine based on zone temp
  IF ZNT > CLG_SP + 1 THEN CALL_COOL = 1
  IF ZNT < HTG_SP - 1 THEN CALL_HEAT = 1
ENDIF

REM ── Compressor Control with Anti-Short-Cycle ──
IF CALL_COOL = 1 OR CALL_HEAT = 1 THEN
  REM Need compressor — check anti-short-cycle timer
  IF BO1 = 0 THEN
    IF CMP_OFF_TMR = 0 OR (ELAPSED - CMP_OFF_TMR) > CMP_MIN_TIME THEN
      BO1 = 1
      CMP_ON_TMR = ELAPSED
    ENDIF
  ENDIF
ELSE
  REM No call — disable compressor (respect min on-time)
  IF BO1 = 1 THEN
    IF (ELAPSED - CMP_ON_TMR) > CMP_MIN_TIME THEN
      BO1 = 0
      CMP_OFF_TMR = ELAPSED
    ENDIF
  ENDIF
ENDIF

REM ── Reversing Valve ──
IF CALL_HEAT = 1 THEN
  REM Heating mode — energize reversing valve
  BO2 = 1
ELSE
  REM Cooling mode or off — de-energize reversing valve
  BO2 = 0
ENDIF

REM ── Fan Control ──
REM Fan tracks compressor — runs whenever compressor runs
IF BO1 = 1 THEN
  BO3 = 1
ELSE
  BO3 = 0
ENDIF

REM ── Fan Status Alarm ──
IF BO3 = 1 AND FAN_STS = 0 THEN
  IF FAN_FAIL_TMR = 0 THEN
    FAN_FAIL_TMR = ELAPSED
  ENDIF
  IF (ELAPSED - FAN_FAIL_TMR) > 30 THEN
    FAN_ALARM = 1
  ENDIF
ELSE
  FAN_FAIL_TMR = 0
  FAN_ALARM = 0
ENDIF

900 REM ── End of Base Module ──\
""",
}

register_base("WSHP", module)
