"""
SBS Controls — Base Module: Rooftop Unit Constant Volume

This is the core module loaded for every RTU-CV equipment type.
Constant volume rooftop unit with zone temperature control for
mode selection (heat/cool/off) and supply air temperature control.

    - Supply air temperature sensor (SAT)
    - Return air temperature sensor (RAT)
    - Outside air temperature sensor (OAT)
    - Zone temperature sensor (ZNT)
    - Supply fan command and status (SF-CMD, SF-STS) — constant speed
    - Occupancy/mode determination (OCC-CMD, MODE)
    - Zone temperature setpoints (ZNT-CLG-SP, ZNT-HTG-SP)
    - Supply air temperature setpoint (SAT-SP)
    - Mode state machine: OFF / UNOCC / OCC / WARMUP / COOLDOWN

Point Naming:
    All points use {device-name} prefix per SBS standard.
    Example: {device-name}-SAT -> RTU-2-SAT when composed.
"""

from app.modules import register_base

module = {
    "id": "base_rtu_cv",
    "name": "RTU - Constant Volume (Base)",
    "feature": "BASE",
    "category": "core",
    "requires": [],
    "conflicts": [],
    "exec_order": 10,

    "objects": {
        "AI": [
            {
                "name": "{device-name}-SAT",
                "desc": "Supply Air Temperature",
                "units": "deg-f",
                "min": -20,
                "max": 150,
            },
            {
                "name": "{device-name}-RAT",
                "desc": "Return Air Temperature",
                "units": "deg-f",
                "min": 40,
                "max": 120,
            },
            {
                "name": "{device-name}-OAT",
                "desc": "Outside Air Temperature",
                "units": "deg-f",
                "min": -40,
                "max": 130,
            },
            {
                "name": "{device-name}-ZNT",
                "desc": "Zone Temperature",
                "units": "deg-f",
                "min": 40,
                "max": 120,
            },
        ],
        "AO": [],
        "AV": [
            {
                "name": "{device-name}-ZNT-CLG-SP",
                "desc": "Zone Cooling Setpoint",
                "units": "deg-f",
                "min": 60,
                "max": 85,
                "default": 74.0,
            },
            {
                "name": "{device-name}-ZNT-HTG-SP",
                "desc": "Zone Heating Setpoint",
                "units": "deg-f",
                "min": 55,
                "max": 80,
                "default": 70.0,
            },
            {
                "name": "{device-name}-SAT-SP",
                "desc": "Supply Air Temperature Setpoint (Active)",
                "units": "deg-f",
                "min": 40,
                "max": 90,
                "default": 55.0,
            },
        ],
        "BI": [
            {
                "name": "{device-name}-SF-STS",
                "desc": "Supply Fan Status (current switch)",
                "states": {0: "Off", 1: "On"},
            },
        ],
        "BO": [
            {
                "name": "{device-name}-SF-CMD",
                "desc": "Supply Fan Start/Stop Command",
                "states": {0: "Stop", 1: "Start"},
                "default": 0,
            },
        ],
        "BV": [
            {
                "name": "{device-name}-OCC-CMD",
                "desc": "Occupancy Command (from schedule or BAS)",
                "states": {0: "Unoccupied", 1: "Occupied"},
                "default": 0,
            },
            {
                "name": "{device-name}-EMER-STOP",
                "desc": "Emergency Stop (software)",
                "states": {0: "Normal", 1: "Emergency Stop"},
                "default": 0,
            },
        ],
        "MV": [
            {
                "name": "{device-name}-MODE",
                "desc": "Operating Mode",
                "states": {1: "Off", 2: "Unoccupied", 3: "Occupied",
                           4: "Warmup", 5: "Cooldown"},
                "default": 1,
            },
        ],
    },

    "io_map": {
        "UI1": "{device-name}-SAT",
        "UI2": "{device-name}-RAT",
        "UI3": "{device-name}-OAT",
        "UI4": "{device-name}-ZNT",
        "BI1": "{device-name}-SF-STS",
        "BO1": "{device-name}-SF-CMD",
    },

    "code": """\
REM ======================================================================
REM  {device-name} — RTU CV BASE: Rooftop Unit Constant Volume Control
REM  SBS Controls Division — Auto-generated by Composition Engine
REM ======================================================================

REM ── Configuration Constants ──
WARMUP_TIME = 30
COOLDOWN_TIME = 15
UNOCC_LOW_LIMIT = 55
UNOCC_HIGH_LIMIT = 85

REM ── Read Inputs ──
SAT = AI1
RAT = AI2
OAT = AI3
ZNT = AI4
FAN_STS = BI1
OCC = BV1
ESTOP = BV2
MODE = MV1

REM ── Emergency Stop Check ──
IF ESTOP = 1 THEN
  BO1 = 0
  MV1 = 1
  GOTO 900
ENDIF

REM ── Mode State Machine ──
REM Mode 1=Off, 2=Unocc, 3=Occ, 4=Warmup, 5=Cooldown

IF OCC = 0 THEN
  IF MODE = 3 THEN
    MV1 = 5
    COOLDOWN_START = ELAPSED
  ENDIF
  IF MODE = 5 THEN
    IF (ELAPSED - COOLDOWN_START) > (COOLDOWN_TIME * 60) THEN
      MV1 = 2
    ENDIF
  ENDIF
  IF MODE = 4 THEN
    MV1 = 2
  ENDIF
  IF MODE = 1 THEN
    MV1 = 2
  ENDIF
ELSE
  IF MODE = 2 OR MODE = 1 THEN
    MV1 = 4
    WARMUP_START = ELAPSED
  ENDIF
  IF MODE = 4 THEN
    IF (ELAPSED - WARMUP_START) > (WARMUP_TIME * 60) THEN
      MV1 = 3
    ENDIF
  ENDIF
  IF MODE = 5 THEN
    MV1 = 3
  ENDIF
ENDIF

MODE = MV1

REM ── Fan Command (Constant Speed) ──
IF MODE >= 3 THEN
  BO1 = 1
ELSE
  IF MODE = 2 THEN
    IF ZNT < UNOCC_LOW_LIMIT OR ZNT > UNOCC_HIGH_LIMIT THEN
      BO1 = 1
    ELSE
      BO1 = 0
    ENDIF
  ELSE
    BO1 = 0
  ENDIF
ENDIF

REM ── Zone Temp Based Mode Selection ──
REM Determine heating/cooling call based on zone temp
IF MODE >= 3 THEN
  IF ZNT > AV1 + 1 THEN
    REM Zone above cooling setpoint — cooling mode
    CALL_COOL = 1
    CALL_HEAT = 0
  ELSE
    IF ZNT < AV2 - 1 THEN
      REM Zone below heating setpoint — heating mode
      CALL_COOL = 0
      CALL_HEAT = 1
    ELSE
      REM Deadband — no active call
      CALL_COOL = 0
      CALL_HEAT = 0
    ENDIF
  ENDIF
ELSE
  CALL_COOL = 0
  CALL_HEAT = 0
ENDIF

REM ── Fan Status Alarm ──
IF BO1 = 1 AND FAN_STS = 0 THEN
  IF FAN_FAIL_TMR = 0 THEN
    FAN_FAIL_TMR = ELAPSED
  ENDIF
  IF (ELAPSED - FAN_FAIL_TMR) > 30 THEN
    FAN_ALARM = 1
  ENDIF
ELSE
  FAN_FAIL_TMR = 0
  FAN_ALARM = 0
ENDIF

900 REM ── End of Base Module ──\
""",
}

register_base("RTU-CV", module)
