"""
SBS Composition Engine v2 — .pan Export

Converts assembled ControllerConfig into the library JSON format
that the existing composer/PFG pipeline can merge into a blank .pan.

The JSON format matches what's in library-dev/ variants:
  - objects: {AI: [...], AO: [...], AV: [...], BI: [...], BO: [...], BV: [...], MV: [...],
              PROGRAM: [...], LOOP: [...], TREND: [...], SCHEDULE: [...], TABLE: [...],
              SYSTEMGROUP: [...]}
  - meta: {Model, Database, HardPointConfig, ...}

RC Studio Range Codes (numeric):
  AI/AO ranges: 0=Off/On, 1=0-5V, 2=0-10V, 3=0-100%, etc.
  For thermistors: specific code per type
  We map our text ranges to numeric codes.
"""

import json
from composition.models import ControllerConfig


# RC Studio range code mapping
INPUT_RANGE_MAP = {
    "Off/On": "0",
    "Normal/Alarm": "0",
    "Clean/Dirty": "0",
    "Close/Open": "0",
    "10K -40 ->250": "3",       # 10K Type 2 thermistor
    "0 ->100% (0-5V)": "1",    # 0-5V
    "0 ->100% (0-10V)": "2",   # 0-10V
    "Table1": "32",             # Table reference
    "Table2": "33",
    "Table3": "34",
    "Table4": "35",
    "Table5": "36",
}

OUTPUT_RANGE_MAP = {
    "Stop/Start": "2",          # Binary relay
    "Close/Open": "2",
    "0.0 ->100%": "3",         # 0-100% analog
}

# RC Studio unit codes
UNIT_MAP = {
    "°F": "2",
    "%": "22",
    "WC": "15",
    "ppm": "88",
    "CFM": "15",
    "FPM": "15",
    "BTU/lb": "26",
    "Min.": "17",
    "#": "29",
    "Sec": "17",
    "Time": "17",
    "": "",
    "GPM": "15",
    "PSI": "15",
    "ft²": "29",
}


def config_to_library_json(config: ControllerConfig, device_instance: int = 4194270) -> dict:
    """
    Convert assembled ControllerConfig to library-compatible JSON format.
    This JSON can be fed to the composer/PFG pipeline to generate a .pan file.
    """
    objects = {
        "AI": {}, "AO": {}, "AV": {}, "BI": {}, "BO": {},
        "BV": {}, "MV": {}, "MO": {},
        "PROGRAM": {}, "LOOP": {}, "TREND": {},
        "SCHEDULE": {}, "TABLE": {}, "ARRAY": {},
        "SYSTEMGROUP": {}, "DEVICE": {},
        "SMARTSENSOR": {}, "CALENDAR": {}, "OTHER": {},
    }

    # Device object
    objects["DEVICE"][str(device_instance)] = {
        "instance": str(device_instance),
        "name": "",
        "description": "Generated by SBS Composition Engine v2",
        "location": "",
    }

    # INPUTS → AI or BI objects
    for pt in config.inputs:
        obj_type = pt.point_type  # "AI" or "BI"
        key = f"{obj_type}{pt.row}"
        range_code = INPUT_RANGE_MAP.get(pt.range_code, "0")
        unit_code = UNIT_MAP.get(pt.units, "")

        objects[obj_type][key] = {
            "type": obj_type,
            "instance": str(pt.row),
            "name": f"{{device-name}}-{pt.name}",
            "description": pt.description,
            "range": range_code,
            "unit": unit_code,
            "increment": "0.100000" if obj_type == "AI" else "",
            "present_value": "0" if obj_type == "BI" else "0.000000",
        }

    # OUTPUTS → AO or BO objects
    for pt in config.outputs:
        obj_type = pt.point_type  # "AO" or "BO"
        key = f"{obj_type}{pt.row}"
        range_code = OUTPUT_RANGE_MAP.get(pt.range_code, "3")
        unit_code = UNIT_MAP.get(pt.units, "")

        obj = {
            "type": obj_type,
            "instance": str(pt.row),
            "name": f"{{device-name}}-{pt.name}",
            "description": pt.description,
            "range": range_code,
            "unit": unit_code if obj_type == "AO" else "",
            "increment": "0.100000" if obj_type == "AO" else "",
            "present_value": "0.000000" if obj_type == "AO" else "0",
        }
        if obj_type == "AO":
            obj["min_value"] = str(pt.min_v)
            obj["max_value"] = str(pt.max_v)
        objects[obj_type][key] = obj

    # VALUES → AV, BV, MV objects
    for val in config.values:
        obj_type = val.point_type  # "AV", "BV", "MV"
        key = f"{obj_type}{val.instance}"
        unit_code = UNIT_MAP.get(val.units, "")

        pv = str(val.default)
        if obj_type == "BV":
            pv = "1" if val.default else "0"
        elif obj_type == "MV":
            pv = str(val.default)
        elif isinstance(val.default, (int, float)):
            pv = f"{float(val.default):.6f}"
        else:
            pv = str(val.default)

        desc = val.description
        if obj_type == "MV" and val.states:
            desc = "/".join([f"{k}-{v}" for k, v in sorted(val.states.items())])

        objects[obj_type][key] = {
            "type": obj_type,
            "instance": str(val.instance),
            "name": f"{{device-name}}-{val.name}",
            "description": desc,
            "range": "3" if obj_type == "AV" else ("3" if obj_type == "BV" else str(len(val.states)) if val.states else "2"),
            "unit": unit_code,
            "increment": "0.100000" if obj_type == "AV" else "",
            "present_value": pv,
        }

    # LOOPS
    for lp in config.loops:
        key = f"LOOP{lp.instance}"
        action = "1" if lp.action == "direct" else "0"
        objects["LOOP"][key] = {
            "instance": str(lp.instance),
            "name": f"{{device-name}}-{lp.name}",
            "proportional": f"{lp.p_band:.6f}",
            "integral": f"{lp.integral:.6f}",
            "derivative": f"{lp.derivative:.6f}",
            "action": action,
            "deadband": "0.000000",
            "bias": "0.000000",
            "integralunits": "1",  # minutes
            "input_ref": f"{device_instance}AI0",
            "input_type": "AI",
            "input_instance": "0",
            "input_name": f"{{device-name}}-{lp.input_ref}",
            "output_ref": "",
            "output_type": "",
            "output_instance": "",
            "output_name": "",
        }

    # PROGRAMS
    for prg in config.programs:
        key = f"PRG{prg.instance}"
        objects["PROGRAM"][key] = {
            "instance": str(prg.instance),
            "name": f"{{device-name}}-{prg.name}",
            "description": prg.description,
            "code": prg.code or "",
        }

    # TABLES
    for tbl in config.tables:
        key = f"TBL{tbl.instance}"
        rows = []
        for dp in tbl.data_points:
            rows.append({"in": f"{dp[0]:.6f}", "out": f"{dp[1]:.6f}"})
        # Pad to 16 rows (RC Studio expects fixed size)
        while len(rows) < 16:
            rows.append({"in": "0.000000", "out": "0.000000"})

        objects["TABLE"][key] = {
            "instance": str(tbl.instance),
            "name": f"{{device-name}}-{tbl.name}",
            "description": tbl.description,
            "unit": UNIT_MAP.get(tbl.output_units, ""),
            "inunit": UNIT_MAP.get(tbl.input_units, "11"),  # 11 = Volts
            "rows": rows,
        }

    # TRENDS
    for tr in config.trends:
        key = f"STL{tr.instance}"
        objects["TREND"][key] = {
            "instance": str(tr.instance),
            "name": f"{{device-name}}-{tr.name}",
            "interval": "900" if tr.trend_type == "polled" else "0",
            "logtype": "Polled" if tr.trend_type == "polled" else "COV",
            "enabled": "true",
            "type": "SINGLETREND",
            "references": [f"{device_instance}{tr.monitored_point}"],
        }

    # SCHEDULES
    for sch in config.schedules:
        key = f"SCHED{sch.instance}"
        objects["SCHEDULE"][key] = {
            "instance": str(sch.instance),
            "name": f"{{device-name}}-{sch.name}",
            "present_value": "1" if sch.default_state == "Occupied" else "0",
        }

    # SYSTEM GROUPS
    for i, sg in enumerate(config.system_groups, 1):
        key = f"GRP{i}"
        objects["SYSTEMGROUP"][key] = {
            "instance": str(i),
            "name": sg.name,
            "groupgraphic": "",
            "jsonpath": "",
            "autoupdate": "false",
        }

    # Build full library JSON
    result = {
        "id": f"SBS-COMPOSED-{config.controller_model}",
        "category": "SBS_COMPOSED",
        "format": "panx",
        "description": f"SBS Composition Engine v2 — {config.equipment_family}",
        "meta": {
            "Features": config.selected_modules,
            "Device": "",
            "Model": config.controller_model,
            "Database": "88" if "MPS" in config.controller_model else "44",
            "HardPointConfig": _get_hard_point_config(config),
        },
        "graphics": [],
        "objects": objects,
        "bas_files": {},
        "grp_files": {},
        "counts": {
            "AI": len([p for p in config.inputs if p.point_type == "AI"]),
            "AO": len([p for p in config.outputs if p.point_type == "AO"]),
            "AV": len([v for v in config.values if v.point_type == "AV"]),
            "BI": len([p for p in config.inputs if p.point_type == "BI"]),
            "BO": len([p for p in config.outputs if p.point_type == "BO"]),
            "BV": len([v for v in config.values if v.point_type == "BV"]),
            "MV": len([v for v in config.values if v.point_type == "MV"]),
            "PROGRAM": len(config.programs),
            "LOOP": len(config.loops),
            "TREND": len(config.trends),
        },
    }

    return result


def _get_hard_point_config(config: ControllerConfig) -> str:
    """Determine the HardPointConfig code for blank selection."""
    # MPS: 88 = Ethernet+MS/TP, 8C = Ethernet+MS/TP+expansion, etc.
    if config.controller_model in ("MPS", "MPWS", "MPV-LCD"):
        if config.expansion_count > 0:
            return "8C"
        return "88"
    elif config.controller_model == "MP2":
        if config.expansion_count > 0:
            return "8C"
        return "88"
    elif config.controller_model in ("MPC", "MPWC"):
        return "88"
    return "88"


def export_library_json(config: ControllerConfig, output_path: str):
    """Export the library JSON to a file."""
    data = config_to_library_json(config)
    with open(output_path, "w") as f:
        json.dump(data, f, indent=2)
    return data


if __name__ == "__main__":
    import sys, os
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from composition.assembler import assemble
    from composition.program_loader import inject_program_code
    from composition.module_registry import STANDARD_CONFIGS

    # Build SBS-AHU-114 (full featured)
    std = STANDARD_CONFIGS["SBS-AHU-114"]
    config = assemble(std["modules"])
    inject_program_code(config)

    out_path = "/srv/dfa/drops/SBS-AHU-114-library.json"
    data = export_library_json(config, out_path)

    print(f"Exported: {out_path}")
    print(f"Objects: {json.dumps(data['counts'], indent=2)}")
    print(f"Controller: {config.controller_model}")
    print(f"Programs: {len(config.programs)} with code")

    # Also try feeding it to the composer pipeline
    print(f"\nTo generate .pan: use composer /api/composer/compose endpoint")
    print(f"Or manually: load blank + merge via PFG")
