"""
HW-PLANT Pump Modules — Constant Speed, VFD, Primary/Secondary

All pump modules scale per number of pumps (1-4).
Lead/lag logic is only generated when N > 1.
Single pump gets simplified program with no lead/lag references.

Per-pump runtime tracking AVs stored in core CONFIG-PRG.
"""

from composition.models import (
    Module, InputPoint, OutputPoint, ValuePoint, LoopDef,
    ProgramDef, ScheduleDef, SystemGroupDef
)


def _gen_pump_lead_lag_code(num_pumps, prefix="HWP"):
    """Generate pump lead/lag .bas code dynamically. No boiler references."""
    d = "{device-name}"
    code = f"REM **** Pump Lead/Lag — {num_pumps} {prefix} pumps\n"
    code += "REM **** Generated by SBS Composition Engine v2\n\n"
    code += "REM **** Failover on failure or OOS ****\n"
    for n in range(1, num_pumps + 1):
        nxt = (n % num_pumps) + 1
        code += f"IF {d}-LEAD-{prefix} = {n} AND ({d}-{prefix}{n}-FAIL OR {d}-{prefix}{n}-OOS) THEN {d}-LEAD-{prefix} = {nxt}\n"
    code += f"\nREM **** Runtime-based rotation ****\n"
    for n in range(1, num_pumps + 1):
        nxt = (n % num_pumps) + 1
        code += f"IF {d}-LEAD-{prefix} = {n} AND {d}-{prefix}{n}-RUNTIME > {d}-{prefix}{nxt}-RUNTIME + 1 AND TIME-ON( {d}-LEAD-{prefix}-SS ) / 3600 > {d}-HWP-ROTATION-HOLD THEN {d}-LEAD-{prefix} = {nxt}\n"
    code += f"\n{d}-LEAD-{prefix} = LIMIT( {d}-LEAD-{prefix} , 1 , {num_pumps} )\n\n"
    code += "REM **** Lead failure flag ****\n"
    for n in range(1, num_pumps + 1):
        code += f"IF {d}-LEAD-{prefix} = {n} THEN {d}-LEAD-{prefix}-FAIL = {d}-{prefix}{n}-FAIL\n"
    code += f"\nIF NOT {d}-HW-SYS-ENAB THEN STOP {d}-LEAD-{prefix}-SS , STOP {d}-LAG-{prefix}-SS , END\n"
    code += f"START {d}-LEAD-{prefix}-SS\n"
    code += f"IF {d}-LEAD-{prefix}-FAIL THEN START {d}-LAG-{prefix}-SS ELSE STOP {d}-LAG-{prefix}-SS\n\n"
    code += "REM **** Any pump running ****\n"
    sts_list = " OR ".join(f"{d}-{prefix}{n}-STS" for n in range(1, num_pumps + 1))
    code += f"IF {sts_list} THEN START {d}-ANY-HWP-ON ELSE STOP {d}-ANY-HWP-ON\n"
    return code

# I/O rows for pump module — after boiler module
_PUMP_STS_BASE = 11      # BI: HWP1-STS at IN11, HWP2 at IN12
_PUMP_SS_BASE = 9        # BO: HWP1-S/S at OUT9, HWP2 at OUT10
_PUMP_SPD_BASE = 11      # AO: HWP1-SPEED at OUT11, HWP2 at OUT12 (VFD only)
_DP_INPUT_1 = 15         # AI: HW-PRESS1 at IN15
_DP_INPUT_2 = 16         # AI: HW-PRESS2 at IN16


def _common_pump_values(num_pumps):
    """Generate per-pump values shared across CS/VFD.
    Instance range 85+ (safe from boiler at 60-68, core at 75-84).
    ANY-HWP-ON is defined in hw-core (BV80) — not duplicated here.
    """
    values = []
    for n in range(1, num_pumps + 1):
        values.append(ValuePoint(85 + (n-1)*3, f"HWP{n}-FAIL", "BV", False, f"HW Pump {n} Failure"))
        values.append(ValuePoint(86 + (n-1)*3, f"HWP{n}-OOS", "BV", False, f"HW Pump {n} Out of Service"))
        values.append(ValuePoint(87 + (n-1)*3, f"HWP{n}-RUNTIME", "AV", 0.0, f"HW Pump {n} Runtime", "Hrs"))
    return values


def build_pump_cs(num_pumps=2):
    """Constant speed pumps with lead/lag."""
    inputs = []
    outputs = []
    values = []

    for n in range(1, num_pumps + 1):
        outputs.append(OutputPoint(
            _PUMP_SS_BASE + n - 1, f"HWP{n}-S/S", "BO", "Stop/Start",
            f"HW Pump {n} Start/Stop"))
        inputs.append(InputPoint(
            _PUMP_STS_BASE + n - 1, f"HWP{n}-STS", "BI", "Off/On",
            f"HW Pump {n} Status"))

    values.extend(_common_pump_values(num_pumps))

    if num_pumps > 1:
        values.extend([
            ValuePoint(97, "LEAD-HWP",      "AV", 1.0,  "Lead Pump Number", "#"),
            ValuePoint(98, "LEAD-HWP-SS",   "BV", False, "Lead Pump Start/Stop"),
            ValuePoint(99, "LAG-HWP-SS",    "BV", False, "Lag Pump Start/Stop"),
            ValuePoint(100, "LEAD-HWP-FAIL", "BV", False, "Lead Pump Failure"),
        ])

    if num_pumps == 1:
        programs = [
            ProgramDef(16, "HW-HWP1-PRG", "HW-PRG16-HWP1-SINGLE.bas", "", True,
                       "HW pump 1 start/stop (single pump)", "hw-pump-cs", exec_order=16),
        ]
    else:
        programs = [
            ProgramDef(16, "HW-HWP1-PRG", "HW-PRG16-HWP1.bas", "", True,
                       "HW pump 1 start/stop", "hw-pump-cs", exec_order=16),
            ProgramDef(19, "HW-HWP2-PRG", "HW-PRG19-HWP2.bas", "", True,
                       "HW pump 2 start/stop", "hw-pump-cs", exec_order=19),
            ProgramDef(17, "HW-LEAD-LAG-PRG", "HW-PRG17-LEAD-LAG.bas",
                       _gen_pump_lead_lag_code(num_pumps, "HWP"), True,
                       "Pump lead/lag rotation", "hw-pump-cs", exec_order=17),
        ]

    schedules = []
    if num_pumps > 1:
        schedules.append(ScheduleDef(3, "{device-name}-HWP-LEAD-SCHED", "Pump 1",
            [f"Pump {n}" for n in range(1, num_pumps + 1)], 10,
            "Pump lead rotation schedule"))

    return Module(
        id="hw-pump-cs",
        name=f"Constant Speed Pumps ({num_pumps})",
        category="hw-pump",
        description=f"{num_pumps} constant speed HW pump(s) with lead/lag",
        inputs=inputs, outputs=outputs, values=values,
        programs=programs, schedules=schedules,
        system_groups=[
            SystemGroupDef("{device-name}-PUMP-CTRL", "Pump status, lead/lag, failures"),
        ],
        soo_paragraph=f"""{num_pumps} constant speed hot water circulation pump(s) shall be provided.
{"Lead/lag rotation shall alternate the duty pump based on accumulated runtime hours. The pump with higher runtime shall yield lead to the other. If the lead pump fails (no status proof after configurable delay), the lag pump shall start automatically. Pump failure detection uses TIME-ON proof with SWITCH deadband." if num_pumps > 1 else "The pump shall start when the HW system is enabled and stop when disabled. Failure detection via TIME-ON proof with configurable delay."}
Pump status shall be monitored via current switch or auxiliary contact.
Out of service detection from output override mode.""",
        requires=["hw-core"],
        conflicts=["hw-pump-vfd", "hw-pump-pri-sec"],
        mutually_exclusive_group="hw-pump",
    )


def build_pump_vfd(num_pumps=2):
    """VFD pumps with differential pressure control."""
    inputs = []
    outputs = []
    values = []

    for n in range(1, num_pumps + 1):
        outputs.append(OutputPoint(
            _PUMP_SS_BASE + n - 1, f"HWP{n}-S/S", "BO", "Stop/Start",
            f"HW Pump {n} Start/Stop"))
        inputs.append(InputPoint(
            _PUMP_STS_BASE + n - 1, f"HWP{n}-STS", "BI", "Off/On",
            f"HW Pump {n} Status"))
        outputs.append(OutputPoint(
            _PUMP_SPD_BASE + (n-1)*2, f"HWP{n}-SPEED", "AO", "0.0 ->100%",
            f"HW Pump {n} VFD Speed", 2.0, 10.0))

    # DP sensors
    inputs.append(InputPoint(_DP_INPUT_1, "HW-PRESS1", "AI", "0 ->100% (0-5V)",
        "HW Differential Pressure 1", "PSI"))
    inputs.append(InputPoint(_DP_INPUT_2, "HW-PRESS2", "AI", "0 ->100% (0-5V)",
        "HW Differential Pressure 2", "PSI"))

    values.extend(_common_pump_values(num_pumps))

    # Speed and DP setpoints
    values.extend([
        ValuePoint(91, "HWP-MIN-SPEED",   "AV", 30.0,  "Pump Minimum Speed",    "%"),
        ValuePoint(92, "HWP-MAX-SPEED",   "AV", 100.0, "Pump Maximum Speed",    "%"),
        ValuePoint(93, "AVG-DP",          "AV", 0.0,   "Average Differential Pressure", "PSI"),
        ValuePoint(94, "HWS-DP-SP",       "AV", 12.0,  "DP Setpoint",           "PSI"),
    ])

    if num_pumps > 1:
        values.extend([
            ValuePoint(97, "LEAD-HWP",      "AV", 1.0,  "Lead Pump Number",   "#"),
            ValuePoint(98, "LEAD-HWP-SS",   "BV", False, "Lead Pump Start/Stop"),
            ValuePoint(99, "LAG-HWP-SS",    "BV", False, "Lag Pump Start/Stop"),
            ValuePoint(100, "LEAD-HWP-FAIL", "BV", False, "Lead Pump Failure"),
        ])

    # DP PID loop
    loops = [
        LoopDef(1, "HW-DP-LOOP", "AVG-DP", "HWS-DP-SP", "HWP1-SPEED",
                p_band=5.0, integral=60.0, action="direct",
                description="HW Differential Pressure Control"),
    ]

    if num_pumps == 1:
        programs = [
            ProgramDef(16, "HW-HWP1-PRG", "HW-PRG16-HWP1-SINGLE.bas", "", True,
                       "HW pump 1 start/stop (single pump)", "hw-pump-vfd", exec_order=16),
            ProgramDef(20, "HW-HWP1-SPEED-PRG", "HW-PRG20-HWP1-SPEED.bas", "", True,
                       "Pump 1 VFD speed from DP loop", "hw-pump-vfd", exec_order=20),
        ]
    else:
        programs = [
            ProgramDef(16, "HW-HWP1-PRG", "HW-PRG16-HWP1.bas", "", True,
                       "HW pump 1 start/stop", "hw-pump-vfd", exec_order=16),
            ProgramDef(19, "HW-HWP2-PRG", "HW-PRG19-HWP2.bas", "", True,
                       "HW pump 2 start/stop", "hw-pump-vfd", exec_order=19),
            ProgramDef(17, "HW-LEAD-LAG-PRG", "HW-PRG17-LEAD-LAG.bas",
                       _gen_pump_lead_lag_code(num_pumps, "HWP"), True,
                       "Pump lead/lag rotation", "hw-pump-vfd", exec_order=17),
            ProgramDef(20, "HW-HWP1-SPEED-PRG", "HW-PRG20-HWP1-SPEED.bas", "", True,
                       "Pump 1 VFD speed from DP loop", "hw-pump-vfd", exec_order=20),
            ProgramDef(21, "HW-HWP2-SPEED-PRG", "HW-PRG21-HWP2-SPEED.bas", "", True,
                       "Pump 2 VFD speed from DP loop", "hw-pump-vfd", exec_order=21),
        ]

    schedules = []
    if num_pumps > 1:
        schedules.append(ScheduleDef(3, "{device-name}-HWP-LEAD-SCHED", "Pump 1",
            [f"Pump {n}" for n in range(1, num_pumps + 1)], 10,
            "Pump lead rotation schedule"))

    return Module(
        id="hw-pump-vfd",
        name=f"VFD Pumps ({num_pumps})",
        category="hw-pump",
        description=f"{num_pumps} VFD HW pump(s) with DP control",
        inputs=inputs, outputs=outputs, values=values,
        loops=loops, programs=programs, schedules=schedules,
        system_groups=[
            SystemGroupDef("{device-name}-PUMP-CTRL", "Pump speed, DP, lead/lag, failures"),
        ],
        soo_paragraph=f"""{num_pumps} variable frequency drive hot water circulation pump(s)
shall be provided. Pump speed shall be controlled by a PID loop maintaining
differential pressure setpoint. Speed shall not ramp until HWS-T exceeds 110°F
(thermal interlock). {"Lead/lag rotation based on accumulated runtime hours." if num_pumps > 1 else ""}
Minimum and maximum speed limits shall be configurable.""",
        requires=["hw-core"],
        conflicts=["hw-pump-cs", "hw-pump-pri-sec"],
        mutually_exclusive_group="hw-pump",
    )


def build_pump_pri_sec(num_primary=2, num_secondary=2):
    """Primary/secondary pumping arrangement."""
    inputs = []
    outputs = []
    values = []

    # Primary loop temps
    inputs.append(InputPoint(16, "PRI-HWS-T", "AI", "10K -40 ->250",
        "Primary Loop HW Supply Temperature", "°F"))
    inputs.append(InputPoint(17, "PRI-HWR-T", "AI", "10K -40 ->250",
        "Primary Loop HW Return Temperature", "°F"))
    # Secondary loop temps
    inputs.append(InputPoint(18, "SEC-HWS-T", "AI", "10K -40 ->250",
        "Secondary Loop HW Supply Temperature", "°F"))
    inputs.append(InputPoint(19, "SEC-HWR-T", "AI", "10K -40 ->250",
        "Secondary Loop HW Return Temperature", "°F"))

    # Primary pumps — constant speed (instances 101+)
    for n in range(1, num_primary + 1):
        outputs.append(OutputPoint(
            _PUMP_SS_BASE + n - 1, f"PHWP{n}", "BO", "Stop/Start",
            f"Primary HW Pump {n}"))
        inputs.append(InputPoint(
            _PUMP_STS_BASE + n - 1, f"PHWP{n}-STS", "BI", "Off/On",
            f"Primary HW Pump {n} Status"))
        values.append(ValuePoint(101 + (n-1)*3, f"PHWP{n}-FAIL", "BV", False,
            f"Primary Pump {n} Failure"))
        values.append(ValuePoint(102 + (n-1)*3, f"PHWP{n}-OOS", "BV", False,
            f"Primary Pump {n} Out of Service"))
        values.append(ValuePoint(103 + (n-1)*3, f"PHWP{n}-RUNTIME", "AV", 0.0,
            f"Primary Pump {n} Runtime", "Hrs"))

    # Secondary pumps — VFD with DP control (instances 111+)
    sec_ss_base = _PUMP_SS_BASE + num_primary
    sec_sts_base = _PUMP_STS_BASE + num_primary
    sec_spd_base = 15
    for n in range(1, num_secondary + 1):
        outputs.append(OutputPoint(
            sec_ss_base + n - 1, f"SHWP{n}", "BO", "Stop/Start",
            f"Secondary HW Pump {n}"))
        inputs.append(InputPoint(
            sec_sts_base + n - 1, f"SHWP{n}-STS", "BI", "Off/On",
            f"Secondary HW Pump {n} Status"))
        outputs.append(OutputPoint(
            sec_spd_base + n - 1, f"SHWP{n}-SPEED", "AO", "0.0 ->100%",
            f"Secondary HW Pump {n} VFD Speed", 2.0, 10.0))
        values.append(ValuePoint(111 + (n-1)*3, f"SHWP{n}-FAIL", "BV", False,
            f"Secondary Pump {n} Failure"))
        values.append(ValuePoint(112 + (n-1)*3, f"SHWP{n}-OOS", "BV", False,
            f"Secondary Pump {n} Out of Service"))
        values.append(ValuePoint(113 + (n-1)*3, f"SHWP{n}-RUNTIME", "AV", 0.0,
            f"Secondary Pump {n} Runtime", "Hrs"))

    # DP sensor
    inputs.append(InputPoint(20, "HW-PRESS1", "AI", "0 ->100% (0-5V)",
        "HW Differential Pressure", "PSI"))

    # System values (121+)
    values.extend([
        ValuePoint(121, "HWS-DP-SP",       "AV", 12.0,  "Secondary DP Setpoint",  "PSI"),
        ValuePoint(122, "HWP-MIN-SPEED",   "AV", 30.0,  "Secondary Min Speed",    "%"),
        ValuePoint(123, "HWP-MAX-SPEED",   "AV", 100.0, "Secondary Max Speed",    "%"),
        ValuePoint(124, "PRI-DELTA-T",     "AV", 0.0,   "Primary Loop Delta T",   "°F"),
        ValuePoint(125, "SEC-DELTA-T",     "AV", 0.0,   "Secondary Loop Delta T", "°F"),
        ValuePoint(126, "AVG-DP",          "AV", 0.0,   "Average Differential Pressure", "PSI"),
        # ANY-HWP-ON is defined in hw-core (BV80) — not duplicated here
    ])

    # Lead/lag for secondary (131+)
    if num_secondary > 1:
        values.extend([
            ValuePoint(131, "LEAD-SHWP",       "AV", 1.0,  "Lead Secondary Pump Number", "#"),
            ValuePoint(132, "LEAD-SHWP-SS",    "BV", False, "Lead Secondary Pump S/S"),
            ValuePoint(133, "LAG-SHWP-SS",     "BV", False, "Lag Secondary Pump S/S"),
            ValuePoint(134, "LEAD-SHWP-FAIL",  "BV", False, "Lead Secondary Pump Failure"),
            ValuePoint(135, "ANY-SHWP-ON",     "BV", False, "Any Secondary Pump Running"),
        ])

    loops = [
        LoopDef(1, "HW-DP-LOOP", "HW-PRESS1", "HWS-DP-SP", "SHWP1-SPEED",
                p_band=5.0, integral=60.0, action="direct",
                description="Secondary HW Pump DP Control"),
    ]

    programs = [
        ProgramDef(16, "HW-PHWP-PRG", "HW-PRG16-PHWP.bas", "", True,
                   "Primary pump control", "hw-pump-pri-sec", exec_order=16),
        ProgramDef(22, "HW-SHWP1-PRG", "HW-PRG22-SHWP1.bas", "", True,
                   "Secondary pump 1 start/stop", "hw-pump-pri-sec", exec_order=22),
        ProgramDef(24, "HW-SHWP1-SPEED-PRG", "HW-PRG24-SHWP1-SPEED.bas", "", True,
                   "Secondary pump 1 VFD speed", "hw-pump-pri-sec", exec_order=24),
    ]
    if num_secondary > 1:
        programs.append(ProgramDef(23, "HW-SHWP2-PRG", "HW-PRG23-SHWP2.bas", "", True,
                   "Secondary pump 2 start/stop", "hw-pump-pri-sec", exec_order=23))
        programs.append(ProgramDef(25, "HW-SHWP2-SPEED-PRG", "HW-PRG25-SHWP2-SPEED.bas", "", True,
                   "Secondary pump 2 VFD speed", "hw-pump-pri-sec", exec_order=25))
        programs.append(ProgramDef(26, "HW-SHWP-LEAD-LAG-PRG", "HW-PRG26-SHWP-LEAD-LAG.bas", "", True,
                   "Secondary pump lead/lag rotation", "hw-pump-pri-sec", exec_order=26))

    schedules = []
    if num_secondary > 1:
        schedules.append(ScheduleDef(3, "{device-name}-SHWP-LEAD-SCHED", "Pump 1",
            [f"Pump {n}" for n in range(1, num_secondary + 1)], 10,
            "Secondary pump lead rotation schedule"))

    return Module(
        id="hw-pump-pri-sec",
        name=f"Primary/Secondary Pumps ({num_primary}P+{num_secondary}S)",
        category="hw-pump",
        description=f"{num_primary} primary + {num_secondary} secondary VFD pumps with DP",
        inputs=inputs, outputs=outputs, values=values,
        loops=loops, programs=programs, schedules=schedules,
        system_groups=[
            SystemGroupDef("{device-name}-PUMP-CTRL", "Primary/secondary pumps, DP, speed"),
        ],
        soo_paragraph=f"""{num_primary} constant speed primary pump(s) shall circulate water through
the boiler loop. {num_secondary} variable frequency drive secondary pump(s) shall distribute
water to the building loop with DP control. Speed shall not ramp until supply temp
exceeds 110°F. {"Secondary pump lead/lag rotation based on runtime hours." if num_secondary > 1 else ""}""",
        requires=["hw-core"],
        conflicts=["hw-pump-cs", "hw-pump-vfd"],
        mutually_exclusive_group="hw-pump",
    )
