REM **** Chiller Control Program
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Enable/disable chiller based on system status, pump proof, and safeties

REM **** Check out of service ****
IF {device-name}-CHLR1-OOS THEN STOP {device-name}-CHLR1-S/S , END

REM **** Check chiller alarm — do not restart until reset ****
IF {device-name}-CHLR1-ALARM THEN STOP {device-name}-CHLR1-S/S , STOP {device-name}-CHLR1-FAIL , START {device-name}-CHLR1-FAIL , END

REM **** Min off time — prevent short cycling ****
IF NOT {device-name}-CHLR1-S/S AND TIME-OFF( {device-name}-CHLR1-S/S ) < {device-name}-CHLR-MIN-OFF-TIME THEN END

REM **** Enable chiller when: system enabled AND primary pump proven AND chiller in service ****
IF {device-name}-CHW-SYS-ENAB AND {device-name}-ANY-CHWP-ON AND NOT {device-name}-CHLR1-ALARM AND NOT {device-name}-CHLR1-OOS THEN GOTO 100

REM **** Conditions not met — stop chiller ****
STOP {device-name}-CHLR1-S/S
END

REM **** Start chiller ****
100 REM **** Determine if this chiller is lead or should start ****
IF {device-name}-LEAD-CHLR < 2 THEN A = {device-name}-LEAD-CHLR-SS
IF {device-name}-LEAD-CHLR >= 2 THEN A = {device-name}-LAG-CHLR-SS

REM **** Start/stop based on lead/lag command ****
IF A AND NOT {device-name}-CHLR1-OOS THEN START {device-name}-CHLR1-S/S ELSE STOP {device-name}-CHLR1-S/S

REM **** Alarm detection with delay ****
B = SWITCH( B , TIME-ON( {device-name}-CHLR1-S/S ) , 0 , {device-name}-CHLR-ALARM-DELAY )
IF B AND {device-name}-CHLR1-ALARM THEN START {device-name}-CHLR1-FAIL
IF NOT {device-name}-CHLR1-ALARM THEN STOP {device-name}-CHLR1-FAIL

REM **** Send setpoint to chiller ****
{device-name}-CHLR1-CHWS-SP = {device-name}-ACT-CHWS-TEMP-SP

REM **** Reset failure on safety reset ****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-CHLR1-FAIL
