REM **** Chilled Water Supply Temperature Setpoint
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** OA reset with valve position feedback trim
REM **** REVERSE from HW: higher OAT = lower setpoint (more cooling)

REM **** OA Reset — SLIDE from OA range to CHW range ****
REM **** At min OAT -> max CHW temp (less cooling), at max OAT -> min CHW temp (more cooling) ****
{device-name}-CHW-OA-RESET = SLIDE( {device-name}-NET-OAT , {device-name}-CFG-RESET-OA-MIN , {device-name}-CFG-RESET-OA-MAX , {device-name}-CFG-CHWS-MAX , {device-name}-CFG-CHWS-MIN )

REM **** Valve position feedback trim ****
REM **** Only apply when AHU data is available (NET-CHV-POS-MAX > 0) ****
IF {device-name}-NET-CHV-POS-MAX > 0 THEN GOTO 100

REM **** No AHU data — use OA reset only ****
{device-name}-ACT-CHWS-TEMP-SP = {device-name}-CHW-OA-RESET
GOTO 200

REM **** AHU data available — apply valve offset ****
100 REM **** If max valve pos > MAX-CHW-VLV-SP, decrease setpoint (more cooling) ****
REM **** If max valve pos < MAX-CHW-VLV-SP, increase setpoint (less cooling) ****
{device-name}-CHW-VLV-OFFSET = SLIDE( {device-name}-NET-CHV-POS-MAX , 0 , 100 , 2 , -2 )
{device-name}-ACT-CHWS-TEMP-SP = {device-name}-CHW-OA-RESET + {device-name}-CHW-VLV-OFFSET

REM **** Clamp to configured min/max ****
200 {device-name}-ACT-CHWS-TEMP-SP = LIMIT( {device-name}-ACT-CHWS-TEMP-SP , {device-name}-CFG-CHWS-MIN , {device-name}-CFG-CHWS-MAX )
