REM **** Cooling Tower CW Bypass Valve Program
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Bypass valve prevents CW from getting too cold in mild weather

REM **** If no CW pump running, close bypass valve ****
IF NOT {device-name}-ANY-CDWP-ON THEN {device-name}-CT-BYP-VLV = 0 , END

REM **** Enable bypass when CDW entering temp approaches bypass setpoint ****
REM **** Bypass opens to mix warm return water with cold tower water ****
REM **** Loop output via SLIDE — lower CDW-ENT-T = more bypass ****
A = {device-name}-CT-BYP-VLV
B = SLIDE( {device-name}-CDW-ENT-T , {device-name}-CT-BYPASS-SPT - 10 , {device-name}-CT-BYPASS-SPT , 100 , 0 )

REM **** Ramp bypass valve ****
{device-name}-CT-BYP-VLV = RAMP( ABS( A - B ) > 1 , A , B , 1.6667 )
IF ABS( A - B ) < 1 THEN {device-name}-CT-BYP-VLV = B

REM **** Clamp valve position ****
{device-name}-CT-BYP-VLV = LIMIT( {device-name}-CT-BYP-VLV , 0 , 100 )
