REM **** Chiller Lead/Lag Program
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Runtime-based chiller rotation with failure swap

REM **** Immediate failover on chiller failure ****
IF {device-name}-LEAD-CHLR < 2 AND {device-name}-CHLR1-FAIL THEN {device-name}-LEAD-CHLR = 2
IF {device-name}-LEAD-CHLR < 2 AND {device-name}-CHLR1-OOS THEN {device-name}-LEAD-CHLR = 2
IF {device-name}-LEAD-CHLR >= 2 AND {device-name}-CHLR2-FAIL THEN {device-name}-LEAD-CHLR = 1
IF {device-name}-LEAD-CHLR >= 2 AND {device-name}-CHLR2-OOS THEN {device-name}-LEAD-CHLR = 1

REM **** Runtime-based rotation — swap when higher runtime chiller is lead ****
REM **** Only swap if rotation hold time has elapsed ****
IF {device-name}-CHLR1-RUNTIME > {device-name}-CHLR2-RUNTIME AND {device-name}-LEAD-CHLR < 2 AND {device-name}-CHLR1-RUNTIME - {device-name}-CHLR2-RUNTIME > 1 AND TIME-ON( {device-name}-LEAD-CHLR-SS ) / 3600 > {device-name}-CHLR-ROTATION-HOLD THEN {device-name}-LEAD-CHLR = 2
IF {device-name}-CHLR2-RUNTIME > {device-name}-CHLR1-RUNTIME AND {device-name}-LEAD-CHLR >= 2 AND {device-name}-CHLR2-RUNTIME - {device-name}-CHLR1-RUNTIME > 1 AND TIME-ON( {device-name}-LEAD-CHLR-SS ) / 3600 > {device-name}-CHLR-ROTATION-HOLD THEN {device-name}-LEAD-CHLR = 1

REM **** Clamp lead chiller to valid range ****
{device-name}-LEAD-CHLR = LIMIT( {device-name}-LEAD-CHLR , 1 , 2 )

REM **** Set lead chiller failure flag ****
IF {device-name}-LEAD-CHLR < 2 THEN {device-name}-LEAD-CHLR-FAIL = {device-name}-CHLR1-FAIL
IF {device-name}-LEAD-CHLR >= 2 THEN {device-name}-LEAD-CHLR-FAIL = {device-name}-CHLR2-FAIL

REM **** System off — stop all chiller commands ****
IF NOT {device-name}-CHW-SYS-ENAB THEN STOP {device-name}-LEAD-CHLR-SS , STOP {device-name}-LAG-CHLR-SS , END

REM **** System on — start lead chiller ****
START {device-name}-LEAD-CHLR-SS

REM **** Start lag chiller ONLY if lead has failed ****
IF {device-name}-LEAD-CHLR-FAIL THEN START {device-name}-LAG-CHLR-SS ELSE STOP {device-name}-LAG-CHLR-SS
