REM **** Condenser Water Pump 1 S/S Program
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** CW pump starts with its paired chiller

REM **** Determine out of service from output mode ****
IF SELECT( {device-name}-CDWP1-S/S ) <> 1 THEN START {device-name}-CDWP1-OOS ELSE STOP {device-name}-CDWP1-OOS

REM **** Check out of service ****
IF {device-name}-CDWP1-OOS THEN STOP {device-name}-CDWP1-S/S , END

REM **** Check pump failure — do not restart until reset ****
IF {device-name}-CDWP1-FAIL THEN STOP {device-name}-CDWP1-S/S , END

REM **** Start CW pump when its paired chiller is commanded on ****
IF {device-name}-CHLR1-S/S AND NOT {device-name}-CDWP1-OOS THEN START {device-name}-CDWP1-S/S ELSE STOP {device-name}-CDWP1-S/S

REM **** Failure detection — SWITCH deadband on proof timing ****
B = SWITCH( B , TIME-ON( {device-name}-CDWP1-S/S ) , 0 , {device-name}-CDWP-STOP-DELAY )
IF B AND NOT {device-name}-CDWP1-STS THEN START {device-name}-CDWP1-FAIL
IF {device-name}-CDWP1-STS THEN STOP {device-name}-CDWP1-FAIL

REM **** Reset failure on safety reset ****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-CDWP1-FAIL
