REM **** Cooling Tower Fan Control Program
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Wet bulb approach reset for CW supply temp, fan speed from PID

REM **** If no CW pump running, stop tower fan and end ****
IF NOT {device-name}-ANY-CDWP-ON THEN {device-name}-CT1-FAN-SPEED = 0 , STOP {device-name}-CT1-FAN-S/S , END

REM **** Calculate approximate wet bulb from OAT and OAH ****
REM **** Simplified wet bulb: WB = OAT * ATAN(0.151977 * SQRT(OAH + 8.313659)) ****
REM **** Using ENTHALPY-based approximation for Control-BASIC ****
{device-name}-OA-WET-BULB = {device-name}-NET-OAT - ( ( 100 - {device-name}-NET-OAH ) / 5 )

REM **** Reset CW supply temp setpoint based on wet bulb + approach ****
{device-name}-CDWS-T-SP = {device-name}-OA-WET-BULB + {device-name}-CFG-CT-APPROACH

REM **** Clamp CDWS-T setpoint to configured min/max ****
{device-name}-CDWS-T-SP = LIMIT( {device-name}-CDWS-T-SP , {device-name}-CFG-CT-MIN-CDWS-SP , {device-name}-CFG-CT-MAX-CDWS-SP )

REM **** Start tower fan when CW pump is running ****
IF {device-name}-ANY-CDWP-ON THEN START {device-name}-CT1-FAN-S/S ELSE STOP {device-name}-CT1-FAN-S/S

REM **** Scale CDWS-T loop output to fan speed range ****
A = {device-name}-CT1-FAN-SPEED
B = SLIDE( loop2 , 0 , 100 , {device-name}-CT-FAN-MIN-SPEED , {device-name}-CT-FAN-MAX-SPEED )

REM **** Ramp fan speed ****
{device-name}-CT1-FAN-SPEED = RAMP( ABS( A - B ) > 1 , A , B , {device-name}-CT-FAN-RAMP-RATE * 1.6667 )
IF ABS( A - B ) < 1 THEN {device-name}-CT1-FAN-SPEED = B

REM **** Zero speed if fan not commanded ****
IF NOT {device-name}-CT1-FAN-S/S THEN {device-name}-CT1-FAN-SPEED = 0
