REM **** CHW Plant Configuration Program
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Network reads, enthalpy, runtime tracking, DP averaging

REM **** Set outside air variables from hardwired sensors ****
{device-name}-NET-OAT = {device-name}-OAT
{device-name}-NET-OAH = {device-name}-OAH

REM **** Calculate outside air enthalpy ****
{device-name}-NET-OA-ERH = ENTHALPY( {device-name}-NET-OAT , {device-name}-NET-OAH , 1 )

REM **** Calculate CHW delta T ****
{device-name}-CHW-DELTA-T = {device-name}-CHWR-T - {device-name}-CHWS-T

REM **** Flow monitoring ****
IF {device-name}-CHW-FLOW > 0 THEN {device-name}-CHW-FLOW-TTL = {device-name}-CHW-FLOW-TTL + {device-name}-CHW-FLOW * INTERVAL / 60

REM **** Pump runtime tracking (hours) ****
{device-name}-PCHWP1-RUNTIME = TIME-ON( {device-name}-PCHWP1-STS ) / 3600
{device-name}-PCHWP2-RUNTIME = TIME-ON( {device-name}-PCHWP2-STS ) / 3600

REM **** Secondary pump runtime tracking (hours) ****
{device-name}-SCHWP1-RUNTIME = TIME-ON( {device-name}-SCHWP1-STS ) / 3600
{device-name}-SCHWP2-RUNTIME = TIME-ON( {device-name}-SCHWP2-STS ) / 3600

REM **** DP sensor averaging ****
{device-name}-AVG-DP = ABS( ( {device-name}-CHW-PRESS1 + {device-name}-CHW-PRESS2 ) / 2 )
