REM **** CHW Bypass Valve Control
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Modulate bypass based on CHW bypass temp vs setpoint

REM **** Set bypass PID setpoint ****
{device-name}-CHW-BYP-PID-SP = {device-name}-CHW-BYP-SP

REM **** Modulate bypass valve from PID loop ****
A = {device-name}-CHW-BYP-VLV
B = loop3

REM **** When system enabled, modulate valve; otherwise close ****
IF {device-name}-CHW-SYS-ENAB THEN {device-name}-CHW-BYP-VLV = RAMP( ABS( A - B ) > 1 , A , B , 1.6667 ) ELSE {device-name}-CHW-BYP-VLV = 0
IF ABS( A - B ) < 1 THEN {device-name}-CHW-BYP-VLV = B

REM **** Clamp valve position ****
{device-name}-CHW-BYP-VLV = LIMIT( {device-name}-CHW-BYP-VLV , 0 , 100 )
