REM **** Cooling Tower Lead/Lag Program
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Tower lead/lag with failure swap

REM **** Immediate failover on tower failure ****
IF {device-name}-LEAD-CT < 2 AND {device-name}-CT1-FAIL THEN {device-name}-LEAD-CT = 2
IF {device-name}-LEAD-CT < 2 AND {device-name}-CT1-OOS THEN {device-name}-LEAD-CT = 2
IF {device-name}-LEAD-CT >= 2 AND {device-name}-CT2-FAIL THEN {device-name}-LEAD-CT = 1
IF {device-name}-LEAD-CT >= 2 AND {device-name}-CT2-OOS THEN {device-name}-LEAD-CT = 1

REM **** Runtime-based rotation ****
IF {device-name}-CT1-RUNTIME > {device-name}-CT2-RUNTIME AND {device-name}-LEAD-CT < 2 AND {device-name}-CT1-RUNTIME - {device-name}-CT2-RUNTIME > 1 AND TIME-ON( {device-name}-LEAD-CT-SS ) / 3600 > {device-name}-CT-ROTATION-HOLD THEN {device-name}-LEAD-CT = 2
IF {device-name}-CT2-RUNTIME > {device-name}-CT1-RUNTIME AND {device-name}-LEAD-CT >= 2 AND {device-name}-CT2-RUNTIME - {device-name}-CT1-RUNTIME > 1 AND TIME-ON( {device-name}-LEAD-CT-SS ) / 3600 > {device-name}-CT-ROTATION-HOLD THEN {device-name}-LEAD-CT = 1

REM **** Clamp lead tower to valid range ****
{device-name}-LEAD-CT = LIMIT( {device-name}-LEAD-CT , 1 , 2 )

REM **** Set lead tower failure flag ****
IF {device-name}-LEAD-CT < 2 THEN {device-name}-LEAD-CT-FAIL = {device-name}-CT1-FAIL
IF {device-name}-LEAD-CT >= 2 THEN {device-name}-LEAD-CT-FAIL = {device-name}-CT2-FAIL

REM **** System off — stop all tower commands ****
IF NOT {device-name}-ANY-CDWP-ON THEN STOP {device-name}-LEAD-CT-SS , STOP {device-name}-LAG-CT-SS , END

REM **** System on — start lead tower ****
START {device-name}-LEAD-CT-SS

REM **** Start lag tower ONLY if lead has failed ****
IF {device-name}-LEAD-CT-FAIL THEN START {device-name}-LAG-CT-SS ELSE STOP {device-name}-LAG-CT-SS

REM **** Any tower running ****
IF {device-name}-CT1-FAN-STS OR {device-name}-CT2-FAN-STS THEN START {device-name}-ANY-CT-ON ELSE STOP {device-name}-ANY-CT-ON
