REM **** Primary CHW Pump 2 S/S Program
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Pump starts when system enabled and pump is in lead
REM **** or system enabled and lead pump has failed

REM **** Determine out of service from output mode ****
IF SELECT( {device-name}-PCHWP2-S/S ) <> 1 THEN START {device-name}-PCHWP2-OOS ELSE STOP {device-name}-PCHWP2-OOS

REM **** Check out of service ****
IF {device-name}-PCHWP2-OOS THEN STOP {device-name}-PCHWP2-S/S , END

REM **** Check pump failure — do not restart until reset ****
IF {device-name}-PCHWP2-FAIL THEN STOP {device-name}-PCHWP2-S/S , END

REM **** Determine if pump 2 is lead or lag ****
IF {device-name}-LEAD-PCHWP >= 2 THEN A = {device-name}-LEAD-PCHWP-SS
IF {device-name}-LEAD-PCHWP < 2 THEN A = {device-name}-LAG-PCHWP-SS

REM **** Start/stop pump ****
IF A AND NOT {device-name}-PCHWP2-OOS THEN START {device-name}-PCHWP2-S/S ELSE STOP {device-name}-PCHWP2-S/S

REM **** Failure detection — SWITCH deadband on proof timing ****
B = SWITCH( B , TIME-ON( {device-name}-PCHWP2-S/S ) , 0 , {device-name}-CHWP-STOP-DELAY )
IF B AND NOT {device-name}-PCHWP2-STS THEN START {device-name}-PCHWP2-FAIL
IF {device-name}-PCHWP2-STS THEN STOP {device-name}-PCHWP2-FAIL

REM **** Reset failure on safety reset ****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-PCHWP2-FAIL
