REM **** CHW Plant System Status
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** CHW enable logic, availability, delta-T monitoring

REM **** System enable — OAT must be ABOVE enable setpoint for cooling ****
REM **** SWITCH with 3 degree deadband — enable when OAT rises above SP ****
A = SWITCH( A , {device-name}-NET-OAT , {device-name}-CFG-OAT-ENBL-SP , {device-name}-CFG-OAT-ENBL-SP + 3 )
IF A THEN START {device-name}-CHW-SYS-ENAB ELSE STOP {device-name}-CHW-SYS-ENAB

REM **** Valve position override — if AHU valves demanding cooling, keep enabled ****
IF {device-name}-NET-CHV-POS-MAX > 50 AND {device-name}-NET-OAT > {device-name}-CFG-OAT-ENBL-SP - 5 THEN START {device-name}-CHW-SYS-ENAB

REM **** CHW Available — requires ALL of: system enabled, pump running, supply temp < 55F ****
IF {device-name}-CHW-SYS-ENAB AND {device-name}-ANY-CHWP-ON AND {device-name}-CHWS-T < 55 THEN START {device-name}-CHW-AVAIL ELSE STOP {device-name}-CHW-AVAIL

REM **** Low delta-T alarm — if pumps running and delta-T < 3F, possible flow issue ****
IF {device-name}-ANY-CHWP-ON AND {device-name}-CHW-DELTA-T < {device-name}-LOW-DELTA-T-SP AND TIME-ON( {device-name}-ANY-CHWP-ON ) > 0:05:00 THEN START {device-name}-LOW-DELTA-T ELSE STOP {device-name}-LOW-DELTA-T
