REM **** Secondary CHW Pump 3 VFD Speed
REM **** Generated by SBS Composition Engine v2 — CHW Plant

IF NOT {device-name}-SCHWP3-S/S THEN {device-name}-SCHWP3-SPEED = 0 , END
IF {device-name}-AVG-DP > {device-name}-CHWS-DP-SP + 5 THEN {device-name}-SCHWP3-SPEED = {device-name}-SCHWP-MIN-SPEED , END

A = {device-name}-SCHWP3-SPEED
B = SLIDE( loop1 , 0 , 100 , {device-name}-SCHWP-MIN-SPEED , {device-name}-SCHWP-MAX-SPEED )
{device-name}-SCHWP3-SPEED = RAMP( ABS( A - B ) > 1 , A , B , {device-name}-SCHWP-RAMP-RATE * 1.6667 )
IF ABS( A - B ) < 1 THEN {device-name}-SCHWP3-SPEED = B
