REM **** Network Data Reads from AHUs
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Populate CHW valve position aggregates from AHU data

REM **** Read CHW valve positions from AHU network data ****
REM **** Each AHU reports its CHW valve position via BACnet ****

REM **** Calculate MIN of all AHU CHW valve positions ****
{device-name}-NET-CHV-POS-MIN = MIN( {device-name}-AHU1-CHV-POS , {device-name}-AHU2-CHV-POS , {device-name}-AHU3-CHV-POS , {device-name}-AHU4-CHV-POS )

REM **** Calculate MAX of all AHU CHW valve positions ****
{device-name}-NET-CHV-POS-MAX = MAX( {device-name}-AHU1-CHV-POS , {device-name}-AHU2-CHV-POS , {device-name}-AHU3-CHV-POS , {device-name}-AHU4-CHV-POS )

REM **** Calculate AVG of all AHU CHW valve positions ****
{device-name}-NET-CHV-POS-AVG = AVG( {device-name}-AHU1-CHV-POS , {device-name}-AHU2-CHV-POS , {device-name}-AHU3-CHV-POS , {device-name}-AHU4-CHV-POS )

REM **** Aggregate cooling requests from AHUs ****
{device-name}-TOTAL-CLG-REQUESTS = {device-name}-AHU1-CLG-DMD + {device-name}-AHU2-CLG-DMD + {device-name}-AHU3-CLG-DMD + {device-name}-AHU4-CLG-DMD

REM **** Count AHUs requesting cooling (valve > 50%) ****
{device-name}-AHUS-REQUESTING-CLG = 0
IF {device-name}-AHU1-CHV-POS > 50 THEN {device-name}-AHUS-REQUESTING-CLG = {device-name}-AHUS-REQUESTING-CLG + 1
IF {device-name}-AHU2-CHV-POS > 50 THEN {device-name}-AHUS-REQUESTING-CLG = {device-name}-AHUS-REQUESTING-CLG + 1
IF {device-name}-AHU3-CHV-POS > 50 THEN {device-name}-AHUS-REQUESTING-CLG = {device-name}-AHUS-REQUESTING-CLG + 1
IF {device-name}-AHU4-CHV-POS > 50 THEN {device-name}-AHUS-REQUESTING-CLG = {device-name}-AHUS-REQUESTING-CLG + 1
