REM **** Primary CHW Pump 1 S/S Program — Single Pump
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Single pump variant — no lead/lag logic needed

REM **** Determine out of service from output mode ****
IF SELECT( {device-name}-PCHWP1-S/S ) <> 1 THEN START {device-name}-PCHWP1-OOS ELSE STOP {device-name}-PCHWP1-OOS

REM **** Check out of service ****
IF {device-name}-PCHWP1-OOS THEN STOP {device-name}-PCHWP1-S/S , END

REM **** Check pump failure — do not restart until reset ****
IF {device-name}-PCHWP1-FAIL THEN STOP {device-name}-PCHWP1-S/S , END

REM **** Start pump when system enabled ****
IF {device-name}-CHW-SYS-ENAB AND NOT {device-name}-PCHWP1-OOS THEN START {device-name}-PCHWP1-S/S ELSE STOP {device-name}-PCHWP1-S/S

REM **** Failure detection — SWITCH deadband on proof timing ****
B = SWITCH( B , TIME-ON( {device-name}-PCHWP1-S/S ) , 0 , {device-name}-CHWP-STOP-DELAY )
IF B AND NOT {device-name}-PCHWP1-STS THEN START {device-name}-PCHWP1-FAIL
IF {device-name}-PCHWP1-STS THEN STOP {device-name}-PCHWP1-FAIL

REM **** Any pump running ****
IF {device-name}-PCHWP1-STS THEN START {device-name}-ANY-CHWP-ON ELSE STOP {device-name}-ANY-CHWP-ON

REM **** Reset failure on safety reset ****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-PCHWP1-FAIL
