REM **** Condenser Water Pump Lead/Lag Program
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** CW pump lead/lag follows chiller lead/lag

REM **** CW pump lead follows chiller lead ****
{device-name}-LEAD-CDWP = {device-name}-LEAD-CHLR

REM **** Override on CW pump failure — swap to other pump ****
IF {device-name}-LEAD-CDWP < 2 AND {device-name}-CDWP1-FAIL THEN {device-name}-LEAD-CDWP = 2
IF {device-name}-LEAD-CDWP < 2 AND {device-name}-CDWP1-OOS THEN {device-name}-LEAD-CDWP = 2
IF {device-name}-LEAD-CDWP >= 2 AND {device-name}-CDWP2-FAIL THEN {device-name}-LEAD-CDWP = 1
IF {device-name}-LEAD-CDWP >= 2 AND {device-name}-CDWP2-OOS THEN {device-name}-LEAD-CDWP = 1

REM **** Clamp to valid range ****
{device-name}-LEAD-CDWP = LIMIT( {device-name}-LEAD-CDWP , 1 , 2 )

REM **** Set lead CW pump failure flag ****
IF {device-name}-LEAD-CDWP < 2 THEN {device-name}-LEAD-CDWP-FAIL = {device-name}-CDWP1-FAIL
IF {device-name}-LEAD-CDWP >= 2 THEN {device-name}-LEAD-CDWP-FAIL = {device-name}-CDWP2-FAIL

REM **** Any CW pump running ****
IF {device-name}-CDWP1-STS OR {device-name}-CDWP2-STS THEN START {device-name}-ANY-CDWP-ON ELSE STOP {device-name}-ANY-CDWP-ON
