REM **** Secondary CHW Pump 3 S/S Program (Lag-2 Standby)
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Lag-2 pump starts on dual failure, failover, or excess demand

REM **** Determine out of service from output mode ****
IF SELECT( {device-name}-SCHWP3-S/S ) <> 1 THEN START {device-name}-SCHWP3-OOS ELSE STOP {device-name}-SCHWP3-OOS

REM **** Check out of service ****
IF {device-name}-SCHWP3-OOS THEN STOP {device-name}-SCHWP3-S/S , END

REM **** Check pump failure — do not restart until reset ****
IF {device-name}-SCHWP3-FAIL THEN STOP {device-name}-SCHWP3-S/S , END

REM **** START conditions for lag-2 pump ****
REM **** Condition 1: both lead and lag-1 pumps have failed ****
IF {device-name}-SCHWP1-FAIL AND {device-name}-SCHWP2-FAIL AND NOT {device-name}-SCHWP3-OOS THEN START {device-name}-SCHWP3-S/S , END

REM **** Condition 2: lead running, lag-1 failed, system still needs 2 pumps ****
IF {device-name}-LEAD-SCHWP-SS AND ({device-name}-SCHWP1-FAIL OR {device-name}-SCHWP2-FAIL) AND {device-name}-ANY-SCHWP-ON AND NOT {device-name}-SCHWP3-OOS THEN START {device-name}-SCHWP3-S/S , END

REM **** Condition 3: demand exceeds 2-pump capacity — DP cannot keep up ****
IF {device-name}-LEAD-SCHWP-SS AND {device-name}-LAG-SCHWP-SS AND {device-name}-AVG-DP < {device-name}-CHWS-DP-SP - 3 AND NOT {device-name}-SCHWP3-OOS THEN START {device-name}-SCHWP3-S/S , END

REM **** STOP when demand drops and lag-1 is healthy ****
IF {device-name}-AVG-DP > {device-name}-CHWS-DP-SP AND NOT {device-name}-SCHWP1-FAIL AND NOT {device-name}-SCHWP2-FAIL THEN STOP {device-name}-SCHWP3-S/S

REM **** Failure detection — SWITCH deadband on proof timing ****
B = SWITCH( B , TIME-ON( {device-name}-SCHWP3-S/S ) , 0 , {device-name}-SCHWP-STOP-DELAY )
IF B AND NOT {device-name}-SCHWP3-STS THEN START {device-name}-SCHWP3-FAIL
IF {device-name}-SCHWP3-STS THEN STOP {device-name}-SCHWP3-FAIL
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-SCHWP3-FAIL
