REM **** Secondary CHW Pump 1 VFD Speed
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Speed from DP PID loop output

REM **** Zero speed if pump not commanded on ****
IF NOT {device-name}-SCHWP1-S/S THEN {device-name}-SCHWP1-SPEED = 0 , END

REM **** Scale DP loop output to speed range ****
A = {device-name}-SCHWP1-SPEED
B = SLIDE( loop1 , 0 , 100 , {device-name}-SCHWP-MIN-SPEED , {device-name}-SCHWP-MAX-SPEED )

REM **** Ramp speed with configurable rate ****
{device-name}-SCHWP1-SPEED = RAMP( ABS( A - B ) > 1 , A , B , {device-name}-SCHWP-RAMP-RATE * 1.6667 )
IF ABS( A - B ) < 1 THEN {device-name}-SCHWP1-SPEED = B
