REM **** Secondary CHW Pump Lead/Lag Program
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Runtime-based pump rotation with failure swap

REM **** Immediate failover on pump failure ****
IF {device-name}-LEAD-SCHWP < 2 AND {device-name}-SCHWP1-FAIL THEN {device-name}-LEAD-SCHWP = 2
IF {device-name}-LEAD-SCHWP < 2 AND {device-name}-SCHWP1-OOS THEN {device-name}-LEAD-SCHWP = 2
IF {device-name}-LEAD-SCHWP >= 2 AND {device-name}-SCHWP2-FAIL THEN {device-name}-LEAD-SCHWP = 1
IF {device-name}-LEAD-SCHWP >= 2 AND {device-name}-SCHWP2-OOS THEN {device-name}-LEAD-SCHWP = 1

REM **** Runtime-based rotation — swap when higher runtime pump is lead ****
IF {device-name}-SCHWP1-RUNTIME > {device-name}-SCHWP2-RUNTIME AND {device-name}-LEAD-SCHWP < 2 AND {device-name}-SCHWP1-RUNTIME - {device-name}-SCHWP2-RUNTIME > 1 AND TIME-ON( {device-name}-LEAD-SCHWP-SS ) / 3600 > {device-name}-SCHWP-ROTATION-HOLD THEN {device-name}-LEAD-SCHWP = 2
IF {device-name}-SCHWP2-RUNTIME > {device-name}-SCHWP1-RUNTIME AND {device-name}-LEAD-SCHWP >= 2 AND {device-name}-SCHWP2-RUNTIME - {device-name}-SCHWP1-RUNTIME > 1 AND TIME-ON( {device-name}-LEAD-SCHWP-SS ) / 3600 > {device-name}-SCHWP-ROTATION-HOLD THEN {device-name}-LEAD-SCHWP = 1

REM **** Clamp lead pump to valid range ****
{device-name}-LEAD-SCHWP = LIMIT( {device-name}-LEAD-SCHWP , 1 , 2 )

REM **** Set lead pump failure flag ****
IF {device-name}-LEAD-SCHWP < 2 THEN {device-name}-LEAD-SCHWP-FAIL = {device-name}-SCHWP1-FAIL
IF {device-name}-LEAD-SCHWP >= 2 THEN {device-name}-LEAD-SCHWP-FAIL = {device-name}-SCHWP2-FAIL

REM **** System off — stop all pump commands ****
IF NOT {device-name}-CHW-SYS-ENAB THEN STOP {device-name}-LEAD-SCHWP-SS , STOP {device-name}-LAG-SCHWP-SS , END

REM **** System on — start lead pump ****
START {device-name}-LEAD-SCHWP-SS

REM **** Start lag pump ONLY if lead has failed ****
IF {device-name}-LEAD-SCHWP-FAIL THEN START {device-name}-LAG-SCHWP-SS ELSE STOP {device-name}-LAG-SCHWP-SS

REM **** Any secondary pump running ****
IF {device-name}-SCHWP1-STS OR {device-name}-SCHWP2-STS THEN START {device-name}-ANY-SCHWP-ON ELSE STOP {device-name}-ANY-SCHWP-ON
