REM **** Chiller Isolation Valve Control
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Open valve BEFORE chiller enable, close AFTER disable with delay

REM **** Chiller 1 isolation valve — open when chiller commanded ****
IF {device-name}-CHLR1-SS OR {device-name}-CHLR1-S/S THEN START {device-name}-CHLR1-ISO-VLV
IF NOT {device-name}-CHLR1-SS AND NOT {device-name}-CHLR1-S/S AND TIME-OFF( {device-name}-CHLR1-S/S ) > {device-name}-ISO-VLV-OPEN-DLY THEN STOP {device-name}-CHLR1-ISO-VLV

REM **** Chiller 2 isolation valve ****
IF {device-name}-CHLR2-SS OR {device-name}-CHLR2-S/S THEN START {device-name}-CHLR2-ISO-VLV
IF NOT {device-name}-CHLR2-SS AND NOT {device-name}-CHLR2-S/S AND TIME-OFF( {device-name}-CHLR2-S/S ) > {device-name}-ISO-VLV-OPEN-DLY THEN STOP {device-name}-CHLR2-ISO-VLV
