REM **** Condenser Water Pump 3 S/S Program (Lag-2 Standby)
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Lag-2 pump starts on dual failure, failover, or excess demand

REM **** Determine out of service from output mode ****
IF SELECT( {device-name}-CDWP3-S/S ) <> 1 THEN START {device-name}-CDWP3-OOS ELSE STOP {device-name}-CDWP3-OOS

REM **** Check out of service ****
IF {device-name}-CDWP3-OOS THEN STOP {device-name}-CDWP3-S/S , END

REM **** Check pump failure — do not restart until reset ****
IF {device-name}-CDWP3-FAIL THEN STOP {device-name}-CDWP3-S/S , END

REM **** START conditions for lag-2 pump ****
REM **** Condition 1: both lead and lag-1 pumps have failed ****
IF {device-name}-CDWP1-FAIL AND {device-name}-CDWP2-FAIL AND NOT {device-name}-CDWP3-OOS THEN START {device-name}-CDWP3-S/S , END

REM **** Condition 2: lead running, lag-1 failed, system still needs 2 CW pumps ****
IF {device-name}-LEAD-CDWP-SS AND ({device-name}-CDWP1-FAIL OR {device-name}-CDWP2-FAIL) AND {device-name}-ANY-CDWP-ON AND NOT {device-name}-CDWP3-OOS THEN START {device-name}-CDWP3-S/S , END

REM **** Condition 3: both lead and lag-1 running, 3rd chiller needs CW flow ****
IF {device-name}-CHLR3-S/S AND NOT {device-name}-CDWP3-OOS THEN START {device-name}-CDWP3-S/S , END

REM **** STOP when demand drops and lag-1 is healthy ****
IF NOT {device-name}-CHLR3-S/S AND NOT {device-name}-CDWP1-FAIL AND NOT {device-name}-CDWP2-FAIL THEN STOP {device-name}-CDWP3-S/S

REM **** Failure detection — SWITCH deadband on proof timing ****
B = SWITCH( B , TIME-ON( {device-name}-CDWP3-S/S ) , 0 , {device-name}-CDWP-STOP-DELAY )
IF B AND NOT {device-name}-CDWP3-STS THEN START {device-name}-CDWP3-FAIL
IF {device-name}-CDWP3-STS THEN STOP {device-name}-CDWP3-FAIL

REM **** Reset failure on safety reset ****
IF {device-name}-RESET-SAFETIES THEN STOP {device-name}-CDWP3-FAIL
