REM **** Primary CHW Pump Lead/Lag Program
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Runtime-based pump rotation with failure swap

REM **** Immediate failover on pump failure ****
IF {device-name}-LEAD-PCHWP < 2 AND {device-name}-PCHWP1-FAIL THEN {device-name}-LEAD-PCHWP = 2
IF {device-name}-LEAD-PCHWP < 2 AND {device-name}-PCHWP1-OOS THEN {device-name}-LEAD-PCHWP = 2
IF {device-name}-LEAD-PCHWP >= 2 AND {device-name}-PCHWP2-FAIL THEN {device-name}-LEAD-PCHWP = 1
IF {device-name}-LEAD-PCHWP >= 2 AND {device-name}-PCHWP2-OOS THEN {device-name}-LEAD-PCHWP = 1

REM **** Runtime-based rotation — swap when higher runtime pump is lead ****
IF {device-name}-PCHWP1-RUNTIME > {device-name}-PCHWP2-RUNTIME AND {device-name}-LEAD-PCHWP < 2 AND {device-name}-PCHWP1-RUNTIME - {device-name}-PCHWP2-RUNTIME > 1 AND TIME-ON( {device-name}-LEAD-PCHWP-SS ) / 3600 > {device-name}-CHWP-ROTATION-HOLD THEN {device-name}-LEAD-PCHWP = 2
IF {device-name}-PCHWP2-RUNTIME > {device-name}-PCHWP1-RUNTIME AND {device-name}-LEAD-PCHWP >= 2 AND {device-name}-PCHWP2-RUNTIME - {device-name}-PCHWP1-RUNTIME > 1 AND TIME-ON( {device-name}-LEAD-PCHWP-SS ) / 3600 > {device-name}-CHWP-ROTATION-HOLD THEN {device-name}-LEAD-PCHWP = 1

REM **** Clamp lead pump to valid range ****
{device-name}-LEAD-PCHWP = LIMIT( {device-name}-LEAD-PCHWP , 1 , 2 )

REM **** Set lead pump failure flag ****
IF {device-name}-LEAD-PCHWP < 2 THEN {device-name}-LEAD-PCHWP-FAIL = {device-name}-PCHWP1-FAIL
IF {device-name}-LEAD-PCHWP >= 2 THEN {device-name}-LEAD-PCHWP-FAIL = {device-name}-PCHWP2-FAIL

REM **** System off — stop all pump commands ****
IF NOT {device-name}-CHW-SYS-ENAB THEN STOP {device-name}-LEAD-PCHWP-SS , STOP {device-name}-LAG-PCHWP-SS , END

REM **** System on — start lead pump ****
START {device-name}-LEAD-PCHWP-SS

REM **** Start lag pump ONLY if lead has failed ****
IF {device-name}-LEAD-PCHWP-FAIL THEN START {device-name}-LAG-PCHWP-SS ELSE STOP {device-name}-LAG-PCHWP-SS

REM **** Any pump running ****
IF {device-name}-PCHWP1-STS OR {device-name}-PCHWP2-STS THEN START {device-name}-ANY-CHWP-ON ELSE STOP {device-name}-ANY-CHWP-ON
