REM **** Secondary CHW Pump Lag Staging Program
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Stage on lag pump when DP drops, stage off when DP recovers

REM **** If system off, stop lag and end ****
IF NOT {device-name}-CHW-SYS-ENAB THEN STOP {device-name}-LAG-SCHWP-SS , END

REM **** If lead pump not running, do not stage lag ****
IF NOT {device-name}-LEAD-SCHWP-SS THEN STOP {device-name}-LAG-SCHWP-SS , END

REM **** Stage ON lag pump — DP below start setpoint for delay period ****
REM **** TIME-ON() needs a local reference, not a comparison — latch into A ****
IF {device-name}-AVG-DP < {device-name}-SCHWP-LAG-START-SP THEN START A ELSE STOP A
IF TIME-ON( A ) > {device-name}-SCHWP-LAG-START-DLY THEN START {device-name}-LAG-SCHWP-SS

REM **** Stage OFF lag pump — DP above stop setpoint for delay period ****
REM **** Latch the stop condition into B ****
IF {device-name}-AVG-DP > {device-name}-SCHWP-LAG-STOP-SP THEN START B ELSE STOP B
IF TIME-ON( B ) > {device-name}-SCHWP-LAG-STOP-DLY THEN STOP {device-name}-LAG-SCHWP-SS

REM **** Failover — if lead fails, force lag on ****
IF {device-name}-LEAD-SCHWP-FAIL THEN START {device-name}-LAG-SCHWP-SS
