REM **** Chiller Isolation Valve Control
REM **** Generated by SBS Composition Engine v2 — CHW Plant
REM **** Open valve BEFORE chiller enable, close AFTER disable with delay

REM **** Chiller 1 isolation valve — open when chiller commanded ****
IF {device-name}-CHLR1-SS THEN START {device-name}-CHLR1-CHW-ISO
IF NOT {device-name}-CHLR1-SS AND TIME-OFF( {device-name}-CHLR1-SS ) > {device-name}-ISO-VLV-OPEN-DLY THEN STOP {device-name}-CHLR1-CHW-ISO

REM **** Chiller 2 isolation valve ****
IF {device-name}-CHLR2-SS THEN START {device-name}-CHLR2-CHW-ISO
IF NOT {device-name}-CHLR2-SS AND TIME-OFF( {device-name}-CHLR2-SS ) > {device-name}-ISO-VLV-OPEN-DLY THEN STOP {device-name}-CHLR2-CHW-ISO
